version: 2.1
orbs:
  aws-cli: circleci/aws-cli@0.1.19
jobs:
  deploy-stg:
    executor: aws-cli/default
    steps:

      - checkout
      - aws-cli/setup:
          profile-name: college-metrics

      - run:
          name: Install Node and NPM
          command: |
            sudo curl -sL https://deb.nodesource.com/setup_10.x | sudo -E bash -
            sudo apt-get install nodejs build-essential libssl-dev

      - run:
          name: Build and Deplot to stg
          command: |
            export DEPLOY_BUCKET=va-college-metrics-dashboard-stg
            npm install && npm run build && aws s3 sync build/ s3://$DEPLOY_BUCKET

workflows:
  version: 2
  aws-cli:
    jobs:
      - deploy-stg