// Do not manually modify this file or else it will be overwritten by the
// convert-excel-to-json.js script
const data =
/** START **/
{
  '4yr': {
    '6yr': [
      {
        'name': 'Averett University',
        'grad_rate_6yr': 46,
        'adj_6yr_grad_rate': 57,
        'white': 50,
        'black': 38,
        'male': 36,
        'female': 60,
        'nopell': 48,
        'pell': 44,
        'sat_lowest_quintile': 38,
        'sat_2nd_quintile': 50,
        'sat_mid_quintile': 49,
        'sat_4th_quintile': 69,
        'gpa_lowest_quintile': 37,
        'gpa_2nd_quintile': 56,
        'gpa_mid_quintile': 48,
        'gpa_4th_quintile': 51,
        'gpa_highest_quintile': 52
      },
      {
        'name': 'Bluefield College',
        'grad_rate_6yr': 34,
        'adj_6yr_grad_rate': 46,
        'white': 40,
        'black': 15,
        'otherrace': 35,
        'male': 24,
        'female': 47,
        'nopell': 44,
        'pell': 23,
        'sat_lowest_quintile': 31,
        'sat_2nd_quintile': 32,
        'sat_mid_quintile': 37,
        'gpa_lowest_quintile': 22,
        'gpa_2nd_quintile': 30,
        'gpa_mid_quintile': 46,
        'gpa_4th_quintile': 52
      },
      {
        'name': 'Bridgewater College',
        'grad_rate_6yr': 69,
        'adj_6yr_grad_rate': 70,
        'white': 71,
        'black': 54,
        'hispanic': 65,
        'otherrace': 63,
        'male': 65,
        'female': 72,
        'nopell': 72,
        'pell': 60,
        'sat_lowest_quintile': 59,
        'sat_2nd_quintile': 63,
        'sat_mid_quintile': 73,
        'sat_4th_quintile': 81,
        'sat_highest_quintile': 85,
        'gpa_lowest_quintile': 41,
        'gpa_2nd_quintile': 62,
        'gpa_mid_quintile': 71,
        'gpa_4th_quintile': 85,
        'gpa_highest_quintile': 93
      },
      {
        'name': 'Christopher Newport University',
        'grad_rate_6yr': 83,
        'adj_6yr_grad_rate': 79,
        'white': 84,
        'black': 71,
        'hispanic': 85,
        'asian': 85,
        'otherrace': 79,
        'male': 79,
        'female': 86,
        'nopell': 84,
        'pell': 78,
        'sat_lowest_quintile': 65,
        'sat_2nd_quintile': 81,
        'sat_mid_quintile': 83,
        'sat_4th_quintile': 85,
        'sat_highest_quintile': 82,
        'gpa_lowest_quintile': 59,
        'gpa_2nd_quintile': 75,
        'gpa_mid_quintile': 82,
        'gpa_4th_quintile': 88,
        'gpa_highest_quintile': 92
      },
      {
        'name': 'College of William and Mary',
        'grad_rate_6yr': 93,
        'adj_6yr_grad_rate': 79,
        'white': 94,
        'black': 89,
        'hispanic': 92,
        'asian': 87,
        'otherrace': 91,
        'male': 90,
        'female': 95,
        'nopell': 93,
        'pell': 89,
        'sat_2nd_quintile': 80,
        'sat_mid_quintile': 90,
        'sat_4th_quintile': 93,
        'sat_highest_quintile': 93,
        'gpa_2nd_quintile': 82,
        'gpa_mid_quintile': 87,
        'gpa_4th_quintile': 91,
        'gpa_highest_quintile': 95
      },
      {
        'name': 'Eastern Mennonite University',
        'grad_rate_6yr': 64,
        'adj_6yr_grad_rate': 65,
        'white': 70,
        'black': 39,
        'hispanic': 55,
        'otherrace': 46,
        'male': 58,
        'female': 68,
        'nopell': 69,
        'pell': 54,
        'sat_lowest_quintile': 45,
        'sat_2nd_quintile': 63,
        'sat_mid_quintile': 66,
        'sat_4th_quintile': 74,
        'sat_highest_quintile': 86,
        'gpa_lowest_quintile': 35,
        'gpa_2nd_quintile': 54,
        'gpa_mid_quintile': 63,
        'gpa_4th_quintile': 81,
        'gpa_highest_quintile': 92
      },
      {
        'name': 'Emory and Henry College',
        'grad_rate_6yr': 59,
        'adj_6yr_grad_rate': 62,
        'white': 61,
        'black': 51,
        'otherrace': 48,
        'male': 50,
        'female': 70,
        'nopell': 66,
        'pell': 49,
        'sat_lowest_quintile': 53,
        'sat_2nd_quintile': 57,
        'sat_mid_quintile': 60,
        'sat_4th_quintile': 66,
        'sat_highest_quintile': 75,
        'gpa_lowest_quintile': 38,
        'gpa_2nd_quintile': 51,
        'gpa_mid_quintile': 60,
        'gpa_4th_quintile': 69,
        'gpa_highest_quintile': 83
      },
      {
        'name': 'Ferrum College',
        'grad_rate_6yr': 36,
        'adj_6yr_grad_rate': 56,
        'white': 42,
        'black': 29,
        'hispanic': 44,
        'otherrace': 29,
        'male': 31,
        'female': 42,
        'nopell': 43,
        'pell': 31,
        'sat_lowest_quintile': 33,
        'sat_2nd_quintile': 39,
        'sat_mid_quintile': 47,
        'sat_4th_quintile': 48,
        'gpa_lowest_quintile': 27,
        'gpa_2nd_quintile': 51,
        'gpa_mid_quintile': 57,
        'gpa_4th_quintile': 56,
        'gpa_highest_quintile': 79
      },
      {
        'name': 'George Mason University',
        'grad_rate_6yr': 73,
        'adj_6yr_grad_rate': 71,
        'white': 73,
        'black': 72,
        'hispanic': 68,
        'asian': 77,
        'otherrace': 70,
        'male': 67,
        'female': 79,
        'nopell': 74,
        'pell': 70,
        'sat_lowest_quintile': 64,
        'sat_2nd_quintile': 72,
        'sat_mid_quintile': 75,
        'sat_4th_quintile': 73,
        'sat_highest_quintile': 71,
        'gpa_lowest_quintile': 53,
        'gpa_2nd_quintile': 64,
        'gpa_mid_quintile': 72,
        'gpa_4th_quintile': 78,
        'gpa_highest_quintile': 86
      },
      {
        'name': 'Hampden-Sydney College',
        'grad_rate_6yr': 69,
        'adj_6yr_grad_rate': 76,
        'white': 71,
        'black': 55,
        'otherrace': 65,
        'male': 69,
        'nopell': 71,
        'pell': 62,
        'sat_lowest_quintile': 54,
        'sat_2nd_quintile': 63,
        'sat_mid_quintile': 74,
        'sat_4th_quintile': 72,
        'sat_highest_quintile': 73,
        'gpa_lowest_quintile': 55,
        'gpa_2nd_quintile': 65,
        'gpa_mid_quintile': 74,
        'gpa_4th_quintile': 78,
        'gpa_highest_quintile': 90
      },
      {
        'name': 'Hampton University',
        'grad_rate_6yr': 53,
        'adj_6yr_grad_rate': 63,
        'white': 43,
        'black': 53,
        'hispanic': 55,
        'otherrace': 71,
        'male': 48,
        'female': 56,
        'nopell': 58,
        'pell': 45,
        'sat_lowest_quintile': 50,
        'sat_2nd_quintile': 53,
        'sat_mid_quintile': 55,
        'sat_4th_quintile': 62,
        'sat_highest_quintile': 61,
        'gpa_lowest_quintile': 46,
        'gpa_2nd_quintile': 53,
        'gpa_mid_quintile': 58,
        'gpa_4th_quintile': 67,
        'gpa_highest_quintile': 79
      },
      {
        'name': 'Hollins University',
        'grad_rate_6yr': 60,
        'adj_6yr_grad_rate': 58,
        'white': 61,
        'black': 52,
        'hispanic': 47,
        'otherrace': 60,
        'female': 60,
        'nopell': 65,
        'pell': 52,
        'sat_lowest_quintile': 51,
        'sat_2nd_quintile': 48,
        'sat_mid_quintile': 61,
        'sat_4th_quintile': 64,
        'sat_highest_quintile': 76,
        'gpa_lowest_quintile': 40,
        'gpa_2nd_quintile': 49,
        'gpa_mid_quintile': 57,
        'gpa_4th_quintile': 67,
        'gpa_highest_quintile': 84
      },
      {
        'name': 'James Madison University',
        'grad_rate_6yr': 86,
        'adj_6yr_grad_rate': 79,
        'white': 87,
        'black': 73,
        'hispanic': 84,
        'asian': 88,
        'otherrace': 84,
        'male': 82,
        'female': 89,
        'nopell': 88,
        'pell': 78,
        'sat_lowest_quintile': 72,
        'sat_2nd_quintile': 84,
        'sat_mid_quintile': 88,
        'sat_4th_quintile': 88,
        'sat_highest_quintile': 87,
        'gpa_lowest_quintile': 65,
        'gpa_2nd_quintile': 74,
        'gpa_mid_quintile': 83,
        'gpa_4th_quintile': 89,
        'gpa_highest_quintile': 92
      },
      {
        'name': 'Jefferson College of Health Sciences',
        'grad_rate_6yr': 47,
        'adj_6yr_grad_rate': 52,
        'white': 52,
        'male': 56,
        'female': 44,
        'nopell': 60,
        'pell': 32,
        'sat_lowest_quintile': 31,
        'sat_2nd_quintile': 59,
        'gpa_lowest_quintile': 14,
        'gpa_2nd_quintile': 41,
        'gpa_mid_quintile': 70,
        'gpa_4th_quintile': 55
      },
      {
        'name': 'Liberty University',
        'grad_rate_6yr': 57,
        'adj_6yr_grad_rate': 63,
        'white': 60,
        'black': 38,
        'hispanic': 49,
        'asian': 57,
        'otherrace': 55,
        'male': 51,
        'female': 62,
        'nopell': 61,
        'pell': 46,
        'sat_lowest_quintile': 43,
        'sat_2nd_quintile': 55,
        'sat_mid_quintile': 64,
        'sat_4th_quintile': 69,
        'sat_highest_quintile': 75,
        'gpa_lowest_quintile': 35,
        'gpa_2nd_quintile': 54,
        'gpa_mid_quintile': 65,
        'gpa_4th_quintile': 77,
        'gpa_highest_quintile': 84
      },
      {
        'name': 'Longwood University',
        'grad_rate_6yr': 74,
        'adj_6yr_grad_rate': 76,
        'white': 74,
        'black': 73,
        'hispanic': 73,
        'asian': 77,
        'otherrace': 71,
        'male': 66,
        'female': 78,
        'nopell': 76,
        'pell': 66,
        'sat_lowest_quintile': 71,
        'sat_2nd_quintile': 75,
        'sat_mid_quintile': 74,
        'sat_4th_quintile': 75,
        'sat_highest_quintile': 63,
        'gpa_lowest_quintile': 57,
        'gpa_2nd_quintile': 71,
        'gpa_mid_quintile': 79,
        'gpa_4th_quintile': 85,
        'gpa_highest_quintile': 92
      },
      {
        'name': 'Lynchburg College',
        'grad_rate_6yr': 64,
        'adj_6yr_grad_rate': 71,
        'white': 65,
        'black': 58,
        'hispanic': 52,
        'otherrace': 60,
        'male': 57,
        'female': 69,
        'nopell': 66,
        'pell': 59,
        'sat_lowest_quintile': 56,
        'sat_2nd_quintile': 63,
        'sat_mid_quintile': 71,
        'sat_4th_quintile': 68,
        'sat_highest_quintile': 74,
        'gpa_lowest_quintile': 49,
        'gpa_2nd_quintile': 66,
        'gpa_mid_quintile': 73,
        'gpa_4th_quintile': 80,
        'gpa_highest_quintile': 88
      },
      {
        'name': 'Mary Baldwin College',
        'grad_rate_6yr': 49,
        'adj_6yr_grad_rate': 57,
        'white': 55,
        'black': 44,
        'hispanic': 51,
        'asian': 46,
        'otherrace': 41,
        'female': 49,
        'nopell': 53,
        'pell': 47,
        'sat_lowest_quintile': 47,
        'sat_2nd_quintile': 57,
        'sat_mid_quintile': 57,
        'sat_4th_quintile': 45,
        'gpa_lowest_quintile': 44,
        'gpa_2nd_quintile': 45,
        'gpa_mid_quintile': 58,
        'gpa_4th_quintile': 55,
        'gpa_highest_quintile': 67
      },
      {
        'name': 'Marymount University',
        'grad_rate_6yr': 59,
        'adj_6yr_grad_rate': 67,
        'white': 65,
        'black': 44,
        'hispanic': 58,
        'asian': 66,
        'otherrace': 59,
        'male': 52,
        'female': 61,
        'nopell': 62,
        'pell': 50,
        'sat_lowest_quintile': 53,
        'sat_2nd_quintile': 58,
        'sat_mid_quintile': 62,
        'sat_4th_quintile': 71,
        'sat_highest_quintile': 71,
        'gpa_lowest_quintile': 47,
        'gpa_2nd_quintile': 58,
        'gpa_mid_quintile': 74,
        'gpa_4th_quintile': 81,
        'gpa_highest_quintile': 79
      },
      {
        'name': 'Norfolk State University',
        'grad_rate_6yr': 38,
        'adj_6yr_grad_rate': 58,
        'white': 44,
        'black': 39,
        'hispanic': 35,
        'otherrace': 37,
        'male': 33,
        'female': 43,
        'nopell': 43,
        'pell': 36,
        'sat_lowest_quintile': 37,
        'sat_2nd_quintile': 39,
        'sat_mid_quintile': 51,
        'sat_4th_quintile': 50,
        'gpa_lowest_quintile': 31,
        'gpa_2nd_quintile': 48,
        'gpa_mid_quintile': 59,
        'gpa_4th_quintile': 72,
        'gpa_highest_quintile': 80
      },
      {
        'name': 'Old Dominion University',
        'grad_rate_6yr': 55,
        'adj_6yr_grad_rate': 61,
        'white': 57,
        'black': 51,
        'hispanic': 56,
        'asian': 58,
        'otherrace': 51,
        'male': 50,
        'female': 60,
        'nopell': 57,
        'pell': 50,
        'sat_lowest_quintile': 54,
        'sat_2nd_quintile': 52,
        'sat_mid_quintile': 57,
        'sat_4th_quintile': 59,
        'sat_highest_quintile': 56,
        'gpa_lowest_quintile': 42,
        'gpa_2nd_quintile': 53,
        'gpa_mid_quintile': 61,
        'gpa_4th_quintile': 72,
        'gpa_highest_quintile': 83
      },
      {
        'name': 'Radford University',
        'grad_rate_6yr': 66,
        'adj_6yr_grad_rate': 73,
        'white': 67,
        'black': 64,
        'hispanic': 61,
        'asian': 63,
        'otherrace': 64,
        'male': 59,
        'female': 71,
        'nopell': 68,
        'pell': 59,
        'sat_lowest_quintile': 64,
        'sat_2nd_quintile': 66,
        'sat_mid_quintile': 69,
        'sat_4th_quintile': 68,
        'sat_highest_quintile': 61,
        'gpa_lowest_quintile': 55,
        'gpa_2nd_quintile': 69,
        'gpa_mid_quintile': 74,
        'gpa_4th_quintile': 81,
        'gpa_highest_quintile': 89
      },
      {
        'name': 'Randolph College',
        'grad_rate_6yr': 70,
        'adj_6yr_grad_rate': 71,
        'white': 71,
        'black': 61,
        'hispanic': 65,
        'asian': 76,
        'otherrace': 70,
        'male': 66,
        'female': 73,
        'nopell': 72,
        'pell': 63,
        'sat_lowest_quintile': 65,
        'sat_2nd_quintile': 64,
        'sat_mid_quintile': 70,
        'sat_4th_quintile': 76,
        'sat_highest_quintile': 79,
        'gpa_lowest_quintile': 51,
        'gpa_2nd_quintile': 64,
        'gpa_mid_quintile': 72,
        'gpa_4th_quintile': 81,
        'gpa_highest_quintile': 87
      },
      {
        'name': 'Regent University',
        'grad_rate_6yr': 52,
        'adj_6yr_grad_rate': 54,
        'white': 59,
        'black': 30,
        'male': 49,
        'female': 55,
        'nopell': 60,
        'pell': 38,
        'sat_lowest_quintile': 39,
        'sat_2nd_quintile': 48,
        'sat_mid_quintile': 60,
        'sat_4th_quintile': 63,
        'gpa_lowest_quintile': 17,
        'gpa_2nd_quintile': 53,
        'gpa_mid_quintile': 56,
        'gpa_4th_quintile': 59,
        'gpa_highest_quintile': 77
      },
      {
        'name': 'Roanoke College',
        'grad_rate_6yr': 70,
        'adj_6yr_grad_rate': 71,
        'white': 71,
        'black': 70,
        'hispanic': 56,
        'otherrace': 69,
        'male': 62,
        'female': 75,
        'nopell': 72,
        'pell': 62,
        'sat_lowest_quintile': 56,
        'sat_2nd_quintile': 69,
        'sat_mid_quintile': 68,
        'sat_4th_quintile': 74,
        'sat_highest_quintile': 81,
        'gpa_lowest_quintile': 53,
        'gpa_2nd_quintile': 64,
        'gpa_mid_quintile': 70,
        'gpa_4th_quintile': 83,
        'gpa_highest_quintile': 90
      },
      {
        'name': 'Shenandoah University',
        'grad_rate_6yr': 62,
        'adj_6yr_grad_rate': 67,
        'white': 65,
        'black': 49,
        'hispanic': 62,
        'asian': 70,
        'otherrace': 52,
        'male': 53,
        'female': 71,
        'nopell': 67,
        'pell': 50,
        'sat_lowest_quintile': 53,
        'sat_2nd_quintile': 57,
        'sat_mid_quintile': 66,
        'sat_4th_quintile': 78,
        'sat_highest_quintile': 82,
        'gpa_lowest_quintile': 41,
        'gpa_2nd_quintile': 61,
        'gpa_mid_quintile': 74,
        'gpa_4th_quintile': 75,
        'gpa_highest_quintile': 92
      },
      {
        'name': 'Southern Virginia University',
        'grad_rate_6yr': 25,
        'adj_6yr_grad_rate': 34,
        'white': 27,
        'male': 15,
        'female': 37,
        'nopell': 27,
        'pell': 23,
        'sat_lowest_quintile': 20,
        'sat_2nd_quintile': 25,
        'sat_mid_quintile': 31,
        'sat_4th_quintile': 22,
        'sat_highest_quintile': 39,
        'gpa_lowest_quintile': 13,
        'gpa_2nd_quintile': 18,
        'gpa_mid_quintile': 41,
        'gpa_4th_quintile': 44,
        'gpa_highest_quintile': 35
      },
      {
        'name': 'Sweet Briar College',
        'grad_rate_6yr': 62,
        'adj_6yr_grad_rate': 65,
        'white': 68,
        'otherrace': 61,
        'female': 62,
        'nopell': 64,
        'pell': 58,
        'sat_lowest_quintile': 44,
        'sat_2nd_quintile': 65,
        'sat_mid_quintile': 69,
        'sat_4th_quintile': 75,
        'sat_highest_quintile': 65,
        'gpa_lowest_quintile': 48,
        'gpa_2nd_quintile': 52,
        'gpa_mid_quintile': 67,
        'gpa_4th_quintile': 74,
        'gpa_highest_quintile': 83
      },
      {
        'name': 'University of Mary Washington',
        'grad_rate_6yr': 77,
        'adj_6yr_grad_rate': 75,
        'white': 78,
        'black': 68,
        'hispanic': 75,
        'asian': 83,
        'otherrace': 76,
        'male': 70,
        'female': 81,
        'nopell': 78,
        'pell': 72,
        'sat_lowest_quintile': 63,
        'sat_2nd_quintile': 75,
        'sat_mid_quintile': 78,
        'sat_4th_quintile': 78,
        'sat_highest_quintile': 80,
        'gpa_lowest_quintile': 56,
        'gpa_2nd_quintile': 69,
        'gpa_mid_quintile': 78,
        'gpa_4th_quintile': 85,
        'gpa_highest_quintile': 89
      },
      {
        'name': 'University of Richmond',
        'grad_rate_6yr': 89,
        'adj_6yr_grad_rate': 82,
        'white': 90,
        'black': 87,
        'hispanic': 81,
        'asian': 92,
        'otherrace': 89,
        'male': 88,
        'female': 90,
        'nopell': 89,
        'pell': 92,
        'sat_2nd_quintile': 86,
        'sat_mid_quintile': 86,
        'sat_4th_quintile': 85,
        'sat_highest_quintile': 91,
        'gpa_lowest_quintile': 86,
        'gpa_2nd_quintile': 79,
        'gpa_mid_quintile': 89,
        'gpa_4th_quintile': 90,
        'gpa_highest_quintile': 91
      },
      {
        'name': 'University of Virginia',
        'grad_rate_6yr': 96,
        'adj_6yr_grad_rate': 79,
        'white': 97,
        'black': 93,
        'hispanic': 94,
        'asian': 96,
        'otherrace': 96,
        'male': 95,
        'female': 98,
        'nopell': 97,
        'pell': 93,
        'sat_lowest_quintile': 82,
        'sat_2nd_quintile': 94,
        'sat_mid_quintile': 95,
        'sat_4th_quintile': 96,
        'sat_highest_quintile': 96,
        'gpa_lowest_quintile': 65,
        'gpa_2nd_quintile': 89,
        'gpa_mid_quintile': 95,
        'gpa_4th_quintile': 96,
        'gpa_highest_quintile': 97
      },
      {
        'name': 'University of Virginia\'s College at Wise',
        'grad_rate_6yr': 51,
        'adj_6yr_grad_rate': 59,
        'white': 52,
        'black': 45,
        'otherrace': 51,
        'male': 45,
        'female': 57,
        'nopell': 56,
        'pell': 46,
        'sat_lowest_quintile': 44,
        'sat_2nd_quintile': 53,
        'sat_mid_quintile': 62,
        'sat_4th_quintile': 67,
        'gpa_lowest_quintile': 34,
        'gpa_2nd_quintile': 45,
        'gpa_mid_quintile': 58,
        'gpa_4th_quintile': 69,
        'gpa_highest_quintile': 83
      },
      {
        'name': 'Virginia Commonwealth University',
        'grad_rate_6yr': 66,
        'adj_6yr_grad_rate': 66,
        'white': 66,
        'black': 63,
        'hispanic': 63,
        'asian': 70,
        'otherrace': 63,
        'male': 60,
        'female': 70,
        'nopell': 67,
        'pell': 61,
        'sat_lowest_quintile': 61,
        'sat_2nd_quintile': 64,
        'sat_mid_quintile': 66,
        'sat_4th_quintile': 67,
        'sat_highest_quintile': 69,
        'gpa_lowest_quintile': 47,
        'gpa_2nd_quintile': 60,
        'gpa_mid_quintile': 68,
        'gpa_4th_quintile': 75,
        'gpa_highest_quintile': 84
      },
      {
        'name': 'Virginia Military Institute',
        'grad_rate_6yr': 79,
        'adj_6yr_grad_rate': 81,
        'white': 80,
        'black': 62,
        'hispanic': 73,
        'asian': 87,
        'male': 79,
        'female': 78,
        'nopell': 81,
        'pell': 69,
        'sat_lowest_quintile': 58,
        'sat_2nd_quintile': 73,
        'sat_mid_quintile': 80,
        'sat_4th_quintile': 85,
        'sat_highest_quintile': 78,
        'gpa_lowest_quintile': 57,
        'gpa_2nd_quintile': 78,
        'gpa_mid_quintile': 86,
        'gpa_4th_quintile': 83,
        'gpa_highest_quintile': 90
      },
      {
        'name': 'Virginia State University',
        'grad_rate_6yr': 46,
        'adj_6yr_grad_rate': 66,
        'white': 34,
        'black': 48,
        'hispanic': 43,
        'otherrace': 41,
        'male': 40,
        'female': 50,
        'nopell': 51,
        'pell': 44,
        'sat_lowest_quintile': 45,
        'sat_2nd_quintile': 48,
        'sat_mid_quintile': 51,
        'sat_4th_quintile': 58,
        'gpa_lowest_quintile': 41,
        'gpa_2nd_quintile': 55,
        'gpa_mid_quintile': 60,
        'gpa_4th_quintile': 66,
        'gpa_highest_quintile': 85
      },
      {
        'name': 'Virginia Tech',
        'grad_rate_6yr': 89,
        'adj_6yr_grad_rate': 79,
        'white': 90,
        'black': 79,
        'hispanic': 90,
        'asian': 91,
        'otherrace': 87,
        'male': 86,
        'female': 94,
        'nopell': 91,
        'pell': 83,
        'sat_lowest_quintile': 76,
        'sat_2nd_quintile': 85,
        'sat_mid_quintile': 88,
        'sat_4th_quintile': 91,
        'sat_highest_quintile': 90,
        'gpa_lowest_quintile': 62,
        'gpa_2nd_quintile': 76,
        'gpa_mid_quintile': 83,
        'gpa_4th_quintile': 90,
        'gpa_highest_quintile': 92
      },
      {
        'name': 'Virginia Union University',
        'grad_rate_6yr': 39,
        'adj_6yr_grad_rate': 64,
        'black': 40,
        'male': 34,
        'female': 43,
        'nopell': 43,
        'pell': 38,
        'sat_lowest_quintile': 40,
        'sat_2nd_quintile': 43,
        'gpa_lowest_quintile': 36,
        'gpa_2nd_quintile': 55,
        'gpa_mid_quintile': 58
      },
      {
        'name': 'Virginia Wesleyan College',
        'grad_rate_6yr': 55,
        'adj_6yr_grad_rate': 65,
        'white': 58,
        'black': 51,
        'hispanic': 52,
        'otherrace': 54,
        'male': 50,
        'female': 58,
        'nopell': 59,
        'pell': 48,
        'sat_lowest_quintile': 46,
        'sat_2nd_quintile': 55,
        'sat_mid_quintile': 62,
        'sat_4th_quintile': 71,
        'sat_highest_quintile': 69,
        'gpa_lowest_quintile': 41,
        'gpa_2nd_quintile': 60,
        'gpa_mid_quintile': 58,
        'gpa_4th_quintile': 78,
        'gpa_highest_quintile': 88
      },
      {
        'name': 'Washington and Lee University',
        'grad_rate_6yr': 98,
        'adj_6yr_grad_rate': 86,
        'white': 98,
        'male': 97,
        'nopell': 98,
        'sat_highest_quintile': 98
      },
      {
        'name': 'State Average',
        'white': 76,
        'black': 54,
        'hispanic': 70,
        'asian': 80,
        'otherrace': 67,
        'male': 67,
        'female': 75,
        'nopell': 76,
        'pell': 58,
        'sat_lowest_quintile': 49,
        'sat_2nd_quintile': 64,
        'sat_mid_quintile': 73,
        'sat_4th_quintile': 80,
        'sat_highest_quintile': 86,
        'gpa_lowest_quintile': 43,
        'gpa_2nd_quintile': 61,
        'gpa_mid_quintile': 74,
        'gpa_4th_quintile': 84,
        'gpa_highest_quintile': 92
      }
    ],
    '4yr': [
      {
        'name': 'Averett University',
        'grad_rate_4yr': 34,
        'adj_4yr_grad_rate': 48,
        'white': 40,
        'black': 23,
        'male': 26,
        'female': 46,
        'nopell': 39,
        'pell': 31,
        'sat_lowest_quintile': 25,
        'sat_2nd_quintile': 43,
        'sat_mid_quintile': 40,
        'sat_4th_quintile': 53,
        'gpa_lowest_quintile': 26,
        'gpa_2nd_quintile': 43,
        'gpa_mid_quintile': 35,
        'gpa_4th_quintile': 38,
        'gpa_highest_quintile': 48
      },
      {
        'name': 'Bluefield College',
        'grad_rate_4yr': 20,
        'adj_4yr_grad_rate': 36,
        'white': 26,
        'black': 5,
        'otherrace': 17,
        'male': 12,
        'female': 31,
        'nopell': 26,
        'pell': 14,
        'sat_lowest_quintile': 14,
        'sat_2nd_quintile': 22,
        'sat_mid_quintile': 33,
        'gpa_lowest_quintile': 7,
        'gpa_2nd_quintile': 20,
        'gpa_mid_quintile': 31,
        'gpa_4th_quintile': 39
      },
      {
        'name': 'Bridgewater College',
        'grad_rate_4yr': 53,
        'adj_4yr_grad_rate': 55,
        'white': 57,
        'black': 35,
        'hispanic': 45,
        'otherrace': 46,
        'male': 44,
        'female': 60,
        'nopell': 57,
        'pell': 44,
        'sat_lowest_quintile': 42,
        'sat_2nd_quintile': 47,
        'sat_mid_quintile': 59,
        'sat_4th_quintile': 67,
        'sat_highest_quintile': 76,
        'gpa_lowest_quintile': 22,
        'gpa_2nd_quintile': 41,
        'gpa_mid_quintile': 55,
        'gpa_4th_quintile': 75,
        'gpa_highest_quintile': 87
      },
      {
        'name': 'Christopher Newport University',
        'grad_rate_4yr': 64,
        'adj_4yr_grad_rate': 59,
        'white': 66,
        'black': 44,
        'hispanic': 67,
        'asian': 61,
        'otherrace': 61,
        'male': 54,
        'female': 73,
        'nopell': 66,
        'pell': 53,
        'sat_lowest_quintile': 38,
        'sat_2nd_quintile': 63,
        'sat_mid_quintile': 62,
        'sat_4th_quintile': 68,
        'sat_highest_quintile': 63,
        'gpa_lowest_quintile': 32,
        'gpa_2nd_quintile': 49,
        'gpa_mid_quintile': 61,
        'gpa_4th_quintile': 72,
        'gpa_highest_quintile': 83
      },
      {
        'name': 'College of William and Mary',
        'grad_rate_4yr': 82,
        'adj_4yr_grad_rate': 64,
        'white': 86,
        'black': 70,
        'hispanic': 80,
        'asian': 75,
        'otherrace': 80,
        'male': 77,
        'female': 87,
        'nopell': 83,
        'pell': 75,
        'sat_2nd_quintile': 59,
        'sat_mid_quintile': 71,
        'sat_4th_quintile': 77,
        'sat_highest_quintile': 84,
        'gpa_2nd_quintile': 57,
        'gpa_mid_quintile': 68,
        'gpa_4th_quintile': 78,
        'gpa_highest_quintile': 88
      },
      {
        'name': 'Eastern Mennonite University',
        'grad_rate_4yr': 46,
        'adj_4yr_grad_rate': 47,
        'white': 54,
        'black': 16,
        'hispanic': 28,
        'otherrace': 26,
        'male': 36,
        'female': 52,
        'nopell': 52,
        'pell': 34,
        'sat_lowest_quintile': 24,
        'sat_2nd_quintile': 39,
        'sat_mid_quintile': 46,
        'sat_4th_quintile': 63,
        'sat_highest_quintile': 73,
        'gpa_lowest_quintile': 16,
        'gpa_2nd_quintile': 26,
        'gpa_mid_quintile': 48,
        'gpa_4th_quintile': 63,
        'gpa_highest_quintile': 83
      },
      {
        'name': 'Emory and Henry College',
        'grad_rate_4yr': 39,
        'adj_4yr_grad_rate': 44,
        'white': 43,
        'black': 23,
        'otherrace': 34,
        'male': 29,
        'female': 52,
        'nopell': 47,
        'pell': 28,
        'sat_lowest_quintile': 25,
        'sat_2nd_quintile': 40,
        'sat_mid_quintile': 46,
        'sat_4th_quintile': 48,
        'sat_highest_quintile': 69,
        'gpa_lowest_quintile': 15,
        'gpa_2nd_quintile': 30,
        'gpa_mid_quintile': 39,
        'gpa_4th_quintile': 51,
        'gpa_highest_quintile': 72
      },
      {
        'name': 'Ferrum College',
        'grad_rate_4yr': 19,
        'adj_4yr_grad_rate': 44,
        'white': 24,
        'black': 13,
        'hispanic': 19,
        'otherrace': 14,
        'male': 13,
        'female': 26,
        'nopell': 23,
        'pell': 16,
        'sat_lowest_quintile': 15,
        'sat_2nd_quintile': 26,
        'sat_mid_quintile': 24,
        'sat_4th_quintile': 40,
        'gpa_lowest_quintile': 12,
        'gpa_2nd_quintile': 26,
        'gpa_mid_quintile': 37,
        'gpa_4th_quintile': 44,
        'gpa_highest_quintile': 71
      },
      {
        'name': 'George Mason University',
        'grad_rate_4yr': 41,
        'adj_4yr_grad_rate': 39,
        'white': 45,
        'black': 42,
        'hispanic': 36,
        'asian': 34,
        'otherrace': 38,
        'male': 31,
        'female': 52,
        'nopell': 43,
        'pell': 36,
        'sat_lowest_quintile': 30,
        'sat_2nd_quintile': 40,
        'sat_mid_quintile': 41,
        'sat_4th_quintile': 42,
        'sat_highest_quintile': 43,
        'gpa_lowest_quintile': 20,
        'gpa_2nd_quintile': 29,
        'gpa_mid_quintile': 38,
        'gpa_4th_quintile': 50,
        'gpa_highest_quintile': 64
      },
      {
        'name': 'Hampden-Sydney College',
        'grad_rate_4yr': 58,
        'adj_4yr_grad_rate': 68,
        'white': 60,
        'black': 48,
        'otherrace': 53,
        'male': 58,
        'nopell': 59,
        'pell': 56,
        'sat_lowest_quintile': 41,
        'sat_2nd_quintile': 50,
        'sat_mid_quintile': 62,
        'sat_4th_quintile': 64,
        'sat_highest_quintile': 67,
        'gpa_lowest_quintile': 41,
        'gpa_2nd_quintile': 55,
        'gpa_mid_quintile': 64,
        'gpa_4th_quintile': 69,
        'gpa_highest_quintile': 84
      },
      {
        'name': 'Hampton University',
        'grad_rate_4yr': 33,
        'adj_4yr_grad_rate': 47,
        'white': 16,
        'black': 33,
        'hispanic': 16,
        'otherrace': 50,
        'male': 24,
        'female': 39,
        'nopell': 37,
        'pell': 27,
        'sat_lowest_quintile': 29,
        'sat_2nd_quintile': 34,
        'sat_mid_quintile': 38,
        'sat_4th_quintile': 42,
        'sat_highest_quintile': 42,
        'gpa_lowest_quintile': 24,
        'gpa_2nd_quintile': 32,
        'gpa_mid_quintile': 41,
        'gpa_4th_quintile': 50,
        'gpa_highest_quintile': 63
      },
      {
        'name': 'Hollins University',
        'grad_rate_4yr': 55,
        'adj_4yr_grad_rate': 50,
        'white': 56,
        'black': 42,
        'hispanic': 43,
        'otherrace': 56,
        'female': 55,
        'nopell': 61,
        'pell': 46,
        'sat_lowest_quintile': 41,
        'sat_2nd_quintile': 43,
        'sat_mid_quintile': 59,
        'sat_4th_quintile': 61,
        'sat_highest_quintile': 70,
        'gpa_lowest_quintile': 34,
        'gpa_2nd_quintile': 44,
        'gpa_mid_quintile': 55,
        'gpa_4th_quintile': 63,
        'gpa_highest_quintile': 77
      },
      {
        'name': 'James Madison University',
        'grad_rate_4yr': 60,
        'adj_4yr_grad_rate': 51,
        'white': 62,
        'black': 38,
        'hispanic': 53,
        'asian': 55,
        'otherrace': 56,
        'male': 50,
        'female': 67,
        'nopell': 62,
        'pell': 49,
        'sat_lowest_quintile': 42,
        'sat_2nd_quintile': 55,
        'sat_mid_quintile': 61,
        'sat_4th_quintile': 62,
        'sat_highest_quintile': 62,
        'gpa_lowest_quintile': 30,
        'gpa_2nd_quintile': 42,
        'gpa_mid_quintile': 53,
        'gpa_4th_quintile': 62,
        'gpa_highest_quintile': 74
      },
      {
        'name': 'Jefferson College of Health Sciences',
        'grad_rate_4yr': 34,
        'adj_4yr_grad_rate': 40,
        'white': 39,
        'male': 44,
        'female': 31,
        'nopell': 45,
        'pell': 22,
        'sat_lowest_quintile': 20,
        'sat_2nd_quintile': 45,
        'gpa_lowest_quintile': 9,
        'gpa_2nd_quintile': 23,
        'gpa_mid_quintile': 54,
        'gpa_4th_quintile': 42
      },
      {
        'name': 'Liberty University',
        'grad_rate_4yr': 30,
        'adj_4yr_grad_rate': 38,
        'white': 34,
        'black': 11,
        'hispanic': 24,
        'asian': 29,
        'otherrace': 29,
        'male': 25,
        'female': 35,
        'nopell': 34,
        'pell': 21,
        'sat_lowest_quintile': 16,
        'sat_2nd_quintile': 28,
        'sat_mid_quintile': 36,
        'sat_4th_quintile': 44,
        'sat_highest_quintile': 52,
        'gpa_lowest_quintile': 11,
        'gpa_2nd_quintile': 25,
        'gpa_mid_quintile': 35,
        'gpa_4th_quintile': 52,
        'gpa_highest_quintile': 62
      },
      {
        'name': 'Longwood University',
        'grad_rate_4yr': 48,
        'adj_4yr_grad_rate': 51,
        'white': 50,
        'black': 39,
        'hispanic': 49,
        'asian': 41,
        'otherrace': 44,
        'male': 33,
        'female': 56,
        'nopell': 51,
        'pell': 40,
        'sat_lowest_quintile': 44,
        'sat_2nd_quintile': 49,
        'sat_mid_quintile': 49,
        'sat_4th_quintile': 50,
        'sat_highest_quintile': 50,
        'gpa_lowest_quintile': 27,
        'gpa_2nd_quintile': 42,
        'gpa_mid_quintile': 54,
        'gpa_4th_quintile': 66,
        'gpa_highest_quintile': 82
      },
      {
        'name': 'Lynchburg College',
        'grad_rate_4yr': 45,
        'adj_4yr_grad_rate': 54,
        'white': 47,
        'black': 35,
        'hispanic': 36,
        'otherrace': 36,
        'male': 34,
        'female': 53,
        'nopell': 46,
        'pell': 41,
        'sat_lowest_quintile': 36,
        'sat_2nd_quintile': 44,
        'sat_mid_quintile': 50,
        'sat_4th_quintile': 51,
        'sat_highest_quintile': 59,
        'gpa_lowest_quintile': 29,
        'gpa_2nd_quintile': 45,
        'gpa_mid_quintile': 54,
        'gpa_4th_quintile': 63,
        'gpa_highest_quintile': 79
      },
      {
        'name': 'Mary Baldwin College',
        'grad_rate_4yr': 38,
        'adj_4yr_grad_rate': 49,
        'white': 41,
        'black': 37,
        'hispanic': 42,
        'asian': 30,
        'otherrace': 29,
        'female': 38,
        'nopell': 37,
        'pell': 39,
        'sat_lowest_quintile': 35,
        'sat_2nd_quintile': 47,
        'sat_mid_quintile': 43,
        'sat_4th_quintile': 38,
        'gpa_lowest_quintile': 33,
        'gpa_2nd_quintile': 35,
        'gpa_mid_quintile': 46,
        'gpa_4th_quintile': 45,
        'gpa_highest_quintile': 56
      },
      {
        'name': 'Marymount University',
        'grad_rate_4yr': 32,
        'adj_4yr_grad_rate': 42,
        'white': 37,
        'black': 21,
        'hispanic': 36,
        'asian': 35,
        'otherrace': 27,
        'male': 22,
        'female': 36,
        'nopell': 35,
        'pell': 25,
        'sat_lowest_quintile': 23,
        'sat_2nd_quintile': 29,
        'sat_mid_quintile': 41,
        'sat_4th_quintile': 48,
        'sat_highest_quintile': 54,
        'gpa_lowest_quintile': 19,
        'gpa_2nd_quintile': 33,
        'gpa_mid_quintile': 45,
        'gpa_4th_quintile': 56,
        'gpa_highest_quintile': 69
      },
      {
        'name': 'Norfolk State University',
        'grad_rate_4yr': 13,
        'adj_4yr_grad_rate': 37,
        'white': 14,
        'black': 13,
        'hispanic': 9,
        'otherrace': 12,
        'male': 8,
        'female': 16,
        'nopell': 16,
        'pell': 10,
        'sat_lowest_quintile': 11,
        'sat_2nd_quintile': 15,
        'sat_mid_quintile': 24,
        'sat_4th_quintile': 26,
        'gpa_lowest_quintile': 7,
        'gpa_2nd_quintile': 16,
        'gpa_mid_quintile': 29,
        'gpa_4th_quintile': 40,
        'gpa_highest_quintile': 59
      },
      {
        'name': 'Old Dominion University',
        'grad_rate_4yr': 21,
        'adj_4yr_grad_rate': 29,
        'white': 23,
        'black': 16,
        'hispanic': 18,
        'asian': 21,
        'otherrace': 20,
        'male': 14,
        'female': 27,
        'nopell': 22,
        'pell': 17,
        'sat_lowest_quintile': 17,
        'sat_2nd_quintile': 18,
        'sat_mid_quintile': 21,
        'sat_4th_quintile': 27,
        'sat_highest_quintile': 29,
        'gpa_lowest_quintile': 10,
        'gpa_2nd_quintile': 18,
        'gpa_mid_quintile': 23,
        'gpa_4th_quintile': 38,
        'gpa_highest_quintile': 56
      },
      {
        'name': 'Radford University',
        'grad_rate_4yr': 35,
        'adj_4yr_grad_rate': 44,
        'white': 37,
        'black': 29,
        'hispanic': 29,
        'asian': 27,
        'otherrace': 33,
        'male': 27,
        'female': 42,
        'nopell': 37,
        'pell': 30,
        'sat_lowest_quintile': 33,
        'sat_2nd_quintile': 33,
        'sat_mid_quintile': 38,
        'sat_4th_quintile': 41,
        'sat_highest_quintile': 41,
        'gpa_lowest_quintile': 23,
        'gpa_2nd_quintile': 36,
        'gpa_mid_quintile': 45,
        'gpa_4th_quintile': 57,
        'gpa_highest_quintile': 72
      },
      {
        'name': 'Randolph College',
        'grad_rate_4yr': 58,
        'adj_4yr_grad_rate': 59,
        'white': 60,
        'black': 48,
        'hispanic': 56,
        'asian': 62,
        'otherrace': 59,
        'male': 52,
        'female': 62,
        'nopell': 60,
        'pell': 52,
        'sat_lowest_quintile': 50,
        'sat_2nd_quintile': 50,
        'sat_mid_quintile': 58,
        'sat_4th_quintile': 67,
        'sat_highest_quintile': 75,
        'gpa_lowest_quintile': 37,
        'gpa_2nd_quintile': 50,
        'gpa_mid_quintile': 59,
        'gpa_4th_quintile': 70,
        'gpa_highest_quintile': 82
      },
      {
        'name': 'Regent University',
        'grad_rate_4yr': 42,
        'adj_4yr_grad_rate': 43,
        'white': 48,
        'black': 21,
        'male': 34,
        'female': 47,
        'nopell': 50,
        'pell': 26,
        'sat_lowest_quintile': 25,
        'sat_2nd_quintile': 38,
        'sat_mid_quintile': 47,
        'sat_4th_quintile': 56,
        'gpa_lowest_quintile': 9,
        'gpa_2nd_quintile': 40,
        'gpa_mid_quintile': 48,
        'gpa_4th_quintile': 41,
        'gpa_highest_quintile': 73
      },
      {
        'name': 'Roanoke College',
        'grad_rate_4yr': 56,
        'adj_4yr_grad_rate': 57,
        'white': 57,
        'black': 49,
        'hispanic': 46,
        'otherrace': 56,
        'male': 44,
        'female': 64,
        'nopell': 58,
        'pell': 50,
        'sat_lowest_quintile': 40,
        'sat_2nd_quintile': 54,
        'sat_mid_quintile': 57,
        'sat_4th_quintile': 60,
        'sat_highest_quintile': 66,
        'gpa_lowest_quintile': 34,
        'gpa_2nd_quintile': 50,
        'gpa_mid_quintile': 56,
        'gpa_4th_quintile': 71,
        'gpa_highest_quintile': 82
      },
      {
        'name': 'Shenandoah University',
        'grad_rate_4yr': 42,
        'adj_4yr_grad_rate': 48,
        'white': 46,
        'black': 27,
        'hispanic': 34,
        'asian': 40,
        'otherrace': 32,
        'male': 31,
        'female': 52,
        'nopell': 46,
        'pell': 31,
        'sat_lowest_quintile': 28,
        'sat_2nd_quintile': 43,
        'sat_mid_quintile': 50,
        'sat_4th_quintile': 57,
        'sat_highest_quintile': 52,
        'gpa_lowest_quintile': 19,
        'gpa_2nd_quintile': 37,
        'gpa_mid_quintile': 55,
        'gpa_4th_quintile': 60,
        'gpa_highest_quintile': 73
      },
      {
        'name': 'Southern Virginia University',
        'grad_rate_4yr': 12,
        'adj_4yr_grad_rate': 22,
        'white': 13,
        'male': 4,
        'female': 21,
        'nopell': 15,
        'pell': 9,
        'sat_lowest_quintile': 12,
        'sat_2nd_quintile': 13,
        'sat_mid_quintile': 11,
        'sat_4th_quintile': 13,
        'sat_highest_quintile': 15,
        'gpa_lowest_quintile': 5,
        'gpa_2nd_quintile': 9,
        'gpa_mid_quintile': 16,
        'gpa_4th_quintile': 27,
        'gpa_highest_quintile': 21
      },
      {
        'name': 'Sweet Briar College',
        'grad_rate_4yr': 51,
        'adj_4yr_grad_rate': 51,
        'white': 54,
        'otherrace': 50,
        'female': 51,
        'nopell': 53,
        'pell': 46,
        'sat_lowest_quintile': 31,
        'sat_2nd_quintile': 55,
        'sat_mid_quintile': 52,
        'sat_4th_quintile': 64,
        'sat_highest_quintile': 62,
        'gpa_lowest_quintile': 33,
        'gpa_2nd_quintile': 44,
        'gpa_mid_quintile': 54,
        'gpa_4th_quintile': 64,
        'gpa_highest_quintile': 72
      },
      {
        'name': 'University of Mary Washington',
        'grad_rate_4yr': 61,
        'adj_4yr_grad_rate': 57,
        'white': 63,
        'black': 49,
        'hispanic': 52,
        'asian': 62,
        'otherrace': 60,
        'male': 48,
        'female': 68,
        'nopell': 62,
        'pell': 54,
        'sat_lowest_quintile': 45,
        'sat_2nd_quintile': 57,
        'sat_mid_quintile': 61,
        'sat_4th_quintile': 63,
        'sat_highest_quintile': 66,
        'gpa_lowest_quintile': 36,
        'gpa_2nd_quintile': 50,
        'gpa_mid_quintile': 59,
        'gpa_4th_quintile': 73,
        'gpa_highest_quintile': 79
      },
      {
        'name': 'University of Richmond',
        'grad_rate_4yr': 81,
        'adj_4yr_grad_rate': 71,
        'white': 82,
        'black': 72,
        'hispanic': 78,
        'asian': 78,
        'otherrace': 82,
        'male': 76,
        'female': 85,
        'nopell': 82,
        'pell': 79,
        'sat_2nd_quintile': 67,
        'sat_mid_quintile': 73,
        'sat_4th_quintile': 76,
        'sat_highest_quintile': 86,
        'gpa_lowest_quintile': 71,
        'gpa_2nd_quintile': 64,
        'gpa_mid_quintile': 79,
        'gpa_4th_quintile': 83,
        'gpa_highest_quintile': 86
      },
      {
        'name': 'University of Virginia',
        'grad_rate_4yr': 88,
        'adj_4yr_grad_rate': 67,
        'white': 88,
        'black': 80,
        'hispanic': 88,
        'asian': 89,
        'otherrace': 89,
        'male': 87,
        'female': 89,
        'nopell': 89,
        'pell': 82,
        'sat_lowest_quintile': 74,
        'sat_2nd_quintile': 78,
        'sat_mid_quintile': 81,
        'sat_4th_quintile': 85,
        'sat_highest_quintile': 89,
        'gpa_lowest_quintile': 54,
        'gpa_2nd_quintile': 73,
        'gpa_mid_quintile': 81,
        'gpa_4th_quintile': 85,
        'gpa_highest_quintile': 89
      },
      {
        'name': 'University of Virginia\'s College at Wise',
        'grad_rate_4yr': 24,
        'adj_4yr_grad_rate': 34,
        'white': 25,
        'black': 13,
        'otherrace': 27,
        'male': 19,
        'female': 30,
        'nopell': 29,
        'pell': 19,
        'sat_lowest_quintile': 17,
        'sat_2nd_quintile': 25,
        'sat_mid_quintile': 37,
        'sat_4th_quintile': 39,
        'gpa_lowest_quintile': 10,
        'gpa_2nd_quintile': 16,
        'gpa_mid_quintile': 28,
        'gpa_4th_quintile': 36,
        'gpa_highest_quintile': 65
      },
      {
        'name': 'Virginia Commonwealth University',
        'grad_rate_4yr': 34,
        'adj_4yr_grad_rate': 35,
        'white': 35,
        'black': 31,
        'hispanic': 33,
        'asian': 35,
        'otherrace': 32,
        'male': 28,
        'female': 38,
        'nopell': 35,
        'pell': 30,
        'sat_lowest_quintile': 26,
        'sat_2nd_quintile': 30,
        'sat_mid_quintile': 34,
        'sat_4th_quintile': 36,
        'sat_highest_quintile': 44,
        'gpa_lowest_quintile': 17,
        'gpa_2nd_quintile': 26,
        'gpa_mid_quintile': 34,
        'gpa_4th_quintile': 45,
        'gpa_highest_quintile': 59
      },
      {
        'name': 'Virginia Military Institute',
        'grad_rate_4yr': 64,
        'adj_4yr_grad_rate': 67,
        'white': 66,
        'black': 33,
        'hispanic': 56,
        'asian': 69,
        'male': 63,
        'female': 67,
        'nopell': 65,
        'pell': 56,
        'sat_lowest_quintile': 27,
        'sat_2nd_quintile': 52,
        'sat_mid_quintile': 65,
        'sat_4th_quintile': 72,
        'sat_highest_quintile': 67,
        'gpa_lowest_quintile': 34,
        'gpa_2nd_quintile': 57,
        'gpa_mid_quintile': 73,
        'gpa_4th_quintile': 73,
        'gpa_highest_quintile': 79
      },
      {
        'name': 'Virginia State University',
        'grad_rate_4yr': 24,
        'adj_4yr_grad_rate': 49,
        'white': 16,
        'black': 25,
        'hispanic': 22,
        'otherrace': 21,
        'male': 16,
        'female': 29,
        'nopell': 27,
        'pell': 22,
        'sat_lowest_quintile': 23,
        'sat_2nd_quintile': 26,
        'sat_mid_quintile': 37,
        'sat_4th_quintile': 33,
        'gpa_lowest_quintile': 18,
        'gpa_2nd_quintile': 34,
        'gpa_mid_quintile': 38,
        'gpa_4th_quintile': 52,
        'gpa_highest_quintile': 69
      },
      {
        'name': 'Virginia Tech',
        'grad_rate_4yr': 65,
        'adj_4yr_grad_rate': 52,
        'white': 66,
        'black': 44,
        'hispanic': 58,
        'asian': 65,
        'otherrace': 60,
        'male': 55,
        'female': 76,
        'nopell': 66,
        'pell': 57,
        'sat_lowest_quintile': 50,
        'sat_2nd_quintile': 61,
        'sat_mid_quintile': 65,
        'sat_4th_quintile': 67,
        'sat_highest_quintile': 63,
        'gpa_lowest_quintile': 29,
        'gpa_2nd_quintile': 47,
        'gpa_mid_quintile': 54,
        'gpa_4th_quintile': 64,
        'gpa_highest_quintile': 70
      },
      {
        'name': 'Virginia Union University',
        'grad_rate_4yr': 19,
        'adj_4yr_grad_rate': 50,
        'black': 19,
        'male': 12,
        'female': 23,
        'nopell': 21,
        'pell': 17,
        'sat_lowest_quintile': 18,
        'sat_2nd_quintile': 25,
        'gpa_lowest_quintile': 15,
        'gpa_2nd_quintile': 33,
        'gpa_mid_quintile': 47
      },
      {
        'name': 'Virginia Wesleyan College',
        'grad_rate_4yr': 44,
        'adj_4yr_grad_rate': 56,
        'white': 48,
        'black': 38,
        'hispanic': 45,
        'otherrace': 43,
        'male': 37,
        'female': 49,
        'nopell': 49,
        'pell': 36,
        'sat_lowest_quintile': 34,
        'sat_2nd_quintile': 45,
        'sat_mid_quintile': 51,
        'sat_4th_quintile': 63,
        'sat_highest_quintile': 57,
        'gpa_lowest_quintile': 30,
        'gpa_2nd_quintile': 51,
        'gpa_mid_quintile': 47,
        'gpa_4th_quintile': 68,
        'gpa_highest_quintile': 78
      },
      {
        'name': 'Washington and Lee University',
        'grad_rate_4yr': 98,
        'adj_4yr_grad_rate': 82,
        'white': 98,
        'male': 97,
        'nopell': 98,
        'sat_highest_quintile': 98
      },
      {
        'name': 'State Average',
        'white': 53,
        'black': 29,
        'hispanic': 45,
        'asian': 52,
        'otherrace': 44,
        'male': 40,
        'female': 54,
        'nopell': 53,
        'pell': 34,
        'sat_lowest_quintile': 24,
        'sat_2nd_quintile': 37,
        'sat_mid_quintile': 48,
        'sat_4th_quintile': 57,
        'sat_highest_quintile': 69,
        'gpa_lowest_quintile': 19,
        'gpa_2nd_quintile': 33,
        'gpa_mid_quintile': 46,
        'gpa_4th_quintile': 61,
        'gpa_highest_quintile': 77
      }
    ]
  },
  '2yr': {
    '4yr': [
      {
        'name': 'Blue Ridge Community College',
        'grad_rate_4yr': 30,
        'adj_4yr_grad_rate': 26,
        'white': 33,
        'black': 11,
        'hispanic': 19,
        'otherrace': 20,
        'male': 26,
        'female': 33,
        'nopell': 33,
        'pell': 25,
        'testscore_lowest_quintile': 9,
        'testscore_2nd_quintile': 18,
        'testscore_mid_quintile': 30,
        'testscore_4th_quintile': 34,
        'testscore_highest_quintile': 40,
        'fulltime': 35,
        'parttime': 13
      },
      {
        'name': 'Central Virginia Community College',
        'grad_rate_4yr': 23,
        'adj_4yr_grad_rate': 21,
        'white': 26,
        'black': 12,
        'hispanic': 13,
        'otherrace': 22,
        'male': 21,
        'female': 25,
        'nopell': 26,
        'pell': 20,
        'testscore_lowest_quintile': 6,
        'testscore_2nd_quintile': 13,
        'testscore_mid_quintile': 22,
        'testscore_4th_quintile': 26,
        'testscore_highest_quintile': 36,
        'fulltime': 28,
        'parttime': 11
      },
      {
        'name': 'Dabney S. Lancaster Community College',
        'grad_rate_4yr': 26,
        'adj_4yr_grad_rate': 24,
        'white': 28,
        'male': 29,
        'female': 23,
        'nopell': 33,
        'pell': 21,
        'testscore_lowest_quintile': 6,
        'testscore_2nd_quintile': 10,
        'testscore_mid_quintile': 30,
        'testscore_4th_quintile': 36,
        'testscore_highest_quintile': 40,
        'fulltime': 30,
        'parttime': 9
      },
      {
        'name': 'Danville Community College',
        'grad_rate_4yr': 24,
        'adj_4yr_grad_rate': 25,
        'white': 32,
        'black': 14,
        'male': 23,
        'female': 25,
        'nopell': 32,
        'pell': 20,
        'testscore_lowest_quintile': 6,
        'testscore_2nd_quintile': 16,
        'testscore_mid_quintile': 22,
        'testscore_4th_quintile': 36,
        'testscore_highest_quintile': 41,
        'fulltime': 27,
        'parttime': 13
      },
      {
        'name': 'Eastern Shore Community College',
        'grad_rate_4yr': 21,
        'adj_4yr_grad_rate': 22,
        'white': 26,
        'black': 17,
        'male': 20,
        'female': 21,
        'nopell': 34,
        'pell': 15,
        'testscore_lowest_quintile': 11,
        'testscore_2nd_quintile': 14,
        'testscore_mid_quintile': 17,
        'testscore_4th_quintile': 24,
        'testscore_highest_quintile': 40,
        'fulltime': 26,
        'parttime': 9
      },
      {
        'name': 'Germanna Community College',
        'grad_rate_4yr': 24,
        'adj_4yr_grad_rate': 24,
        'white': 26,
        'black': 15,
        'hispanic': 23,
        'asian': 41,
        'otherrace': 20,
        'male': 21,
        'female': 28,
        'nopell': 26,
        'pell': 19,
        'testscore_lowest_quintile': 16,
        'testscore_2nd_quintile': 21,
        'testscore_mid_quintile': 23,
        'testscore_4th_quintile': 24,
        'testscore_highest_quintile': 35,
        'fulltime': 30,
        'parttime': 12
      },
      {
        'name': 'J Sargeant Reynolds Community College',
        'grad_rate_4yr': 13,
        'adj_4yr_grad_rate': 16,
        'white': 16,
        'black': 7,
        'hispanic': 11,
        'asian': 19,
        'otherrace': 12,
        'male': 11,
        'female': 16,
        'nopell': 16,
        'pell': 10,
        'testscore_lowest_quintile': 5,
        'testscore_2nd_quintile': 11,
        'testscore_mid_quintile': 13,
        'testscore_4th_quintile': 17,
        'testscore_highest_quintile': 22,
        'fulltime': 17,
        'parttime': 7
      },
      {
        'name': 'John Tyler Community College',
        'grad_rate_4yr': 16,
        'adj_4yr_grad_rate': 19,
        'white': 20,
        'black': 7,
        'hispanic': 21,
        'asian': 20,
        'otherrace': 16,
        'male': 14,
        'female': 18,
        'nopell': 19,
        'pell': 13,
        'testscore_lowest_quintile': 8,
        'testscore_2nd_quintile': 12,
        'testscore_mid_quintile': 16,
        'testscore_4th_quintile': 25,
        'testscore_highest_quintile': 27,
        'fulltime': 20,
        'parttime': 7
      },
      {
        'name': 'Lord Fairfax Community College',
        'grad_rate_4yr': 27,
        'adj_4yr_grad_rate': 26,
        'white': 29,
        'black': 9,
        'hispanic': 21,
        'otherrace': 19,
        'male': 22,
        'female': 31,
        'nopell': 30,
        'pell': 21,
        'testscore_lowest_quintile': 7,
        'testscore_2nd_quintile': 19,
        'testscore_mid_quintile': 29,
        'testscore_4th_quintile': 28,
        'testscore_highest_quintile': 39,
        'fulltime': 35,
        'parttime': 12
      },
      {
        'name': 'Mountain Empire Community College',
        'grad_rate_4yr': 26,
        'adj_4yr_grad_rate': 23,
        'white': 27,
        'male': 26,
        'female': 26,
        'nopell': 37,
        'pell': 21,
        'testscore_lowest_quintile': 9,
        'testscore_2nd_quintile': 14,
        'testscore_mid_quintile': 23,
        'testscore_4th_quintile': 27,
        'testscore_highest_quintile': 42,
        'fulltime': 30,
        'parttime': 9
      },
      {
        'name': 'New River Community College',
        'grad_rate_4yr': 23,
        'adj_4yr_grad_rate': 22,
        'white': 24,
        'black': 11,
        'otherrace': 11,
        'male': 23,
        'female': 22,
        'nopell': 27,
        'pell': 18,
        'testscore_lowest_quintile': 9,
        'testscore_2nd_quintile': 20,
        'testscore_mid_quintile': 22,
        'testscore_4th_quintile': 29,
        'testscore_highest_quintile': 36,
        'fulltime': 25,
        'parttime': 14
      },
      {
        'name': 'Northern Virginia Community College',
        'grad_rate_4yr': 24,
        'adj_4yr_grad_rate': 24,
        'white': 24,
        'black': 16,
        'hispanic': 22,
        'asian': 36,
        'otherrace': 26,
        'male': 20,
        'female': 28,
        'nopell': 23,
        'pell': 28,
        'testscore_lowest_quintile': 14,
        'testscore_2nd_quintile': 21,
        'testscore_mid_quintile': 26,
        'testscore_4th_quintile': 29,
        'testscore_highest_quintile': 32,
        'fulltime': 30,
        'parttime': 12
      },
      {
        'name': 'Patrick Henry Community College',
        'grad_rate_4yr': 26,
        'adj_4yr_grad_rate': 26,
        'white': 32,
        'black': 14,
        'male': 26,
        'female': 27,
        'nopell': 31,
        'pell': 24,
        'testscore_lowest_quintile': 12,
        'testscore_2nd_quintile': 16,
        'testscore_mid_quintile': 29,
        'testscore_4th_quintile': 34,
        'testscore_highest_quintile': 41,
        'fulltime': 29,
        'parttime': 11
      },
      {
        'name': 'Paul D Camp Community College',
        'grad_rate_4yr': 23,
        'adj_4yr_grad_rate': 26,
        'white': 35,
        'black': 8,
        'male': 27,
        'female': 20,
        'nopell': 30,
        'pell': 19,
        'testscore_lowest_quintile': 7,
        'testscore_2nd_quintile': 13,
        'testscore_mid_quintile': 29,
        'testscore_4th_quintile': 43,
        'testscore_highest_quintile': 41,
        'fulltime': 27,
        'parttime': 10
      },
      {
        'name': 'Piedmont Virginia Community College',
        'grad_rate_4yr': 18,
        'adj_4yr_grad_rate': 20,
        'white': 21,
        'black': 5,
        'hispanic': 17,
        'otherrace': 20,
        'male': 18,
        'female': 18,
        'nopell': 22,
        'pell': 13,
        'testscore_lowest_quintile': 4,
        'testscore_2nd_quintile': 10,
        'testscore_mid_quintile': 14,
        'testscore_4th_quintile': 21,
        'testscore_highest_quintile': 36,
        'fulltime': 27,
        'parttime': 8
      },
      {
        'name': 'Rappahannock Community College',
        'grad_rate_4yr': 24,
        'adj_4yr_grad_rate': 25,
        'white': 27,
        'black': 14,
        'hispanic': 28,
        'otherrace': 25,
        'male': 21,
        'female': 27,
        'nopell': 28,
        'pell': 20,
        'testscore_lowest_quintile': 9,
        'testscore_2nd_quintile': 15,
        'testscore_mid_quintile': 26,
        'testscore_4th_quintile': 27,
        'testscore_highest_quintile': 44,
        'fulltime': 30,
        'parttime': 9
      },
      {
        'name': 'Southside Virginia Community College',
        'grad_rate_4yr': 22,
        'adj_4yr_grad_rate': 25,
        'white': 26,
        'black': 19,
        'male': 22,
        'female': 23,
        'nopell': 31,
        'pell': 20,
        'testscore_lowest_quintile': 12,
        'testscore_2nd_quintile': 19,
        'testscore_mid_quintile': 25,
        'testscore_4th_quintile': 21,
        'testscore_highest_quintile': 41,
        'fulltime': 26,
        'parttime': 9
      },
      {
        'name': 'Southwest Virginia Community College',
        'grad_rate_4yr': 33,
        'adj_4yr_grad_rate': 28,
        'white': 34,
        'male': 29,
        'female': 37,
        'nopell': 39,
        'pell': 29,
        'testscore_lowest_quintile': 15,
        'testscore_2nd_quintile': 16,
        'testscore_mid_quintile': 33,
        'testscore_4th_quintile': 32,
        'testscore_highest_quintile': 46,
        'fulltime': 35,
        'parttime': 15
      },
      {
        'name': 'Thomas Nelson Community College',
        'grad_rate_4yr': 16,
        'adj_4yr_grad_rate': 18,
        'white': 22,
        'black': 5,
        'hispanic': 11,
        'asian': 29,
        'otherrace': 15,
        'male': 13,
        'female': 18,
        'nopell': 20,
        'pell': 9,
        'testscore_lowest_quintile': 5,
        'testscore_2nd_quintile': 11,
        'testscore_mid_quintile': 16,
        'testscore_4th_quintile': 22,
        'testscore_highest_quintile': 25,
        'fulltime': 20,
        'parttime': 7
      },
      {
        'name': 'Tidewater Community College',
        'grad_rate_4yr': 16,
        'adj_4yr_grad_rate': 18,
        'white': 22,
        'black': 8,
        'hispanic': 16,
        'asian': 25,
        'otherrace': 18,
        'male': 14,
        'female': 18,
        'nopell': 21,
        'pell': 11,
        'testscore_lowest_quintile': 6,
        'testscore_2nd_quintile': 11,
        'testscore_mid_quintile': 18,
        'testscore_4th_quintile': 21,
        'testscore_highest_quintile': 29,
        'fulltime': 20,
        'parttime': 7
      },
      {
        'name': 'Virginia Highlands Community College',
        'grad_rate_4yr': 26,
        'adj_4yr_grad_rate': 22,
        'white': 27,
        'male': 25,
        'female': 27,
        'nopell': 31,
        'pell': 21,
        'testscore_lowest_quintile': 8,
        'testscore_2nd_quintile': 18,
        'testscore_mid_quintile': 22,
        'testscore_4th_quintile': 26,
        'testscore_highest_quintile': 41,
        'fulltime': 28,
        'parttime': 5
      },
      {
        'name': 'Virginia Western Community College',
        'grad_rate_4yr': 24,
        'adj_4yr_grad_rate': 22,
        'white': 26,
        'black': 10,
        'hispanic': 26,
        'asian': 31,
        'otherrace': 19,
        'male': 22,
        'female': 26,
        'nopell': 27,
        'pell': 20,
        'testscore_lowest_quintile': 7,
        'testscore_2nd_quintile': 13,
        'testscore_mid_quintile': 21,
        'testscore_4th_quintile': 28,
        'testscore_highest_quintile': 38,
        'fulltime': 28,
        'parttime': 10
      },
      {
        'name': 'Wytheville Community College',
        'grad_rate_4yr': 29,
        'adj_4yr_grad_rate': 27,
        'white': 30,
        'black': 10,
        'male': 27,
        'female': 31,
        'nopell': 40,
        'pell': 23,
        'testscore_lowest_quintile': 15,
        'testscore_2nd_quintile': 24,
        'testscore_mid_quintile': 31,
        'testscore_4th_quintile': 36,
        'testscore_highest_quintile': 39,
        'fulltime': 31,
        'parttime': 17
      },
      {
        'name': 'State Average',
        'white': 25,
        'black': 11,
        'hispanic': 21,
        'asian': 33,
        'otherrace': 21,
        'male': 19,
        'female': 24,
        'nopell': 24,
        'pell': 19,
        'testscore_lowest_quintile': 10,
        'testscore_2nd_quintile': 16,
        'testscore_mid_quintile': 22,
        'testscore_4th_quintile': 26,
        'testscore_highest_quintile': 34,
        'fulltime': 26,
        'parttime': 10
      }
    ],
    '6yr': [
      {
        'name': 'Blue Ridge Community College',
        'grad_rate_6yr': 37,
        'adj_6yr_grad_rate': 33,
        'white': 40,
        'black': 21,
        'hispanic': 26,
        'otherrace': 30,
        'male': 34,
        'female': 40,
        'nopell': 41,
        'pell': 32,
        'testscore_lowest_quintile': 13,
        'testscore_2nd_quintile': 25,
        'testscore_mid_quintile': 36,
        'testscore_4th_quintile': 42,
        'testscore_highest_quintile': 50,
        'fulltime': 43,
        'parttime': 20
      },
      {
        'name': 'Central Virginia Community College',
        'grad_rate_6yr': 31,
        'adj_6yr_grad_rate': 29,
        'white': 35,
        'black': 15,
        'hispanic': 13,
        'otherrace': 30,
        'male': 30,
        'female': 32,
        'nopell': 36,
        'pell': 25,
        'testscore_lowest_quintile': 10,
        'testscore_2nd_quintile': 20,
        'testscore_mid_quintile': 29,
        'testscore_4th_quintile': 35,
        'testscore_highest_quintile': 47,
        'fulltime': 36,
        'parttime': 19
      },
      {
        'name': 'Dabney S. Lancaster Community College',
        'grad_rate_6yr': 34,
        'adj_6yr_grad_rate': 31,
        'white': 35,
        'male': 37,
        'female': 30,
        'nopell': 40,
        'pell': 28,
        'testscore_lowest_quintile': 13,
        'testscore_2nd_quintile': 14,
        'testscore_mid_quintile': 36,
        'testscore_4th_quintile': 44,
        'testscore_highest_quintile': 50,
        'fulltime': 38,
        'parttime': 13
      },
      {
        'name': 'Danville Community College',
        'grad_rate_6yr': 32,
        'adj_6yr_grad_rate': 34,
        'white': 42,
        'black': 21,
        'male': 30,
        'female': 34,
        'nopell': 44,
        'pell': 26,
        'testscore_lowest_quintile': 12,
        'testscore_2nd_quintile': 25,
        'testscore_mid_quintile': 28,
        'testscore_4th_quintile': 44,
        'testscore_highest_quintile': 51,
        'fulltime': 35,
        'parttime': 18
      },
      {
        'name': 'Eastern Shore Community College',
        'grad_rate_6yr': 28,
        'adj_6yr_grad_rate': 30,
        'white': 33,
        'black': 22,
        'male': 27,
        'female': 29,
        'nopell': 45,
        'pell': 21,
        'testscore_lowest_quintile': 16,
        'testscore_2nd_quintile': 21,
        'testscore_mid_quintile': 22,
        'testscore_4th_quintile': 36,
        'testscore_highest_quintile': 48,
        'fulltime': 33,
        'parttime': 17
      },
      {
        'name': 'Germanna Community College',
        'grad_rate_6yr': 34,
        'adj_6yr_grad_rate': 33,
        'white': 36,
        'black': 25,
        'hispanic': 32,
        'asian': 49,
        'otherrace': 30,
        'male': 30,
        'female': 39,
        'nopell': 36,
        'pell': 29,
        'testscore_lowest_quintile': 24,
        'testscore_2nd_quintile': 31,
        'testscore_mid_quintile': 33,
        'testscore_4th_quintile': 37,
        'testscore_highest_quintile': 45,
        'fulltime': 41,
        'parttime': 19
      },
      {
        'name': 'J Sargeant Reynolds Community College',
        'grad_rate_6yr': 23,
        'adj_6yr_grad_rate': 27,
        'white': 28,
        'black': 13,
        'hispanic': 24,
        'asian': 28,
        'otherrace': 23,
        'male': 21,
        'female': 26,
        'nopell': 27,
        'pell': 18,
        'testscore_lowest_quintile': 12,
        'testscore_2nd_quintile': 19,
        'testscore_mid_quintile': 24,
        'testscore_4th_quintile': 28,
        'testscore_highest_quintile': 36,
        'fulltime': 29,
        'parttime': 14
      },
      {
        'name': 'John Tyler Community College',
        'grad_rate_6yr': 25,
        'adj_6yr_grad_rate': 28,
        'white': 30,
        'black': 13,
        'hispanic': 28,
        'asian': 37,
        'otherrace': 24,
        'male': 23,
        'female': 28,
        'nopell': 28,
        'pell': 20,
        'testscore_lowest_quintile': 14,
        'testscore_2nd_quintile': 21,
        'testscore_mid_quintile': 27,
        'testscore_4th_quintile': 35,
        'testscore_highest_quintile': 37,
        'fulltime': 30,
        'parttime': 13
      },
      {
        'name': 'Lord Fairfax Community College',
        'grad_rate_6yr': 35,
        'adj_6yr_grad_rate': 34,
        'white': 37,
        'black': 15,
        'hispanic': 31,
        'otherrace': 31,
        'male': 30,
        'female': 40,
        'nopell': 39,
        'pell': 28,
        'testscore_lowest_quintile': 13,
        'testscore_2nd_quintile': 27,
        'testscore_mid_quintile': 37,
        'testscore_4th_quintile': 38,
        'testscore_highest_quintile': 49,
        'fulltime': 45,
        'parttime': 18
      },
      {
        'name': 'Mountain Empire Community College',
        'grad_rate_6yr': 30,
        'adj_6yr_grad_rate': 27,
        'white': 31,
        'male': 30,
        'female': 31,
        'nopell': 41,
        'pell': 25,
        'testscore_lowest_quintile': 10,
        'testscore_2nd_quintile': 19,
        'testscore_mid_quintile': 27,
        'testscore_4th_quintile': 32,
        'testscore_highest_quintile': 47,
        'fulltime': 34,
        'parttime': 12
      },
      {
        'name': 'New River Community College',
        'grad_rate_6yr': 31,
        'adj_6yr_grad_rate': 31,
        'white': 33,
        'black': 16,
        'otherrace': 27,
        'male': 31,
        'female': 31,
        'nopell': 36,
        'pell': 27,
        'testscore_lowest_quintile': 17,
        'testscore_2nd_quintile': 28,
        'testscore_mid_quintile': 32,
        'testscore_4th_quintile': 40,
        'testscore_highest_quintile': 44,
        'fulltime': 34,
        'parttime': 21
      },
      {
        'name': 'Northern Virginia Community College',
        'grad_rate_6yr': 36,
        'adj_6yr_grad_rate': 35,
        'white': 37,
        'black': 25,
        'hispanic': 34,
        'asian': 51,
        'otherrace': 38,
        'male': 32,
        'female': 42,
        'nopell': 35,
        'pell': 40,
        'testscore_lowest_quintile': 24,
        'testscore_2nd_quintile': 33,
        'testscore_mid_quintile': 39,
        'testscore_4th_quintile': 42,
        'testscore_highest_quintile': 46,
        'fulltime': 44,
        'parttime': 21
      },
      {
        'name': 'Patrick Henry Community College',
        'grad_rate_6yr': 33,
        'adj_6yr_grad_rate': 33,
        'white': 39,
        'black': 21,
        'male': 32,
        'female': 33,
        'nopell': 38,
        'pell': 30,
        'testscore_lowest_quintile': 18,
        'testscore_2nd_quintile': 22,
        'testscore_mid_quintile': 36,
        'testscore_4th_quintile': 42,
        'testscore_highest_quintile': 46,
        'fulltime': 35,
        'parttime': 18
      },
      {
        'name': 'Paul D Camp Community College',
        'grad_rate_6yr': 29,
        'adj_6yr_grad_rate': 32,
        'white': 44,
        'black': 10,
        'male': 32,
        'female': 26,
        'nopell': 39,
        'pell': 23,
        'testscore_lowest_quintile': 11,
        'testscore_2nd_quintile': 20,
        'testscore_mid_quintile': 37,
        'testscore_4th_quintile': 50,
        'testscore_highest_quintile': 44,
        'fulltime': 34,
        'parttime': 13
      },
      {
        'name': 'Piedmont Virginia Community College',
        'grad_rate_6yr': 25,
        'adj_6yr_grad_rate': 27,
        'white': 29,
        'black': 9,
        'hispanic': 24,
        'otherrace': 26,
        'male': 24,
        'female': 26,
        'nopell': 31,
        'pell': 18,
        'testscore_lowest_quintile': 6,
        'testscore_2nd_quintile': 16,
        'testscore_mid_quintile': 21,
        'testscore_4th_quintile': 31,
        'testscore_highest_quintile': 44,
        'fulltime': 34,
        'parttime': 14
      },
      {
        'name': 'Rappahannock Community College',
        'grad_rate_6yr': 31,
        'adj_6yr_grad_rate': 32,
        'white': 36,
        'black': 17,
        'hispanic': 31,
        'otherrace': 30,
        'male': 28,
        'female': 34,
        'nopell': 36,
        'pell': 26,
        'testscore_lowest_quintile': 13,
        'testscore_2nd_quintile': 21,
        'testscore_mid_quintile': 34,
        'testscore_4th_quintile': 37,
        'testscore_highest_quintile': 49,
        'fulltime': 37,
        'parttime': 15
      },
      {
        'name': 'Southside Virginia Community College',
        'grad_rate_6yr': 28,
        'adj_6yr_grad_rate': 32,
        'white': 33,
        'black': 23,
        'male': 26,
        'female': 30,
        'nopell': 36,
        'pell': 25,
        'testscore_lowest_quintile': 16,
        'testscore_2nd_quintile': 23,
        'testscore_mid_quintile': 33,
        'testscore_4th_quintile': 23,
        'testscore_highest_quintile': 48,
        'fulltime': 32,
        'parttime': 14
      },
      {
        'name': 'Southwest Virginia Community College',
        'grad_rate_6yr': 39,
        'adj_6yr_grad_rate': 33,
        'white': 39,
        'male': 35,
        'female': 42,
        'nopell': 45,
        'pell': 35,
        'testscore_lowest_quintile': 20,
        'testscore_2nd_quintile': 19,
        'testscore_mid_quintile': 38,
        'testscore_4th_quintile': 36,
        'testscore_highest_quintile': 55,
        'fulltime': 41,
        'parttime': 19
      },
      {
        'name': 'Thomas Nelson Community College',
        'grad_rate_6yr': 25,
        'adj_6yr_grad_rate': 27,
        'white': 33,
        'black': 12,
        'hispanic': 20,
        'asian': 42,
        'otherrace': 22,
        'male': 22,
        'female': 27,
        'nopell': 32,
        'pell': 14,
        'testscore_lowest_quintile': 9,
        'testscore_2nd_quintile': 18,
        'testscore_mid_quintile': 26,
        'testscore_4th_quintile': 34,
        'testscore_highest_quintile': 37,
        'fulltime': 30,
        'parttime': 14
      },
      {
        'name': 'Tidewater Community College',
        'grad_rate_6yr': 26,
        'adj_6yr_grad_rate': 27,
        'white': 33,
        'black': 15,
        'hispanic': 26,
        'asian': 35,
        'otherrace': 26,
        'male': 23,
        'female': 27,
        'nopell': 32,
        'pell': 18,
        'testscore_lowest_quintile': 13,
        'testscore_2nd_quintile': 18,
        'testscore_mid_quintile': 28,
        'testscore_4th_quintile': 32,
        'testscore_highest_quintile': 40,
        'fulltime': 30,
        'parttime': 15
      },
      {
        'name': 'Virginia Highlands Community College',
        'grad_rate_6yr': 32,
        'adj_6yr_grad_rate': 28,
        'white': 33,
        'male': 30,
        'female': 34,
        'nopell': 38,
        'pell': 27,
        'testscore_lowest_quintile': 18,
        'testscore_2nd_quintile': 25,
        'testscore_mid_quintile': 28,
        'testscore_4th_quintile': 31,
        'testscore_highest_quintile': 48,
        'fulltime': 34,
        'parttime': 11
      },
      {
        'name': 'Virginia Western Community College',
        'grad_rate_6yr': 34,
        'adj_6yr_grad_rate': 31,
        'white': 37,
        'black': 15,
        'hispanic': 33,
        'asian': 47,
        'otherrace': 24,
        'male': 32,
        'female': 36,
        'nopell': 38,
        'pell': 28,
        'testscore_lowest_quintile': 13,
        'testscore_2nd_quintile': 23,
        'testscore_mid_quintile': 33,
        'testscore_4th_quintile': 41,
        'testscore_highest_quintile': 47,
        'fulltime': 39,
        'parttime': 16
      },
      {
        'name': 'Wytheville Community College',
        'grad_rate_6yr': 36,
        'adj_6yr_grad_rate': 35,
        'white': 38,
        'black': 16,
        'male': 33,
        'female': 39,
        'nopell': 49,
        'pell': 30,
        'testscore_lowest_quintile': 18,
        'testscore_2nd_quintile': 30,
        'testscore_mid_quintile': 37,
        'testscore_4th_quintile': 45,
        'testscore_highest_quintile': 50,
        'fulltime': 38,
        'parttime': 23
      },
      {
        'name': 'State Average',
        'white': 35,
        'black': 18,
        'hispanic': 32,
        'asian': 47,
        'otherrace': 31,
        'male': 28,
        'female': 34,
        'nopell': 35,
        'pell': 27,
        'testscore_lowest_quintile': 17,
        'testscore_2nd_quintile': 25,
        'testscore_mid_quintile': 33,
        'testscore_4th_quintile': 37,
        'testscore_highest_quintile': 44,
        'fulltime': 37,
        'parttime': 17
      }
    ]
  }
}
/** END **/

export default data
