// Do not manually modify this file or else it will be overwritten by the
// convert-excel-to-json.js script
const data =
/** START **/
{
  '4yr': {
    '6yr': [
      {
        'name': 'Averett University',
        'grad_rate_6yr': 45,
        'adj_6yr_grad_rate': 56,
        'white': 50,
        'black': 37,
        'male': 35,
        'female': 59,
        'nopell': 48,
        'pell': 43,
        'sat_lowest_quintile': 38,
        'sat_2nd_quintile': 51,
        'sat_mid_quintile': 47,
        'sat_4th_quintile': 69,
        'gpa_lowest_quintile': 35,
        'gpa_2nd_quintile': 54,
        'gpa_mid_quintile': 49,
        'gpa_4th_quintile': 51,
        'gpa_highest_quintile': 50,
        'description': 'Averett University, a private Baptist and former women\'s college,  does not change its rank, despite an increase of 11 percentage points in its graduation rate.'
      },
      {
        'name': 'Bluefield College',
        'grad_rate_6yr': 32,
        'adj_6yr_grad_rate': 44,
        'white': 38,
        'black': 14,
        'otherrace': 33,
        'male': 22,
        'female': 45,
        'nopell': 41,
        'pell': 22,
        'sat_lowest_quintile': 27,
        'sat_2nd_quintile': 30,
        'sat_mid_quintile': 40,
        'gpa_lowest_quintile': 20,
        'gpa_2nd_quintile': 29,
        'gpa_mid_quintile': 44,
        'gpa_4th_quintile': 51,
        'description': 'Bluefield College, a Baptist liberal arts college,  does not change its rank, despite an increase of 13 percentage points in its graduation rate.'
      },
      {
        'name': 'Bridgewater College',
        'grad_rate_6yr': 69,
        'adj_6yr_grad_rate': 70,
        'white': 72,
        'black': 56,
        'hispanic': 67,
        'otherrace': 63,
        'male': 65,
        'female': 72,
        'nopell': 72,
        'pell': 61,
        'sat_lowest_quintile': 60,
        'sat_2nd_quintile': 64,
        'sat_mid_quintile': 74,
        'sat_4th_quintile': 81,
        'sat_highest_quintile': 83,
        'gpa_lowest_quintile': 43,
        'gpa_2nd_quintile': 61,
        'gpa_mid_quintile': 71,
        'gpa_4th_quintile': 85,
        'gpa_highest_quintile': 93,
        'description': 'Bridgewater College, a private liberal arts college, moves down 1 place in the rankings, despite an increase of 1 percentage points in its graduation rate.'
      },
      {
        'name': 'Christopher Newport University',
        'grad_rate_6yr': 83,
        'adj_6yr_grad_rate': 79,
        'white': 84,
        'black': 69,
        'hispanic': 84,
        'asian': 86,
        'otherrace': 79,
        'male': 78,
        'female': 87,
        'nopell': 83,
        'pell': 77,
        'sat_lowest_quintile': 70,
        'sat_2nd_quintile': 82,
        'sat_mid_quintile': 82,
        'sat_4th_quintile': 85,
        'sat_highest_quintile': 82,
        'gpa_lowest_quintile': 50,
        'gpa_2nd_quintile': 74,
        'gpa_mid_quintile': 82,
        'gpa_4th_quintile': 88,
        'gpa_highest_quintile': 92,
        'description': 'Christopher Newport University, a public liberal arts university, moves up 3 places in the rankings, despite a decrease of 4 percentage points in its graduation rate.'
      },
      {
        'name': 'College of William and Mary',
        'grad_rate_6yr': 93,
        'adj_6yr_grad_rate': 79,
        'white': 94,
        'black': 89,
        'hispanic': 92,
        'asian': 88,
        'otherrace': 91,
        'male': 90,
        'female': 95,
        'nopell': 93,
        'pell': 89,
        'sat_2nd_quintile': 80,
        'sat_mid_quintile': 89,
        'sat_4th_quintile': 92,
        'sat_highest_quintile': 93,
        'gpa_2nd_quintile': 85,
        'gpa_mid_quintile': 87,
        'gpa_4th_quintile': 91,
        'gpa_highest_quintile': 95,
        'description': 'College of William and Mary, a public research university and the second-oldest institution of higher education in the US, moves down 3 places in the rankings, reflecting a decrease of 14 percentage points in its graduation rate.'
      },
      {
        'name': 'Eastern Mennonite University',
        'grad_rate_6yr': 66,
        'adj_6yr_grad_rate': 66,
        'white': 72,
        'black': 37,
        'hispanic': 56,
        'otherrace': 46,
        'male': 60,
        'female': 69,
        'nopell': 72,
        'pell': 54,
        'sat_lowest_quintile': 45,
        'sat_2nd_quintile': 62,
        'sat_mid_quintile': 67,
        'sat_4th_quintile': 75,
        'sat_highest_quintile': 88,
        'gpa_lowest_quintile': 34,
        'gpa_2nd_quintile': 54,
        'gpa_mid_quintile': 64,
        'gpa_4th_quintile': 83,
        'gpa_highest_quintile': 93,
        'description': 'Eastern Mennonite University, a private Mennonite liberal arts university in Harrisonburg, moves down 3 places in the rankings, despite no change in its graduation rate.'
      },
      {
        'name': 'Emory and Henry College',
        'grad_rate_6yr': 58,
        'adj_6yr_grad_rate': 61,
        'white': 61,
        'black': 51,
        'otherrace': 44,
        'male': 50,
        'female': 69,
        'nopell': 65,
        'pell': 49,
        'sat_lowest_quintile': 50,
        'sat_2nd_quintile': 55,
        'sat_mid_quintile': 64,
        'sat_4th_quintile': 64,
        'sat_highest_quintile': 70,
        'gpa_lowest_quintile': 36,
        'gpa_2nd_quintile': 49,
        'gpa_mid_quintile': 61,
        'gpa_4th_quintile': 69,
        'gpa_highest_quintile': 83,
        'description': 'Emory and Henry College, a private liberal arts college,  moves down 4 places in the rankings, despite an increase of 3 percentage points in its graduation rate.'
      },
      {
        'name': 'Ferrum College',
        'grad_rate_6yr': 35,
        'adj_6yr_grad_rate': 55,
        'white': 41,
        'black': 29,
        'hispanic': 38,
        'otherrace': 31,
        'male': 30,
        'female': 42,
        'nopell': 41,
        'pell': 31,
        'sat_lowest_quintile': 31,
        'sat_2nd_quintile': 38,
        'sat_mid_quintile': 50,
        'sat_4th_quintile': 50,
        'gpa_lowest_quintile': 25,
        'gpa_2nd_quintile': 49,
        'gpa_mid_quintile': 60,
        'gpa_4th_quintile': 57,
        'gpa_highest_quintile': 81,
        'description': 'Ferrum College, a private college, moves up 2 places in the rankings, reflecting an increase of 20 percentage points in its graduation rate.'
      },
      {
        'name': 'George Mason University',
        'grad_rate_6yr': 73,
        'adj_6yr_grad_rate': 70,
        'white': 73,
        'black': 72,
        'hispanic': 67,
        'asian': 77,
        'otherrace': 70,
        'male': 67,
        'female': 79,
        'nopell': 74,
        'pell': 70,
        'sat_lowest_quintile': 63,
        'sat_2nd_quintile': 71,
        'sat_mid_quintile': 75,
        'sat_4th_quintile': 74,
        'sat_highest_quintile': 72,
        'gpa_lowest_quintile': 52,
        'gpa_2nd_quintile': 64,
        'gpa_mid_quintile': 72,
        'gpa_4th_quintile': 78,
        'gpa_highest_quintile': 86,
        'description': 'George Mason University, a public research university in Fairfax, moves down 5 places in the rankings, reflecting a decrease of 3 percentage points in its graduation rate.'
      },
      {
        'name': 'Hampden-Sydney College',
        'grad_rate_6yr': 69,
        'adj_6yr_grad_rate': 75,
        'white': 71,
        'black': 54,
        'otherrace': 65,
        'male': 69,
        'nopell': 70,
        'pell': 62,
        'sat_lowest_quintile': 55,
        'sat_2nd_quintile': 62,
        'sat_mid_quintile': 73,
        'sat_4th_quintile': 72,
        'sat_highest_quintile': 74,
        'gpa_lowest_quintile': 51,
        'gpa_2nd_quintile': 67,
        'gpa_mid_quintile': 73,
        'gpa_4th_quintile': 79,
        'gpa_highest_quintile': 90,
        'description': 'Hampden-Sydney College, a men\'s liberal arts college, moves up 5 places in the rankings, reflecting an increase of 7 percentage points in its graduation rate.'
      },
      {
        'name': 'Hampton University',
        'grad_rate_6yr': 54,
        'adj_6yr_grad_rate': 63,
        'white': 43,
        'black': 54,
        'hispanic': 55,
        'otherrace': 74,
        'male': 48,
        'female': 57,
        'nopell': 59,
        'pell': 46,
        'sat_lowest_quintile': 51,
        'sat_2nd_quintile': 54,
        'sat_mid_quintile': 56,
        'sat_4th_quintile': 63,
        'sat_highest_quintile': 60,
        'gpa_lowest_quintile': 46,
        'gpa_2nd_quintile': 53,
        'gpa_mid_quintile': 58,
        'gpa_4th_quintile': 69,
        'gpa_highest_quintile': 77,
        'description': 'Hampton University, a private historically black university in Hampton, moves up 3 places in the rankings, reflecting an increase of 10 percentage points in its graduation rate.'
      },
      {
        'name': 'Hollins University',
        'grad_rate_6yr': 62,
        'adj_6yr_grad_rate': 60,
        'white': 62,
        'black': 63,
        'hispanic': 43,
        'otherrace': 65,
        'female': 62,
        'nopell': 68,
        'pell': 53,
        'sat_lowest_quintile': 50,
        'sat_2nd_quintile': 51,
        'sat_mid_quintile': 65,
        'sat_4th_quintile': 64,
        'sat_highest_quintile': 76,
        'gpa_lowest_quintile': 39,
        'gpa_2nd_quintile': 53,
        'gpa_mid_quintile': 60,
        'gpa_4th_quintile': 69,
        'gpa_highest_quintile': 83,
        'description': 'Hollins University, a private women\'s college,  moves down 8 places in the rankings, reflecting a decrease of 2 percentage points in its graduation rate.'
      },
      {
        'name': 'James Madison University',
        'grad_rate_6yr': 86,
        'adj_6yr_grad_rate': 79,
        'white': 87,
        'black': 73,
        'hispanic': 84,
        'asian': 88,
        'otherrace': 84,
        'male': 82,
        'female': 89,
        'nopell': 88,
        'pell': 78,
        'sat_lowest_quintile': 72,
        'sat_2nd_quintile': 83,
        'sat_mid_quintile': 87,
        'sat_4th_quintile': 88,
        'sat_highest_quintile': 87,
        'gpa_lowest_quintile': 62,
        'gpa_2nd_quintile': 74,
        'gpa_mid_quintile': 83,
        'gpa_4th_quintile': 89,
        'gpa_highest_quintile': 92,
        'description': 'James Madison University, a public research university in Harrisonburg, moves down 2 places in the rankings, reflecting a decrease of 8 percentage points in its graduation rate.'
      },
      {
        'name': 'Jefferson College of Health Sciences',
        'grad_rate_6yr': 45,
        'adj_6yr_grad_rate': 50,
        'white': 50,
        'male': 54,
        'female': 43,
        'nopell': 59,
        'pell': 31,
        'sat_lowest_quintile': 31,
        'sat_2nd_quintile': 58,
        'sat_mid_quintile': 67,
        'gpa_lowest_quintile': 17,
        'gpa_2nd_quintile': 36,
        'gpa_mid_quintile': 66,
        'gpa_4th_quintile': 52,
        'description': 'Jefferson College of Health Sciences, a private and independent health sciences college in Roanoke, moves down 3 places in the rankings, despite an increase of 5 percentage points in its graduation rate.'
      },
      {
        'name': 'Liberty University',
        'grad_rate_6yr': 56,
        'adj_6yr_grad_rate': 62,
        'white': 59,
        'black': 37,
        'hispanic': 47,
        'asian': 57,
        'otherrace': 54,
        'male': 50,
        'female': 61,
        'nopell': 60,
        'pell': 45,
        'sat_lowest_quintile': 42,
        'sat_2nd_quintile': 54,
        'sat_mid_quintile': 62,
        'sat_4th_quintile': 68,
        'sat_highest_quintile': 76,
        'gpa_lowest_quintile': 34,
        'gpa_2nd_quintile': 52,
        'gpa_mid_quintile': 64,
        'gpa_4th_quintile': 75,
        'gpa_highest_quintile': 84,
        'description': 'Liberty University, a private evangelical Christian university in Lynchburg, moves down 2 places in the rankings, despite an increase of 6 percentage points in its graduation rate.'
      },
      {
        'name': 'Longwood University',
        'grad_rate_6yr': 74,
        'adj_6yr_grad_rate': 76,
        'white': 74,
        'black': 72,
        'hispanic': 73,
        'asian': 78,
        'otherrace': 71,
        'male': 66,
        'female': 78,
        'nopell': 76,
        'pell': 66,
        'sat_lowest_quintile': 71,
        'sat_2nd_quintile': 75,
        'sat_mid_quintile': 74,
        'sat_4th_quintile': 76,
        'sat_highest_quintile': 64,
        'gpa_lowest_quintile': 55,
        'gpa_2nd_quintile': 71,
        'gpa_mid_quintile': 80,
        'gpa_4th_quintile': 85,
        'gpa_highest_quintile': 91,
        'description': 'Longwood University, a public liberal arts university, moves up 1 place in the rankings, reflecting an increase of 2 percentage points in its graduation rate.'
      },
      {
        'name': 'University of Lynchburg',
        'grad_rate_6yr': 63,
        'adj_6yr_grad_rate': 70,
        'white': 64,
        'black': 57,
        'hispanic': 52,
        'asian': 69,
        'otherrace': 60,
        'male': 56,
        'female': 68,
        'nopell': 65,
        'pell': 57,
        'sat_lowest_quintile': 55,
        'sat_2nd_quintile': 62,
        'sat_mid_quintile': 69,
        'sat_4th_quintile': 66,
        'sat_highest_quintile': 75,
        'gpa_lowest_quintile': 47,
        'gpa_2nd_quintile': 64,
        'gpa_mid_quintile': 72,
        'gpa_4th_quintile': 80,
        'gpa_highest_quintile': 89,
        'description': 'University of Lynchburg, a private university associated with the Christian Church, moves up 3 places in the rankings, reflecting an increase of 7 percentage points in its graduation rate.'
      },
      {
        'name': 'Mary Baldwin College',
        'grad_rate_6yr': 49,
        'adj_6yr_grad_rate': 55,
        'white': 53,
        'black': 44,
        'hispanic': 54,
        'asian': 48,
        'otherrace': 41,
        'female': 49,
        'nopell': 51,
        'pell': 47,
        'sat_lowest_quintile': 47,
        'sat_2nd_quintile': 54,
        'sat_mid_quintile': 57,
        'sat_4th_quintile': 48,
        'sat_highest_quintile': 44,
        'gpa_lowest_quintile': 40,
        'gpa_2nd_quintile': 48,
        'gpa_mid_quintile': 57,
        'gpa_4th_quintile': 55,
        'gpa_highest_quintile': 64,
        'description': 'Mary Baldwin College, a private Presbyterian liberal arts and former women\'s university in Staunton, moves down 3 places in the rankings, despite an increase of 7 percentage points in its graduation rate.'
      },
      {
        'name': 'Marymount University',
        'grad_rate_6yr': 58,
        'adj_6yr_grad_rate': 66,
        'white': 64,
        'black': 44,
        'hispanic': 57,
        'asian': 65,
        'otherrace': 60,
        'male': 53,
        'female': 61,
        'nopell': 62,
        'pell': 50,
        'sat_lowest_quintile': 51,
        'sat_2nd_quintile': 59,
        'sat_mid_quintile': 62,
        'sat_4th_quintile': 69,
        'sat_highest_quintile': 69,
        'gpa_lowest_quintile': 47,
        'gpa_2nd_quintile': 56,
        'gpa_mid_quintile': 74,
        'gpa_4th_quintile': 79,
        'gpa_highest_quintile': 77,
        'description': 'Marymount University, a Catholic university with its main campus in Arlington, moves up 4 places in the rankings, reflecting an increase of 8 percentage points in its graduation rate.'
      },
      {
        'name': 'Norfolk State University',
        'grad_rate_6yr': 38,
        'adj_6yr_grad_rate': 57,
        'white': 44,
        'black': 38,
        'hispanic': 35,
        'otherrace': 36,
        'male': 32,
        'female': 43,
        'nopell': 43,
        'pell': 35,
        'sat_lowest_quintile': 36,
        'sat_2nd_quintile': 37,
        'sat_mid_quintile': 50,
        'sat_4th_quintile': 50,
        'gpa_lowest_quintile': 30,
        'gpa_2nd_quintile': 45,
        'gpa_mid_quintile': 60,
        'gpa_4th_quintile': 71,
        'gpa_highest_quintile': 77,
        'description': 'Norfolk State University, a public historically black university, moves up 4 places in the rankings, reflecting an increase of 19 percentage points in its graduation rate.'
      },
      {
        'name': 'Old Dominion University',
        'grad_rate_6yr': 55,
        'adj_6yr_grad_rate': 61,
        'white': 57,
        'black': 52,
        'hispanic': 56,
        'asian': 57,
        'otherrace': 50,
        'male': 50,
        'female': 60,
        'nopell': 57,
        'pell': 51,
        'sat_lowest_quintile': 55,
        'sat_2nd_quintile': 52,
        'sat_mid_quintile': 56,
        'sat_4th_quintile': 59,
        'sat_highest_quintile': 55,
        'gpa_lowest_quintile': 42,
        'gpa_2nd_quintile': 53,
        'gpa_mid_quintile': 61,
        'gpa_4th_quintile': 71,
        'gpa_highest_quintile': 82,
        'description': 'Old Dominion University, a public research university and one of the largest in Virginia, moves down 3 places in the rankings, despite an increase of 6 percentage points in its graduation rate.'
      },
      {
        'name': 'Radford University',
        'grad_rate_6yr': 66,
        'adj_6yr_grad_rate': 73,
        'white': 67,
        'black': 63,
        'hispanic': 58,
        'asian': 63,
        'otherrace': 64,
        'male': 60,
        'female': 71,
        'nopell': 69,
        'pell': 59,
        'sat_lowest_quintile': 64,
        'sat_2nd_quintile': 67,
        'sat_mid_quintile': 68,
        'sat_4th_quintile': 67,
        'sat_highest_quintile': 61,
        'gpa_lowest_quintile': 55,
        'gpa_2nd_quintile': 69,
        'gpa_mid_quintile': 75,
        'gpa_4th_quintile': 80,
        'gpa_highest_quintile': 88,
        'description': 'Radford University, a public university, moves up 4 places in the rankings, reflecting an increase of 7 percentage points in its graduation rate.'
      },
      {
        'name': 'Randolph College',
        'grad_rate_6yr': 70,
        'adj_6yr_grad_rate': 71,
        'white': 71,
        'black': 63,
        'hispanic': 66,
        'asian': 77,
        'otherrace': 70,
        'male': 66,
        'female': 73,
        'nopell': 72,
        'pell': 63,
        'sat_lowest_quintile': 65,
        'sat_2nd_quintile': 64,
        'sat_mid_quintile': 69,
        'sat_4th_quintile': 77,
        'sat_highest_quintile': 80,
        'gpa_lowest_quintile': 51,
        'gpa_2nd_quintile': 63,
        'gpa_mid_quintile': 72,
        'gpa_4th_quintile': 81,
        'gpa_highest_quintile': 87,
        'description': 'Randolph College, a private liberal arts and sciences and former women\'s college, moves down 2 places in the rankings, despite an increase of 1 percentage points in its graduation rate.'
      },
      {
        'name': 'Regent University',
        'grad_rate_6yr': 50,
        'adj_6yr_grad_rate': 52,
        'white': 55,
        'black': 33,
        'otherrace': 45,
        'male': 49,
        'female': 51,
        'nopell': 57,
        'pell': 38,
        'sat_lowest_quintile': 38,
        'sat_2nd_quintile': 43,
        'sat_mid_quintile': 60,
        'sat_4th_quintile': 61,
        'gpa_lowest_quintile': 25,
        'gpa_2nd_quintile': 44,
        'gpa_mid_quintile': 51,
        'gpa_4th_quintile': 56,
        'gpa_highest_quintile': 78,
        'description': 'Regent University, a private Christian university in Virginia Beach, moves down 7 places in the rankings, despite an increase of 1 percentage points in its graduation rate.'
      },
      {
        'name': 'Roanoke College',
        'grad_rate_6yr': 69,
        'adj_6yr_grad_rate': 71,
        'white': 70,
        'black': 69,
        'hispanic': 59,
        'otherrace': 69,
        'male': 61,
        'female': 75,
        'nopell': 71,
        'pell': 63,
        'sat_lowest_quintile': 57,
        'sat_2nd_quintile': 68,
        'sat_mid_quintile': 69,
        'sat_4th_quintile': 73,
        'sat_highest_quintile': 79,
        'gpa_lowest_quintile': 54,
        'gpa_2nd_quintile': 63,
        'gpa_mid_quintile': 71,
        'gpa_4th_quintile': 82,
        'gpa_highest_quintile': 89,
        'description': 'Roanoke College, a private liberal arts college,  does not change its rank, despite an increase of 2 percentage points in its graduation rate.'
      },
      {
        'name': 'Shenandoah University',
        'grad_rate_6yr': 63,
        'adj_6yr_grad_rate': 67,
        'white': 66,
        'black': 51,
        'hispanic': 64,
        'asian': 71,
        'otherrace': 53,
        'male': 54,
        'female': 71,
        'nopell': 67,
        'pell': 51,
        'sat_lowest_quintile': 54,
        'sat_2nd_quintile': 59,
        'sat_mid_quintile': 65,
        'sat_4th_quintile': 77,
        'sat_highest_quintile': 80,
        'gpa_lowest_quintile': 42,
        'gpa_2nd_quintile': 58,
        'gpa_mid_quintile': 74,
        'gpa_4th_quintile': 76,
        'gpa_highest_quintile': 92,
        'description': 'Shenandoah University, a private university in Winchester, moves up 3 places in the rankings, reflecting an increase of 4 percentage points in its graduation rate.'
      },
      {
        'name': 'Southern Virginia University',
        'grad_rate_6yr': 22,
        'adj_6yr_grad_rate': 28,
        'white': 23,
        'black': 12,
        'otherrace': 18,
        'male': 12,
        'female': 33,
        'nopell': 23,
        'pell': 20,
        'sat_lowest_quintile': 16,
        'sat_2nd_quintile': 17,
        'sat_mid_quintile': 25,
        'sat_4th_quintile': 21,
        'sat_highest_quintile': 40,
        'gpa_lowest_quintile': 12,
        'gpa_2nd_quintile': 14,
        'gpa_mid_quintile': 26,
        'gpa_4th_quintile': 37,
        'gpa_highest_quintile': 28,
        'description': 'Southern Virginia University, a public liberal arts college in Buena Vista,  does not change its rank, despite an increase of 7 percentage points in its graduation rate.'
      },
      {
        'name': 'Sweet Briar College',
        'grad_rate_6yr': 63,
        'adj_6yr_grad_rate': 64,
        'white': 68,
        'otherrace': 62,
        'female': 63,
        'nopell': 66,
        'pell': 57,
        'sat_lowest_quintile': 45,
        'sat_2nd_quintile': 65,
        'sat_mid_quintile': 68,
        'sat_4th_quintile': 74,
        'sat_highest_quintile': 64,
        'gpa_lowest_quintile': 50,
        'gpa_2nd_quintile': 49,
        'gpa_mid_quintile': 69,
        'gpa_4th_quintile': 74,
        'gpa_highest_quintile': 82,
        'description': 'Sweet Briar College, a private women\'s liberal arts college, moves down 4 places in the rankings, despite an increase of 1 percentage points in its graduation rate.'
      },
      {
        'name': 'University of Mary Washington',
        'grad_rate_6yr': 77,
        'adj_6yr_grad_rate': 74,
        'white': 78,
        'black': 68,
        'hispanic': 73,
        'asian': 82,
        'otherrace': 75,
        'male': 70,
        'female': 80,
        'nopell': 78,
        'pell': 72,
        'sat_lowest_quintile': 63,
        'sat_2nd_quintile': 74,
        'sat_mid_quintile': 78,
        'sat_4th_quintile': 78,
        'sat_highest_quintile': 80,
        'gpa_lowest_quintile': 54,
        'gpa_2nd_quintile': 69,
        'gpa_mid_quintile': 78,
        'gpa_4th_quintile': 84,
        'gpa_highest_quintile': 88,
        'description': 'University of Mary Washington, a public liberal arts and sciences university in Fredericksburg, moves down 2 places in the rankings, reflecting a decrease of 3 percentage points in its graduation rate.'
      },
      {
        'name': 'University of Richmond',
        'grad_rate_6yr': 89,
        'adj_6yr_grad_rate': 82,
        'white': 90,
        'black': 89,
        'hispanic': 81,
        'asian': 93,
        'otherrace': 89,
        'male': 88,
        'female': 90,
        'nopell': 89,
        'pell': 91,
        'sat_lowest_quintile': 88,
        'sat_2nd_quintile': 87,
        'sat_mid_quintile': 85,
        'sat_4th_quintile': 86,
        'sat_highest_quintile': 91,
        'gpa_lowest_quintile': 86,
        'gpa_2nd_quintile': 81,
        'gpa_mid_quintile': 89,
        'gpa_4th_quintile': 91,
        'gpa_highest_quintile': 91,
        'description': 'University of Richmond, a private liberal arts college, moves up 3 places in the rankings, despite a decrease of 8 percentage points in its graduation rate.'
      },
      {
        'name': 'University of Virginia',
        'grad_rate_6yr': 96,
        'adj_6yr_grad_rate': 79,
        'white': 97,
        'black': 93,
        'hispanic': 94,
        'asian': 96,
        'otherrace': 96,
        'male': 94,
        'female': 97,
        'nopell': 97,
        'pell': 93,
        'sat_lowest_quintile': 80,
        'sat_2nd_quintile': 93,
        'sat_mid_quintile': 95,
        'sat_4th_quintile': 96,
        'sat_highest_quintile': 96,
        'gpa_lowest_quintile': 58,
        'gpa_2nd_quintile': 91,
        'gpa_mid_quintile': 95,
        'gpa_4th_quintile': 95,
        'gpa_highest_quintile': 97,
        'description': 'University of Virginia, a public research university founded by Thomas Jefferson, moves down 3 places in the rankings, reflecting a decrease of 17 percentage points in its graduation rate.'
      },
      {
        'name': 'University of Virginia\'s College at Wise',
        'grad_rate_6yr': 50,
        'adj_6yr_grad_rate': 58,
        'white': 51,
        'black': 45,
        'otherrace': 51,
        'male': 45,
        'female': 55,
        'nopell': 55,
        'pell': 46,
        'sat_lowest_quintile': 43,
        'sat_2nd_quintile': 52,
        'sat_mid_quintile': 62,
        'sat_4th_quintile': 65,
        'sat_highest_quintile': 48,
        'gpa_lowest_quintile': 33,
        'gpa_2nd_quintile': 42,
        'gpa_mid_quintile': 60,
        'gpa_4th_quintile': 69,
        'gpa_highest_quintile': 81,
        'description': 'University of Virginia\'s College at Wise, a public liberal arts college, moves down 1 place in the rankings, despite an increase of 8 percentage points in its graduation rate.'
      },
      {
        'name': 'Virginia Commonwealth University',
        'grad_rate_6yr': 65,
        'adj_6yr_grad_rate': 66,
        'white': 66,
        'black': 63,
        'hispanic': 63,
        'asian': 70,
        'otherrace': 63,
        'male': 60,
        'female': 69,
        'nopell': 67,
        'pell': 61,
        'sat_lowest_quintile': 61,
        'sat_2nd_quintile': 65,
        'sat_mid_quintile': 66,
        'sat_4th_quintile': 66,
        'sat_highest_quintile': 69,
        'gpa_lowest_quintile': 46,
        'gpa_2nd_quintile': 59,
        'gpa_mid_quintile': 68,
        'gpa_4th_quintile': 75,
        'gpa_highest_quintile': 84,
        'description': 'Virginia Commonwealth University, a public research university in Richmond, moves down 3 places in the rankings, despite no change in its graduation rate.'
      },
      {
        'name': 'Virginia Military Institute',
        'grad_rate_6yr': 79,
        'adj_6yr_grad_rate': 81,
        'white': 80,
        'black': 63,
        'hispanic': 72,
        'asian': 86,
        'male': 79,
        'female': 78,
        'nopell': 81,
        'pell': 70,
        'sat_lowest_quintile': 56,
        'sat_2nd_quintile': 74,
        'sat_mid_quintile': 79,
        'sat_4th_quintile': 84,
        'sat_highest_quintile': 79,
        'gpa_lowest_quintile': 55,
        'gpa_2nd_quintile': 76,
        'gpa_mid_quintile': 85,
        'gpa_4th_quintile': 83,
        'gpa_highest_quintile': 90,
        'description': 'Virginia Military Institute, the oldest state-supported military college in the US,  moves up 5 places in the rankings, reflecting an increase of 2 percentage points in its graduation rate.'
      },
      {
        'name': 'Virginia State University',
        'grad_rate_6yr': 46,
        'adj_6yr_grad_rate': 66,
        'white': 37,
        'black': 48,
        'hispanic': 42,
        'otherrace': 42,
        'male': 40,
        'female': 49,
        'nopell': 51,
        'pell': 43,
        'sat_lowest_quintile': 45,
        'sat_2nd_quintile': 48,
        'sat_mid_quintile': 52,
        'sat_4th_quintile': 58,
        'gpa_lowest_quintile': 40,
        'gpa_2nd_quintile': 54,
        'gpa_mid_quintile': 60,
        'gpa_4th_quintile': 65,
        'gpa_highest_quintile': 86,
        'description': 'Virginia State University, a historically black public land-grant university in Ettrick, moves up 10 places in the rankings, reflecting an increase of 20 percentage points in its graduation rate.'
      },
      {
        'name': 'Virginia Tech',
        'grad_rate_6yr': 89,
        'adj_6yr_grad_rate': 79,
        'white': 90,
        'black': 79,
        'hispanic': 90,
        'asian': 91,
        'otherrace': 87,
        'male': 86,
        'female': 94,
        'nopell': 91,
        'pell': 83,
        'sat_lowest_quintile': 76,
        'sat_2nd_quintile': 85,
        'sat_mid_quintile': 88,
        'sat_4th_quintile': 91,
        'sat_highest_quintile': 90,
        'gpa_lowest_quintile': 64,
        'gpa_2nd_quintile': 75,
        'gpa_mid_quintile': 84,
        'gpa_4th_quintile': 90,
        'gpa_highest_quintile': 92,
        'description': 'Virginia Tech, a public land-grant research university, moves down 3 places in the rankings, reflecting a decrease of 11 percentage points in its graduation rate.'
      },
      {
        'name': 'Virginia Union University',
        'grad_rate_6yr': 38,
        'adj_6yr_grad_rate': 62,
        'black': 38,
        'male': 33,
        'female': 41,
        'nopell': 42,
        'pell': 36,
        'sat_lowest_quintile': 39,
        'sat_2nd_quintile': 38,
        'gpa_lowest_quintile': 34,
        'gpa_2nd_quintile': 55,
        'gpa_mid_quintile': 57,
        'description': 'Virginia Union University, a private historically black university in Richmond, moves up 9 places in the rankings, reflecting an increase of 24 percentage points in its graduation rate.'
      },
      {
        'name': 'Virginia Wesleyan College',
        'grad_rate_6yr': 55,
        'adj_6yr_grad_rate': 64,
        'white': 57,
        'black': 50,
        'hispanic': 53,
        'otherrace': 56,
        'male': 49,
        'female': 58,
        'nopell': 59,
        'pell': 48,
        'sat_lowest_quintile': 46,
        'sat_2nd_quintile': 54,
        'sat_mid_quintile': 63,
        'sat_4th_quintile': 68,
        'sat_highest_quintile': 67,
        'gpa_lowest_quintile': 39,
        'gpa_2nd_quintile': 60,
        'gpa_mid_quintile': 59,
        'gpa_4th_quintile': 75,
        'gpa_highest_quintile': 86,
        'description': 'Virginia Wesleyan College, a private university in Virginia Beach, moves up 3 places in the rankings, reflecting an increase of 9 percentage points in its graduation rate.'
      },
      {
        'name': 'Washington and Lee University',
        'grad_rate_6yr': 98,
        'adj_6yr_grad_rate': 86,
        'white': 98,
        'male': 97,
        'nopell': 98,
        'sat_highest_quintile': 98,
        'description': 'Washington and Lee University, a private liberal arts college in Lexington,  does not change its rank, despite a decrease of 12 percentage points in its graduation rate.'
      },
      {
        'name': 'State Average',
        'white': 75,
        'black': 53,
        'hispanic': 70,
        'asian': 80,
        'otherrace': 66,
        'male': 66,
        'female': 74,
        'nopell': 75,
        'pell': 57,
        'sat_lowest_quintile': 49,
        'sat_2nd_quintile': 63,
        'sat_mid_quintile': 73,
        'sat_4th_quintile': 79,
        'sat_highest_quintile': 86,
        'gpa_lowest_quintile': 41,
        'gpa_2nd_quintile': 60,
        'gpa_mid_quintile': 73,
        'gpa_4th_quintile': 83,
        'gpa_highest_quintile': 91
      }
    ],
    '4yr': [
      {
        'name': 'Averett University',
        'grad_rate_4yr': 34,
        'adj_4yr_grad_rate': 47,
        'white': 39,
        'black': 23,
        'male': 26,
        'female': 45,
        'nopell': 38,
        'pell': 30,
        'sat_lowest_quintile': 24,
        'sat_2nd_quintile': 44,
        'sat_mid_quintile': 36,
        'sat_4th_quintile': 54,
        'gpa_lowest_quintile': 25,
        'gpa_2nd_quintile': 41,
        'gpa_mid_quintile': 35,
        'gpa_4th_quintile': 36,
        'gpa_highest_quintile': 47,
        'description': 'Averett University, a private Baptist and former women\'s college, moves up 3 places in the rankings, reflecting an increase of 13 percentage points in its graduation rate.'
      },
      {
        'name': 'Bluefield College',
        'grad_rate_4yr': 19,
        'adj_4yr_grad_rate': 35,
        'white': 24,
        'black': 6,
        'otherrace': 18,
        'male': 11,
        'female': 30,
        'nopell': 25,
        'pell': 14,
        'sat_lowest_quintile': 14,
        'sat_2nd_quintile': 21,
        'sat_mid_quintile': 30,
        'gpa_lowest_quintile': 6,
        'gpa_2nd_quintile': 20,
        'gpa_mid_quintile': 31,
        'gpa_4th_quintile': 39,
        'description': 'Bluefield College, a Baptist liberal arts college, does not change its rank, despite an increase of 16 percentage points in its graduation rate.'
      },
      {
        'name': 'Bridgewater College',
        'grad_rate_4yr': 53,
        'adj_4yr_grad_rate': 55,
        'white': 57,
        'black': 35,
        'hispanic': 48,
        'otherrace': 46,
        'male': 44,
        'female': 60,
        'nopell': 57,
        'pell': 45,
        'sat_lowest_quintile': 42,
        'sat_2nd_quintile': 47,
        'sat_mid_quintile': 59,
        'sat_4th_quintile': 67,
        'sat_highest_quintile': 75,
        'gpa_lowest_quintile': 23,
        'gpa_2nd_quintile': 39,
        'gpa_mid_quintile': 56,
        'gpa_4th_quintile': 75,
        'gpa_highest_quintile': 88,
        'description': 'Bridgewater College, a private liberal arts college, moves up 3 places in the rankings, reflecting an increase of 2 percentage points in its graduation rate.'
      },
      {
        'name': 'Christopher Newport University',
        'grad_rate_4yr': 64,
        'adj_4yr_grad_rate': 58,
        'white': 65,
        'black': 43,
        'hispanic': 67,
        'asian': 61,
        'otherrace': 61,
        'male': 52,
        'female': 73,
        'nopell': 65,
        'pell': 53,
        'sat_lowest_quintile': 44,
        'sat_2nd_quintile': 62,
        'sat_mid_quintile': 61,
        'sat_4th_quintile': 67,
        'sat_highest_quintile': 64,
        'gpa_lowest_quintile': 23,
        'gpa_2nd_quintile': 47,
        'gpa_mid_quintile': 62,
        'gpa_4th_quintile': 71,
        'gpa_highest_quintile': 83,
        'description': 'Christopher Newport University, a public liberal arts university, moves down 2 places in the rankings, reflecting a decrease of 5 percentage points in its graduation rate.'
      },
      {
        'name': 'College of William and Mary',
        'grad_rate_4yr': 82,
        'adj_4yr_grad_rate': 64,
        'white': 86,
        'black': 70,
        'hispanic': 81,
        'asian': 75,
        'otherrace': 79,
        'male': 77,
        'female': 87,
        'nopell': 83,
        'pell': 75,
        'sat_2nd_quintile': 60,
        'sat_mid_quintile': 70,
        'sat_4th_quintile': 77,
        'sat_highest_quintile': 85,
        'gpa_2nd_quintile': 58,
        'gpa_mid_quintile': 70,
        'gpa_4th_quintile': 78,
        'gpa_highest_quintile': 88,
        'description': 'College of William and Mary, a public research university and the second-oldest institution of higher education in the US, moves down 3 places in the rankings, reflecting a decrease of 18 percentage points in its graduation rate.'
      },
      {
        'name': 'Eastern Mennonite University',
        'grad_rate_4yr': 48,
        'adj_4yr_grad_rate': 48,
        'white': 56,
        'black': 15,
        'hispanic': 30,
        'otherrace': 29,
        'male': 39,
        'female': 53,
        'nopell': 55,
        'pell': 35,
        'sat_lowest_quintile': 25,
        'sat_2nd_quintile': 40,
        'sat_mid_quintile': 47,
        'sat_4th_quintile': 65,
        'sat_highest_quintile': 75,
        'gpa_lowest_quintile': 16,
        'gpa_2nd_quintile': 28,
        'gpa_mid_quintile': 48,
        'gpa_4th_quintile': 66,
        'gpa_highest_quintile': 84,
        'description': 'Eastern Mennonite University, a private Mennonite liberal arts university in Harrisonburg, moves down 5 places in the rankings, reflecting no change in its graduation rate.'
      },
      {
        'name': 'Emory and Henry College',
        'grad_rate_4yr': 40,
        'adj_4yr_grad_rate': 44,
        'white': 43,
        'black': 25,
        'otherrace': 33,
        'male': 31,
        'female': 51,
        'nopell': 48,
        'pell': 30,
        'sat_lowest_quintile': 25,
        'sat_2nd_quintile': 36,
        'sat_mid_quintile': 50,
        'sat_4th_quintile': 50,
        'sat_highest_quintile': 62,
        'gpa_lowest_quintile': 16,
        'gpa_2nd_quintile': 30,
        'gpa_mid_quintile': 38,
        'gpa_4th_quintile': 52,
        'gpa_highest_quintile': 72,
        'description': 'Emory and Henry College, a private liberal arts college,  moves down 4 places in the rankings, despite an increase of 4 percentage points in its graduation rate.'
      },
      {
        'name': 'Ferrum College',
        'grad_rate_4yr': 19,
        'adj_4yr_grad_rate': 43,
        'white': 25,
        'black': 14,
        'hispanic': 17,
        'otherrace': 14,
        'male': 13,
        'female': 27,
        'nopell': 23,
        'pell': 16,
        'sat_lowest_quintile': 15,
        'sat_2nd_quintile': 25,
        'sat_mid_quintile': 29,
        'sat_4th_quintile': 42,
        'gpa_lowest_quintile': 11,
        'gpa_2nd_quintile': 27,
        'gpa_mid_quintile': 40,
        'gpa_4th_quintile': 48,
        'gpa_highest_quintile': 68,
        'description': 'Ferrum College, a private college, moves up 8 places in the rankings, reflecting an increase of 24 percentage points in its graduation rate.'
      },
      {
        'name': 'George Mason University',
        'grad_rate_4yr': 42,
        'adj_4yr_grad_rate': 39,
        'white': 46,
        'black': 42,
        'hispanic': 37,
        'asian': 34,
        'otherrace': 39,
        'male': 31,
        'female': 52,
        'nopell': 44,
        'pell': 37,
        'sat_lowest_quintile': 30,
        'sat_2nd_quintile': 40,
        'sat_mid_quintile': 42,
        'sat_4th_quintile': 43,
        'sat_highest_quintile': 45,
        'gpa_lowest_quintile': 18,
        'gpa_2nd_quintile': 28,
        'gpa_mid_quintile': 39,
        'gpa_4th_quintile': 50,
        'gpa_highest_quintile': 65,
        'description': 'George Mason University, a public research university in Fairfax, moves down 11 places in the rankings, reflecting a decrease of 3 percentage points in its graduation rate.'
      },
      {
        'name': 'Hampden-Sydney College',
        'grad_rate_4yr': 58,
        'adj_4yr_grad_rate': 68,
        'white': 60,
        'black': 48,
        'otherrace': 54,
        'male': 58,
        'nopell': 59,
        'pell': 56,
        'sat_lowest_quintile': 41,
        'sat_2nd_quintile': 51,
        'sat_mid_quintile': 61,
        'sat_4th_quintile': 63,
        'sat_highest_quintile': 67,
        'gpa_lowest_quintile': 39,
        'gpa_2nd_quintile': 55,
        'gpa_mid_quintile': 63,
        'gpa_4th_quintile': 71,
        'gpa_highest_quintile': 84,
        'description': 'Hampden-Sydney College, a men\'s liberal arts college, moves up 7 places in the rankings, reflecting an increase of 9 percentage points in its graduation rate.'
      },
      {
        'name': 'Hampton University',
        'grad_rate_4yr': 34,
        'adj_4yr_grad_rate': 47,
        'white': 17,
        'black': 34,
        'hispanic': 16,
        'otherrace': 50,
        'male': 24,
        'female': 40,
        'nopell': 38,
        'pell': 28,
        'sat_lowest_quintile': 30,
        'sat_2nd_quintile': 35,
        'sat_mid_quintile': 39,
        'sat_4th_quintile': 43,
        'sat_highest_quintile': 43,
        'gpa_lowest_quintile': 24,
        'gpa_2nd_quintile': 34,
        'gpa_mid_quintile': 39,
        'gpa_4th_quintile': 52,
        'gpa_highest_quintile': 62,
        'description': 'Hampton University, a private historically black university in Hampton, moves up 1 place in the rankings, reflecting an increase of 13 percentage points in its graduation rate.'
      },
      {
        'name': 'Hollins University',
        'grad_rate_4yr': 55,
        'adj_4yr_grad_rate': 51,
        'white': 57,
        'black': 50,
        'hispanic': 41,
        'otherrace': 57,
        'female': 55,
        'nopell': 63,
        'pell': 46,
        'sat_lowest_quintile': 38,
        'sat_2nd_quintile': 46,
        'sat_mid_quintile': 61,
        'sat_4th_quintile': 60,
        'sat_highest_quintile': 71,
        'gpa_lowest_quintile': 30,
        'gpa_2nd_quintile': 46,
        'gpa_mid_quintile': 56,
        'gpa_4th_quintile': 62,
        'gpa_highest_quintile': 78,
        'description': 'Hollins University, a private women\'s college,  moves down 4 places in the rankings, reflecting a decrease of 5 percentage points in its graduation rate.'
      },
      {
        'name': 'James Madison University',
        'grad_rate_4yr': 60,
        'adj_4yr_grad_rate': 50,
        'white': 62,
        'black': 38,
        'hispanic': 53,
        'asian': 55,
        'otherrace': 56,
        'male': 50,
        'female': 67,
        'nopell': 62,
        'pell': 49,
        'sat_lowest_quintile': 42,
        'sat_2nd_quintile': 54,
        'sat_mid_quintile': 61,
        'sat_4th_quintile': 62,
        'sat_highest_quintile': 62,
        'gpa_lowest_quintile': 28,
        'gpa_2nd_quintile': 43,
        'gpa_mid_quintile': 52,
        'gpa_4th_quintile': 62,
        'gpa_highest_quintile': 73,
        'description': 'James Madison University, a public research university in Harrisonburg, moves down 8 places in the rankings, reflecting a decrease of 10 percentage points in its graduation rate.'
      },
      {
        'name': 'Jefferson College of Health Sciences',
        'grad_rate_4yr': 32,
        'adj_4yr_grad_rate': 38,
        'white': 36,
        'male': 43,
        'female': 29,
        'nopell': 45,
        'pell': 20,
        'sat_lowest_quintile': 20,
        'sat_2nd_quintile': 43,
        'sat_mid_quintile': 55,
        'gpa_lowest_quintile': 8,
        'gpa_2nd_quintile': 21,
        'gpa_mid_quintile': 49,
        'gpa_4th_quintile': 40,
        'description': 'Jefferson College of Health Sciences, a private and independent health sciences college in Roanoke, moves down 3 places in the rankings, despite an increase of 5 percentage points in its graduation rate.'
      },
      {
        'name': 'Liberty University',
        'grad_rate_4yr': 29,
        'adj_4yr_grad_rate': 36,
        'white': 33,
        'black': 12,
        'hispanic': 23,
        'asian': 29,
        'otherrace': 28,
        'male': 24,
        'female': 34,
        'nopell': 33,
        'pell': 21,
        'sat_lowest_quintile': 16,
        'sat_2nd_quintile': 27,
        'sat_mid_quintile': 35,
        'sat_4th_quintile': 42,
        'sat_highest_quintile': 53,
        'gpa_lowest_quintile': 11,
        'gpa_2nd_quintile': 24,
        'gpa_mid_quintile': 34,
        'gpa_4th_quintile': 50,
        'gpa_highest_quintile': 61,
        'description': 'Liberty University, a private evangelical Christian university in Lynchburg, moves down 2 places in the rankings, despite an increase of 7 percentage points in its graduation rate.'
      },
      {
        'name': 'Longwood University',
        'grad_rate_4yr': 48,
        'adj_4yr_grad_rate': 50,
        'white': 50,
        'black': 38,
        'hispanic': 48,
        'asian': 42,
        'otherrace': 44,
        'male': 33,
        'female': 56,
        'nopell': 50,
        'pell': 40,
        'sat_lowest_quintile': 44,
        'sat_2nd_quintile': 49,
        'sat_mid_quintile': 48,
        'sat_4th_quintile': 50,
        'sat_highest_quintile': 51,
        'gpa_lowest_quintile': 26,
        'gpa_2nd_quintile': 41,
        'gpa_mid_quintile': 55,
        'gpa_4th_quintile': 66,
        'gpa_highest_quintile': 82,
        'description': 'Longwood University, a public liberal arts university, moves down 2 places in the rankings, despite an increase of 2 percentage points in its graduation rate.'
      },
      {
        'name': 'University of Lynchburg',
        'grad_rate_4yr': 44,
        'adj_4yr_grad_rate': 53,
        'white': 46,
        'black': 35,
        'hispanic': 36,
        'asian': 41,
        'otherrace': 36,
        'male': 33,
        'female': 52,
        'nopell': 46,
        'pell': 40,
        'sat_lowest_quintile': 36,
        'sat_2nd_quintile': 43,
        'sat_mid_quintile': 50,
        'sat_4th_quintile': 50,
        'sat_highest_quintile': 60,
        'gpa_lowest_quintile': 28,
        'gpa_2nd_quintile': 44,
        'gpa_mid_quintile': 54,
        'gpa_4th_quintile': 63,
        'gpa_highest_quintile': 80,
        'description': 'University of Lynchburg, a private university associated with the Christian Church, moves up 5 places in the rankings, reflecting an increase of 9 percentage points in its graduation rate.'
      },
      {
        'name': 'Mary Baldwin College',
        'grad_rate_4yr': 38,
        'adj_4yr_grad_rate': 48,
        'white': 41,
        'black': 37,
        'hispanic': 44,
        'asian': 31,
        'otherrace': 29,
        'female': 39,
        'nopell': 37,
        'pell': 40,
        'sat_lowest_quintile': 35,
        'sat_2nd_quintile': 44,
        'sat_mid_quintile': 44,
        'sat_4th_quintile': 43,
        'sat_highest_quintile': 41,
        'gpa_lowest_quintile': 29,
        'gpa_2nd_quintile': 38,
        'gpa_mid_quintile': 46,
        'gpa_4th_quintile': 45,
        'gpa_highest_quintile': 54,
        'description': 'Mary Baldwin College, a private Presbyterian liberal arts and former women\'s university in Staunton, moves up 3 places in the rankings, reflecting an increase of 10 percentage points in its graduation rate.'
      },
      {
        'name': 'Marymount University',
        'grad_rate_4yr': 32,
        'adj_4yr_grad_rate': 41,
        'white': 37,
        'black': 21,
        'hispanic': 35,
        'asian': 35,
        'otherrace': 27,
        'male': 21,
        'female': 36,
        'nopell': 35,
        'pell': 25,
        'sat_lowest_quintile': 22,
        'sat_2nd_quintile': 29,
        'sat_mid_quintile': 40,
        'sat_4th_quintile': 47,
        'sat_highest_quintile': 52,
        'gpa_lowest_quintile': 18,
        'gpa_2nd_quintile': 31,
        'gpa_mid_quintile': 44,
        'gpa_4th_quintile': 54,
        'gpa_highest_quintile': 67,
        'description': 'Marymount University, a Catholic university with its main campus in Arlington, does not change its rank, despite an increase of 9 percentage points in its graduation rate.'
      },
      {
        'name': 'Norfolk State University',
        'grad_rate_4yr': 12,
        'adj_4yr_grad_rate': 36,
        'white': 14,
        'black': 13,
        'hispanic': 9,
        'otherrace': 12,
        'male': 8,
        'female': 16,
        'nopell': 16,
        'pell': 10,
        'sat_lowest_quintile': 10,
        'sat_2nd_quintile': 15,
        'sat_mid_quintile': 24,
        'sat_4th_quintile': 26,
        'gpa_lowest_quintile': 7,
        'gpa_2nd_quintile': 15,
        'gpa_mid_quintile': 29,
        'gpa_4th_quintile': 40,
        'gpa_highest_quintile': 57,
        'description': 'Norfolk State University, a public historically black university, moves up 4 places in the rankings, reflecting an increase of 24 percentage points in its graduation rate.'
      },
      {
        'name': 'Old Dominion University',
        'grad_rate_4yr': 20,
        'adj_4yr_grad_rate': 28,
        'white': 23,
        'black': 16,
        'hispanic': 17,
        'asian': 21,
        'otherrace': 19,
        'male': 14,
        'female': 26,
        'nopell': 22,
        'pell': 16,
        'sat_lowest_quintile': 16,
        'sat_2nd_quintile': 18,
        'sat_mid_quintile': 21,
        'sat_4th_quintile': 27,
        'sat_highest_quintile': 29,
        'gpa_lowest_quintile': 9,
        'gpa_2nd_quintile': 17,
        'gpa_mid_quintile': 23,
        'gpa_4th_quintile': 37,
        'gpa_highest_quintile': 55,
        'description': 'Old Dominion University, a public research university and one of the largest in Virginia, moves down 4 places in the rankings, despite an increase of 8 percentage points in its graduation rate.'
      },
      {
        'name': 'Radford University',
        'grad_rate_4yr': 36,
        'adj_4yr_grad_rate': 44,
        'white': 37,
        'black': 29,
        'hispanic': 27,
        'asian': 26,
        'otherrace': 33,
        'male': 28,
        'female': 42,
        'nopell': 37,
        'pell': 31,
        'sat_lowest_quintile': 33,
        'sat_2nd_quintile': 35,
        'sat_mid_quintile': 38,
        'sat_4th_quintile': 42,
        'sat_highest_quintile': 39,
        'gpa_lowest_quintile': 23,
        'gpa_2nd_quintile': 36,
        'gpa_mid_quintile': 46,
        'gpa_4th_quintile': 56,
        'gpa_highest_quintile': 72,
        'description': 'Radford University, a public university, moves down 1 place in the rankings, despite an increase of 8 percentage points in its graduation rate.'
      },
      {
        'name': 'Randolph College',
        'grad_rate_4yr': 58,
        'adj_4yr_grad_rate': 59,
        'white': 60,
        'black': 48,
        'hispanic': 56,
        'asian': 63,
        'otherrace': 59,
        'male': 52,
        'female': 63,
        'nopell': 61,
        'pell': 51,
        'sat_lowest_quintile': 50,
        'sat_2nd_quintile': 50,
        'sat_mid_quintile': 57,
        'sat_4th_quintile': 67,
        'sat_highest_quintile': 75,
        'gpa_lowest_quintile': 37,
        'gpa_2nd_quintile': 49,
        'gpa_mid_quintile': 59,
        'gpa_4th_quintile': 70,
        'gpa_highest_quintile': 82,
        'description': 'Randolph College, a private liberal arts and sciences and former women\'s college, moves up 4 places in the rankings, reflecting an increase of 1 percentage points in its graduation rate.'
      },
      {
        'name': 'Regent University',
        'grad_rate_4yr': 40,
        'adj_4yr_grad_rate': 42,
        'white': 46,
        'black': 23,
        'otherrace': 29,
        'male': 34,
        'female': 45,
        'nopell': 49,
        'pell': 25,
        'sat_lowest_quintile': 25,
        'sat_2nd_quintile': 32,
        'sat_mid_quintile': 49,
        'sat_4th_quintile': 53,
        'gpa_lowest_quintile': 14,
        'gpa_2nd_quintile': 34,
        'gpa_mid_quintile': 44,
        'gpa_4th_quintile': 40,
        'gpa_highest_quintile': 73,
        'description': 'Regent University, a private Christian university in Virginia Beach, moves down 7 places in the rankings, despite an increase of 1 percentage points in its graduation rate.'
      },
      {
        'name': 'Roanoke College',
        'grad_rate_4yr': 55,
        'adj_4yr_grad_rate': 57,
        'white': 56,
        'black': 48,
        'hispanic': 46,
        'otherrace': 56,
        'male': 43,
        'female': 63,
        'nopell': 57,
        'pell': 50,
        'sat_lowest_quintile': 42,
        'sat_2nd_quintile': 53,
        'sat_mid_quintile': 57,
        'sat_4th_quintile': 58,
        'sat_highest_quintile': 66,
        'gpa_lowest_quintile': 35,
        'gpa_2nd_quintile': 48,
        'gpa_mid_quintile': 57,
        'gpa_4th_quintile': 70,
        'gpa_highest_quintile': 81,
        'description': 'Roanoke College, a private liberal arts college, moves up 4 places in the rankings, reflecting an increase of 1 percentage points in its graduation rate.'
      },
      {
        'name': 'Shenandoah University',
        'grad_rate_4yr': 42,
        'adj_4yr_grad_rate': 47,
        'white': 46,
        'black': 28,
        'hispanic': 35,
        'asian': 41,
        'otherrace': 32,
        'male': 31,
        'female': 51,
        'nopell': 46,
        'pell': 31,
        'sat_lowest_quintile': 27,
        'sat_2nd_quintile': 43,
        'sat_mid_quintile': 49,
        'sat_4th_quintile': 56,
        'sat_highest_quintile': 54,
        'gpa_lowest_quintile': 19,
        'gpa_2nd_quintile': 35,
        'gpa_mid_quintile': 55,
        'gpa_4th_quintile': 59,
        'gpa_highest_quintile': 72,
        'description': 'Shenandoah University, a private university in Winchester, moves down 2 places in the rankings, despite an increase of 6 percentage points in its graduation rate.'
      },
      {
        'name': 'Southern Virginia University',
        'grad_rate_4yr': 10,
        'adj_4yr_grad_rate': 18,
        'white': 11,
        'black': 3,
        'otherrace': 11,
        'male': 3,
        'female': 19,
        'nopell': 12,
        'pell': 9,
        'sat_lowest_quintile': 7,
        'sat_2nd_quintile': 9,
        'sat_mid_quintile': 10,
        'sat_4th_quintile': 9,
        'sat_highest_quintile': 21,
        'gpa_lowest_quintile': 3,
        'gpa_2nd_quintile': 7,
        'gpa_mid_quintile': 10,
        'gpa_4th_quintile': 22,
        'gpa_highest_quintile': 14,
        'description': 'Southern Virginia University, a public liberal arts college in Buena Vista, does not change its rank, despite an increase of 7 percentage points in its graduation rate.'
      },
      {
        'name': 'Sweet Briar College',
        'grad_rate_4yr': 52,
        'adj_4yr_grad_rate': 51,
        'white': 55,
        'otherrace': 51,
        'female': 52,
        'nopell': 54,
        'pell': 46,
        'sat_lowest_quintile': 32,
        'sat_2nd_quintile': 56,
        'sat_mid_quintile': 53,
        'sat_4th_quintile': 62,
        'sat_highest_quintile': 61,
        'gpa_lowest_quintile': 34,
        'gpa_2nd_quintile': 43,
        'gpa_mid_quintile': 57,
        'gpa_4th_quintile': 64,
        'gpa_highest_quintile': 71,
        'description': 'Sweet Briar College, a private women\'s liberal arts college, does not change its rank and has no change in its graduation rate.'
      },
      {
        'name': 'University of Mary Washington',
        'grad_rate_4yr': 61,
        'adj_4yr_grad_rate': 56,
        'white': 63,
        'black': 50,
        'hispanic': 51,
        'asian': 61,
        'otherrace': 59,
        'male': 48,
        'female': 67,
        'nopell': 62,
        'pell': 53,
        'sat_lowest_quintile': 46,
        'sat_2nd_quintile': 56,
        'sat_mid_quintile': 60,
        'sat_4th_quintile': 63,
        'sat_highest_quintile': 66,
        'gpa_lowest_quintile': 34,
        'gpa_2nd_quintile': 49,
        'gpa_mid_quintile': 59,
        'gpa_4th_quintile': 73,
        'gpa_highest_quintile': 79,
        'description': 'University of Mary Washington, a public liberal arts and sciences university in Fredericksburg, moves down 2 places in the rankings, reflecting a decrease of 5 percentage points in its graduation rate.'
      },
      {
        'name': 'University of Richmond',
        'grad_rate_4yr': 82,
        'adj_4yr_grad_rate': 71,
        'white': 83,
        'black': 74,
        'hispanic': 77,
        'asian': 80,
        'otherrace': 82,
        'male': 76,
        'female': 85,
        'nopell': 82,
        'pell': 80,
        'sat_lowest_quintile': 55,
        'sat_2nd_quintile': 70,
        'sat_mid_quintile': 73,
        'sat_4th_quintile': 77,
        'sat_highest_quintile': 85,
        'gpa_lowest_quintile': 74,
        'gpa_2nd_quintile': 65,
        'gpa_mid_quintile': 79,
        'gpa_4th_quintile': 85,
        'gpa_highest_quintile': 86,
        'description': 'University of Richmond, a private liberal arts college, moves up 2 places in the rankings, despite a decrease of 11 percentage points in its graduation rate.'
      },
      {
        'name': 'University of Virginia',
        'grad_rate_4yr': 88,
        'adj_4yr_grad_rate': 66,
        'white': 88,
        'black': 79,
        'hispanic': 88,
        'asian': 89,
        'otherrace': 89,
        'male': 87,
        'female': 89,
        'nopell': 89,
        'pell': 82,
        'sat_lowest_quintile': 73,
        'sat_2nd_quintile': 78,
        'sat_mid_quintile': 80,
        'sat_4th_quintile': 85,
        'sat_highest_quintile': 89,
        'gpa_lowest_quintile': 47,
        'gpa_2nd_quintile': 74,
        'gpa_mid_quintile': 80,
        'gpa_4th_quintile': 85,
        'gpa_highest_quintile': 89,
        'description': 'University of Virginia, a public research university founded by Thomas Jefferson, moves down 3 places in the rankings, reflecting a decrease of 21 percentage points in its graduation rate.'
      },
      {
        'name': 'University of Virginia\'s College at Wise',
        'grad_rate_4yr': 24,
        'adj_4yr_grad_rate': 34,
        'white': 25,
        'black': 13,
        'otherrace': 25,
        'male': 19,
        'female': 28,
        'nopell': 29,
        'pell': 19,
        'sat_lowest_quintile': 17,
        'sat_2nd_quintile': 26,
        'sat_mid_quintile': 36,
        'sat_4th_quintile': 38,
        'sat_highest_quintile': 21,
        'gpa_lowest_quintile': 10,
        'gpa_2nd_quintile': 14,
        'gpa_mid_quintile': 28,
        'gpa_4th_quintile': 36,
        'gpa_highest_quintile': 63,
        'description': 'University of Virginia\'s College at Wise, a public liberal arts college, moves down 4 places in the rankings, despite an increase of 10 percentage points in its graduation rate.'
      },
      {
        'name': 'Virginia Commonwealth University',
        'grad_rate_4yr': 34,
        'adj_4yr_grad_rate': 35,
        'white': 35,
        'black': 31,
        'hispanic': 33,
        'asian': 35,
        'otherrace': 32,
        'male': 28,
        'female': 38,
        'nopell': 35,
        'pell': 30,
        'sat_lowest_quintile': 26,
        'sat_2nd_quintile': 30,
        'sat_mid_quintile': 34,
        'sat_4th_quintile': 36,
        'sat_highest_quintile': 45,
        'gpa_lowest_quintile': 17,
        'gpa_2nd_quintile': 25,
        'gpa_mid_quintile': 34,
        'gpa_4th_quintile': 45,
        'gpa_highest_quintile': 59,
        'description': 'Virginia Commonwealth University, a public research university in Richmond, moves down 8 places in the rankings, despite an increase of 1 percentage points in its graduation rate.'
      },
      {
        'name': 'Virginia Military Institute',
        'grad_rate_4yr': 63,
        'adj_4yr_grad_rate': 67,
        'white': 66,
        'black': 31,
        'hispanic': 54,
        'asian': 70,
        'male': 63,
        'female': 66,
        'nopell': 65,
        'pell': 56,
        'sat_lowest_quintile': 26,
        'sat_2nd_quintile': 49,
        'sat_mid_quintile': 64,
        'sat_4th_quintile': 72,
        'sat_highest_quintile': 67,
        'gpa_lowest_quintile': 31,
        'gpa_2nd_quintile': 56,
        'gpa_mid_quintile': 72,
        'gpa_4th_quintile': 73,
        'gpa_highest_quintile': 80,
        'description': 'Virginia Military Institute, the oldest state-supported military college in the US,  moves up 3 places in the rankings, reflecting an increase of 3 percentage points in its graduation rate.'
      },
      {
        'name': 'Virginia State University',
        'grad_rate_4yr': 24,
        'adj_4yr_grad_rate': 48,
        'white': 21,
        'black': 26,
        'hispanic': 21,
        'otherrace': 20,
        'male': 16,
        'female': 29,
        'nopell': 27,
        'pell': 23,
        'sat_lowest_quintile': 22,
        'sat_2nd_quintile': 27,
        'sat_mid_quintile': 37,
        'sat_4th_quintile': 34,
        'gpa_lowest_quintile': 18,
        'gpa_2nd_quintile': 33,
        'gpa_mid_quintile': 38,
        'gpa_4th_quintile': 52,
        'gpa_highest_quintile': 72,
        'description': 'Virginia State University, a historically black public land-grant university in Ettrick, moves up 12 places in the rankings, reflecting an increase of 24 percentage points in its graduation rate.'
      },
      {
        'name': 'Virginia Tech',
        'grad_rate_4yr': 65,
        'adj_4yr_grad_rate': 52,
        'white': 66,
        'black': 44,
        'hispanic': 58,
        'asian': 65,
        'otherrace': 60,
        'male': 55,
        'female': 76,
        'nopell': 66,
        'pell': 57,
        'sat_lowest_quintile': 50,
        'sat_2nd_quintile': 61,
        'sat_mid_quintile': 65,
        'sat_4th_quintile': 67,
        'sat_highest_quintile': 63,
        'gpa_lowest_quintile': 29,
        'gpa_2nd_quintile': 45,
        'gpa_mid_quintile': 54,
        'gpa_4th_quintile': 64,
        'gpa_highest_quintile': 70,
        'description': 'Virginia Tech, a public land-grant research university, moves down 9 places in the rankings, reflecting a decrease of 13 percentage points in its graduation rate.'
      },
      {
        'name': 'Virginia Union University',
        'grad_rate_4yr': 18,
        'adj_4yr_grad_rate': 49,
        'black': 18,
        'male': 12,
        'female': 23,
        'nopell': 20,
        'pell': 17,
        'sat_lowest_quintile': 18,
        'sat_2nd_quintile': 21,
        'gpa_lowest_quintile': 14,
        'gpa_2nd_quintile': 32,
        'gpa_mid_quintile': 45,
        'description': 'Virginia Union University, a private historically black university in Richmond, moves up 18 places in the rankings, reflecting an increase of 30 percentage points in its graduation rate.'
      },
      {
        'name': 'Virginia Wesleyan College',
        'grad_rate_4yr': 44,
        'adj_4yr_grad_rate': 55,
        'white': 47,
        'black': 37,
        'hispanic': 45,
        'otherrace': 44,
        'male': 37,
        'female': 49,
        'nopell': 49,
        'pell': 36,
        'sat_lowest_quintile': 33,
        'sat_2nd_quintile': 45,
        'sat_mid_quintile': 52,
        'sat_4th_quintile': 61,
        'sat_highest_quintile': 58,
        'gpa_lowest_quintile': 27,
        'gpa_2nd_quintile': 52,
        'gpa_mid_quintile': 48,
        'gpa_4th_quintile': 67,
        'gpa_highest_quintile': 77,
        'description': 'Virginia Wesleyan College, a private university in Virginia Beach, moves up 7 places in the rankings, reflecting an increase of 11 percentage points in its graduation rate.'
      },
      {
        'name': 'Washington and Lee University',
        'grad_rate_4yr': 98,
        'adj_4yr_grad_rate': 82,
        'white': 98,
        'male': 97,
        'nopell': 98,
        'sat_highest_quintile': 98,
        'description': 'Washington and Lee University, a private liberal arts college in Lexington, does not change its rank, despite a decrease of 16 percentage points in its graduation rate.'
      },
      {
        'name': 'State Average',
        'white': 53,
        'black': 28,
        'hispanic': 45,
        'asian': 52,
        'otherrace': 44,
        'male': 40,
        'female': 53,
        'nopell': 52,
        'pell': 33,
        'sat_lowest_quintile': 24,
        'sat_2nd_quintile': 37,
        'sat_mid_quintile': 47,
        'sat_4th_quintile': 56,
        'sat_highest_quintile': 69,
        'gpa_lowest_quintile': 18,
        'gpa_2nd_quintile': 32,
        'gpa_mid_quintile': 46,
        'gpa_4th_quintile': 61,
        'gpa_highest_quintile': 77
      }
    ]
  },
  '2yr': {
    '6yr': [
      {
        'name': 'Blue Ridge Community College',
        'grad_rate_6yr': 37,
        'adj_6yr_grad_rate': 33,
        'white': 40,
        'black': 21,
        'hispanic': 26,
        'otherrace': 30,
        'male': 34,
        'female': 40,
        'nopell': 41,
        'pell': 32,
        'testscore_lowest_quintile': 13,
        'testscore_2nd_quintile': 25,
        'testscore_mid_quintile': 36,
        'testscore_4th_quintile': 42,
        'testscore_highest_quintile': 50,
        'fulltime': 43,
        'parttime': 20,
        'description': 'Blue Ridge Community College moves down 4 places in the rankings, reflecting a decrease of 4 percentage points in its graduation rate.'
      },
      {
        'name': 'Central Virginia Community College',
        'grad_rate_6yr': 31,
        'adj_6yr_grad_rate': 29,
        'white': 35,
        'black': 15,
        'hispanic': 13,
        'otherrace': 30,
        'male': 30,
        'female': 32,
        'nopell': 36,
        'pell': 25,
        'testscore_lowest_quintile': 10,
        'testscore_2nd_quintile': 20,
        'testscore_mid_quintile': 29,
        'testscore_4th_quintile': 35,
        'testscore_highest_quintile': 47,
        'fulltime': 36,
        'parttime': 19,
        'description': 'Central Virginia Community College moves down 2 places in the rankings, reflecting a decrease of 2 percentage points in its graduation rate.'
      },
      {
        'name': 'Dabney S. Lancaster Community College',
        'grad_rate_6yr': 34,
        'adj_6yr_grad_rate': 31,
        'white': 35,
        'male': 37,
        'female': 30,
        'nopell': 40,
        'pell': 28,
        'testscore_lowest_quintile': 13,
        'testscore_2nd_quintile': 14,
        'testscore_mid_quintile': 36,
        'testscore_4th_quintile': 44,
        'testscore_highest_quintile': 50,
        'fulltime': 38,
        'parttime': 13,
        'description': 'Dabney S. Lancaster Community College moves down 5 places in the rankings, reflecting a decrease of 2 percentage points in its graduation rate.'
      },
      {
        'name': 'Danville Community College',
        'grad_rate_6yr': 32,
        'adj_6yr_grad_rate': 34,
        'white': 42,
        'black': 21,
        'male': 30,
        'female': 34,
        'nopell': 44,
        'pell': 26,
        'testscore_lowest_quintile': 12,
        'testscore_2nd_quintile': 25,
        'testscore_mid_quintile': 28,
        'testscore_4th_quintile': 44,
        'testscore_highest_quintile': 51,
        'fulltime': 35,
        'parttime': 18,
        'description': 'Danville Community College moves up 7 places in the rankings, reflecting an increase of 2 percentage points in its graduation rate.'
      },
      {
        'name': 'Eastern Shore Community College',
        'grad_rate_6yr': 28,
        'adj_6yr_grad_rate': 30,
        'white': 33,
        'black': 22,
        'male': 27,
        'female': 29,
        'nopell': 45,
        'pell': 21,
        'testscore_lowest_quintile': 16,
        'testscore_2nd_quintile': 21,
        'testscore_mid_quintile': 22,
        'testscore_4th_quintile': 36,
        'testscore_highest_quintile': 48,
        'fulltime': 33,
        'parttime': 17,
        'description': 'Eastern Shore Community College moves up 2 places in the rankings, reflecting an increase of 2 percentage points in its graduation rate.'
      },
      {
        'name': 'Germanna Community College',
        'grad_rate_6yr': 34,
        'adj_6yr_grad_rate': 33,
        'white': 36,
        'black': 25,
        'hispanic': 32,
        'asian': 49,
        'otherrace': 30,
        'male': 30,
        'female': 39,
        'nopell': 36,
        'pell': 29,
        'testscore_lowest_quintile': 24,
        'testscore_2nd_quintile': 31,
        'testscore_mid_quintile': 33,
        'testscore_4th_quintile': 37,
        'testscore_highest_quintile': 45,
        'fulltime': 41,
        'parttime': 19,
        'description': 'Germanna Community College moves up 1 place in the rankings, despite a decrease of 1 percentage points in its graduation rate.'
      },
      {
        'name': 'J. Sargeant Reynolds Community College',
        'grad_rate_6yr': 23,
        'adj_6yr_grad_rate': 27,
        'white': 28,
        'black': 13,
        'hispanic': 24,
        'asian': 28,
        'otherrace': 23,
        'male': 21,
        'female': 26,
        'nopell': 27,
        'pell': 18,
        'testscore_lowest_quintile': 12,
        'testscore_2nd_quintile': 19,
        'testscore_mid_quintile': 24,
        'testscore_4th_quintile': 28,
        'testscore_highest_quintile': 36,
        'fulltime': 29,
        'parttime': 14,
        'description': 'J. Sargeant Reynolds Community College does not change its rank, despite an increase of 3 percentage points in its graduation rate.'
      },
      {
        'name': 'John Tyler Community College',
        'grad_rate_6yr': 25,
        'adj_6yr_grad_rate': 28,
        'white': 30,
        'black': 13,
        'hispanic': 28,
        'asian': 37,
        'otherrace': 24,
        'male': 23,
        'female': 28,
        'nopell': 28,
        'pell': 20,
        'testscore_lowest_quintile': 14,
        'testscore_2nd_quintile': 21,
        'testscore_mid_quintile': 27,
        'testscore_4th_quintile': 35,
        'testscore_highest_quintile': 37,
        'fulltime': 30,
        'parttime': 13,
        'description': 'John Tyler Community College moves up 3 places in the rankings, reflecting an increase of 3 percentage points in its graduation rate.'
      },
      {
        'name': 'Lord Fairfax Community College',
        'grad_rate_6yr': 35,
        'adj_6yr_grad_rate': 34,
        'white': 37,
        'black': 15,
        'hispanic': 31,
        'otherrace': 31,
        'male': 30,
        'female': 40,
        'nopell': 39,
        'pell': 28,
        'testscore_lowest_quintile': 13,
        'testscore_2nd_quintile': 27,
        'testscore_mid_quintile': 37,
        'testscore_4th_quintile': 38,
        'testscore_highest_quintile': 49,
        'fulltime': 45,
        'parttime': 18,
        'description': 'Lord Fairfax Community College moves up 1 place in the rankings, despite a decrease of 1 percentage points in its graduation rate.'
      },
      {
        'name': 'Mountain Empire Community College',
        'grad_rate_6yr': 30,
        'adj_6yr_grad_rate': 27,
        'white': 31,
        'male': 30,
        'female': 31,
        'nopell': 41,
        'pell': 25,
        'testscore_lowest_quintile': 10,
        'testscore_2nd_quintile': 19,
        'testscore_mid_quintile': 27,
        'testscore_4th_quintile': 32,
        'testscore_highest_quintile': 47,
        'fulltime': 34,
        'parttime': 12,
        'description': 'Mountain Empire Community College moves down 7 places in the rankings, reflecting a decrease of 4 percentage points in its graduation rate.'
      },
      {
        'name': 'New River Community College',
        'grad_rate_6yr': 31,
        'adj_6yr_grad_rate': 31,
        'white': 33,
        'black': 16,
        'otherrace': 27,
        'male': 31,
        'female': 31,
        'nopell': 36,
        'pell': 27,
        'testscore_lowest_quintile': 17,
        'testscore_2nd_quintile': 28,
        'testscore_mid_quintile': 32,
        'testscore_4th_quintile': 40,
        'testscore_highest_quintile': 44,
        'fulltime': 34,
        'parttime': 21,
        'description': 'New River Community College moves down 2 places in the rankings, reflecting a decrease of 1 percentage points in its graduation rate.'
      },
      {
        'name': 'Northern Virginia Community College',
        'grad_rate_6yr': 36,
        'adj_6yr_grad_rate': 35,
        'white': 37,
        'black': 25,
        'hispanic': 34,
        'asian': 51,
        'otherrace': 38,
        'male': 32,
        'female': 42,
        'nopell': 35,
        'pell': 40,
        'testscore_lowest_quintile': 24,
        'testscore_2nd_quintile': 33,
        'testscore_mid_quintile': 39,
        'testscore_4th_quintile': 42,
        'testscore_highest_quintile': 46,
        'fulltime': 44,
        'parttime': 21,
        'description': 'Northern Virginia Community College moves up 2 places in the rankings, despite a decrease of 1 percentage points in its graduation rate.'
      },
      {
        'name': 'Patrick Henry Community College',
        'grad_rate_6yr': 33,
        'adj_6yr_grad_rate': 33,
        'white': 39,
        'black': 21,
        'male': 32,
        'female': 33,
        'nopell': 38,
        'pell': 30,
        'testscore_lowest_quintile': 18,
        'testscore_2nd_quintile': 22,
        'testscore_mid_quintile': 36,
        'testscore_4th_quintile': 42,
        'testscore_highest_quintile': 46,
        'fulltime': 35,
        'parttime': 18,
        'description': 'Patrick Henry Community College moves up 1 place in the rankings, reflecting no change in its graduation rate.'
      },
      {
        'name': 'Paul D. Camp Community College',
        'grad_rate_6yr': 29,
        'adj_6yr_grad_rate': 32,
        'white': 44,
        'black': 10,
        'male': 32,
        'female': 26,
        'nopell': 39,
        'pell': 23,
        'testscore_lowest_quintile': 11,
        'testscore_2nd_quintile': 20,
        'testscore_mid_quintile': 37,
        'testscore_4th_quintile': 50,
        'testscore_highest_quintile': 44,
        'fulltime': 34,
        'parttime': 13,
        'description': 'Paul D. Camp Community College moves up 7 places in the rankings, reflecting an increase of 4 percentage points in its graduation rate.'
      },
      {
        'name': 'Piedmont Virginia Community College',
        'grad_rate_6yr': 25,
        'adj_6yr_grad_rate': 27,
        'white': 29,
        'black': 9,
        'hispanic': 24,
        'otherrace': 26,
        'male': 24,
        'female': 26,
        'nopell': 31,
        'pell': 18,
        'testscore_lowest_quintile': 6,
        'testscore_2nd_quintile': 16,
        'testscore_mid_quintile': 21,
        'testscore_4th_quintile': 31,
        'testscore_highest_quintile': 44,
        'fulltime': 34,
        'parttime': 14,
        'description': 'Piedmont Virginia Community College does not change its rank, despite an increase of 2 percentage points in its graduation rate.'
      },
      {
        'name': 'Rappahannock Community College',
        'grad_rate_6yr': 31,
        'adj_6yr_grad_rate': 32,
        'white': 36,
        'black': 17,
        'hispanic': 31,
        'otherrace': 30,
        'male': 28,
        'female': 34,
        'nopell': 36,
        'pell': 26,
        'testscore_lowest_quintile': 13,
        'testscore_2nd_quintile': 21,
        'testscore_mid_quintile': 34,
        'testscore_4th_quintile': 37,
        'testscore_highest_quintile': 49,
        'fulltime': 37,
        'parttime': 15,
        'description': 'Rappahannock Community College moves up 3 places in the rankings, reflecting an increase of 1 percentage points in its graduation rate.'
      },
      {
        'name': 'Southside Virginia Community College',
        'grad_rate_6yr': 28,
        'adj_6yr_grad_rate': 32,
        'white': 33,
        'black': 23,
        'male': 26,
        'female': 30,
        'nopell': 36,
        'pell': 25,
        'testscore_lowest_quintile': 16,
        'testscore_2nd_quintile': 23,
        'testscore_mid_quintile': 33,
        'testscore_4th_quintile': 23,
        'testscore_highest_quintile': 48,
        'fulltime': 32,
        'parttime': 14,
        'description': 'Southside Virginia Community College moves up 7 places in the rankings, reflecting an increase of 4 percentage points in its graduation rate.'
      },
      {
        'name': 'Southwest Virginia Community College',
        'grad_rate_6yr': 39,
        'adj_6yr_grad_rate': 33,
        'white': 39,
        'male': 35,
        'female': 42,
        'nopell': 45,
        'pell': 35,
        'testscore_lowest_quintile': 20,
        'testscore_2nd_quintile': 19,
        'testscore_mid_quintile': 38,
        'testscore_4th_quintile': 36,
        'testscore_highest_quintile': 55,
        'fulltime': 41,
        'parttime': 19,
        'description': 'Southwest Virginia Community College moves down 6 places in the rankings, reflecting a decrease of 6 percentage points in its graduation rate.'
      },
      {
        'name': 'Thomas Nelson Community College',
        'grad_rate_6yr': 25,
        'adj_6yr_grad_rate': 27,
        'white': 33,
        'black': 12,
        'hispanic': 20,
        'asian': 42,
        'otherrace': 22,
        'male': 22,
        'female': 27,
        'nopell': 32,
        'pell': 14,
        'testscore_lowest_quintile': 9,
        'testscore_2nd_quintile': 18,
        'testscore_mid_quintile': 26,
        'testscore_4th_quintile': 34,
        'testscore_highest_quintile': 37,
        'fulltime': 30,
        'parttime': 14,
        'description': 'Thomas Nelson Community College moves up 2 places in the rankings, reflecting an increase of 3 percentage points in its graduation rate.'
      },
      {
        'name': 'Tidewater Community College',
        'grad_rate_6yr': 26,
        'adj_6yr_grad_rate': 27,
        'white': 33,
        'black': 15,
        'hispanic': 26,
        'asian': 35,
        'otherrace': 26,
        'male': 23,
        'female': 27,
        'nopell': 32,
        'pell': 18,
        'testscore_lowest_quintile': 13,
        'testscore_2nd_quintile': 18,
        'testscore_mid_quintile': 28,
        'testscore_4th_quintile': 32,
        'testscore_highest_quintile': 40,
        'fulltime': 30,
        'parttime': 15,
        'description': 'Tidewater Community College does not change its rank, despite an increase of 2 percentage points in its graduation rate.'
      },
      {
        'name': 'Virginia Highlands Community College',
        'grad_rate_6yr': 32,
        'adj_6yr_grad_rate': 28,
        'white': 33,
        'male': 30,
        'female': 34,
        'nopell': 38,
        'pell': 27,
        'testscore_lowest_quintile': 18,
        'testscore_2nd_quintile': 25,
        'testscore_mid_quintile': 28,
        'testscore_4th_quintile': 31,
        'testscore_highest_quintile': 48,
        'fulltime': 34,
        'parttime': 11,
        'description': 'Virginia Highlands Community College moves down 7 places in the rankings, reflecting a decrease of 5 percentage points in its graduation rate.'
      },
      {
        'name': 'Virginia Western Community College',
        'grad_rate_6yr': 34,
        'adj_6yr_grad_rate': 31,
        'white': 37,
        'black': 15,
        'hispanic': 33,
        'asian': 47,
        'otherrace': 24,
        'male': 32,
        'female': 36,
        'nopell': 38,
        'pell': 28,
        'testscore_lowest_quintile': 13,
        'testscore_2nd_quintile': 23,
        'testscore_mid_quintile': 33,
        'testscore_4th_quintile': 41,
        'testscore_highest_quintile': 47,
        'fulltime': 39,
        'parttime': 16,
        'description': 'Virginia Western Community College moves down 5 places in the rankings, reflecting a decrease of 2 percentage points in its graduation rate.'
      },
      {
        'name': 'Wytheville Community College',
        'grad_rate_6yr': 36,
        'adj_6yr_grad_rate': 35,
        'white': 38,
        'black': 16,
        'male': 33,
        'female': 39,
        'nopell': 49,
        'pell': 30,
        'testscore_lowest_quintile': 18,
        'testscore_2nd_quintile': 30,
        'testscore_mid_quintile': 37,
        'testscore_4th_quintile': 45,
        'testscore_highest_quintile': 50,
        'fulltime': 38,
        'parttime': 23,
        'description': 'Wytheville Community College moves up 2 places in the rankings, despite a decrease of 2 percentage points in its graduation rate.'
      },
      {
        'name': 'State Average',
        'white': 35,
        'black': 18,
        'hispanic': 32,
        'asian': 47,
        'otherrace': 31,
        'male': 28,
        'female': 34,
        'nopell': 35,
        'pell': 27,
        'testscore_lowest_quintile': 17,
        'testscore_2nd_quintile': 25,
        'testscore_mid_quintile': 33,
        'testscore_4th_quintile': 37,
        'testscore_highest_quintile': 44,
        'fulltime': 37,
        'parttime': 17
      }
    ],
    '4yr': [
      {
        'name': 'Blue Ridge Community College',
        'grad_rate_4yr': 30,
        'adj_4yr_grad_rate': 26,
        'white': 33,
        'black': 11,
        'hispanic': 19,
        'otherrace': 20,
        'male': 26,
        'female': 33,
        'nopell': 33,
        'pell': 25,
        'testscore_lowest_quintile': 9,
        'testscore_2nd_quintile': 18,
        'testscore_mid_quintile': 30,
        'testscore_4th_quintile': 34,
        'testscore_highest_quintile': 40,
        'fulltime': 35,
        'parttime': 13
      },
      {
        'name': 'Central Virginia Community College',
        'grad_rate_4yr': 23,
        'adj_4yr_grad_rate': 21,
        'white': 26,
        'black': 12,
        'hispanic': 13,
        'otherrace': 22,
        'male': 21,
        'female': 25,
        'nopell': 26,
        'pell': 20,
        'testscore_lowest_quintile': 6,
        'testscore_2nd_quintile': 13,
        'testscore_mid_quintile': 22,
        'testscore_4th_quintile': 26,
        'testscore_highest_quintile': 36,
        'fulltime': 28,
        'parttime': 11
      },
      {
        'name': 'Dabney S. Lancaster Community College',
        'grad_rate_4yr': 26,
        'adj_4yr_grad_rate': 24,
        'white': 28,
        'male': 29,
        'female': 23,
        'nopell': 33,
        'pell': 21,
        'testscore_lowest_quintile': 6,
        'testscore_2nd_quintile': 10,
        'testscore_mid_quintile': 30,
        'testscore_4th_quintile': 36,
        'testscore_highest_quintile': 40,
        'fulltime': 30,
        'parttime': 9
      },
      {
        'name': 'Danville Community College',
        'grad_rate_4yr': 24,
        'adj_4yr_grad_rate': 25,
        'white': 32,
        'black': 14,
        'male': 23,
        'female': 25,
        'nopell': 32,
        'pell': 20,
        'testscore_lowest_quintile': 6,
        'testscore_2nd_quintile': 16,
        'testscore_mid_quintile': 22,
        'testscore_4th_quintile': 36,
        'testscore_highest_quintile': 41,
        'fulltime': 27,
        'parttime': 13
      },
      {
        'name': 'Eastern Shore Community College',
        'grad_rate_4yr': 21,
        'adj_4yr_grad_rate': 22,
        'white': 26,
        'black': 17,
        'male': 20,
        'female': 21,
        'nopell': 34,
        'pell': 15,
        'testscore_lowest_quintile': 11,
        'testscore_2nd_quintile': 14,
        'testscore_mid_quintile': 17,
        'testscore_4th_quintile': 24,
        'testscore_highest_quintile': 40,
        'fulltime': 26,
        'parttime': 9
      },
      {
        'name': 'Germanna Community College',
        'grad_rate_4yr': 24,
        'adj_4yr_grad_rate': 24,
        'white': 26,
        'black': 15,
        'hispanic': 23,
        'asian': 41,
        'otherrace': 20,
        'male': 21,
        'female': 28,
        'nopell': 26,
        'pell': 19,
        'testscore_lowest_quintile': 16,
        'testscore_2nd_quintile': 21,
        'testscore_mid_quintile': 23,
        'testscore_4th_quintile': 24,
        'testscore_highest_quintile': 35,
        'fulltime': 30,
        'parttime': 12
      },
      {
        'name': 'J. Sargeant Reynolds Community College',
        'grad_rate_4yr': 13,
        'adj_4yr_grad_rate': 16,
        'white': 16,
        'black': 7,
        'hispanic': 11,
        'asian': 19,
        'otherrace': 12,
        'male': 11,
        'female': 16,
        'nopell': 16,
        'pell': 10,
        'testscore_lowest_quintile': 5,
        'testscore_2nd_quintile': 11,
        'testscore_mid_quintile': 13,
        'testscore_4th_quintile': 17,
        'testscore_highest_quintile': 22,
        'fulltime': 17,
        'parttime': 7
      },
      {
        'name': 'John Tyler Community College',
        'grad_rate_4yr': 16,
        'adj_4yr_grad_rate': 19,
        'white': 20,
        'black': 7,
        'hispanic': 21,
        'asian': 20,
        'otherrace': 16,
        'male': 14,
        'female': 18,
        'nopell': 19,
        'pell': 13,
        'testscore_lowest_quintile': 8,
        'testscore_2nd_quintile': 12,
        'testscore_mid_quintile': 16,
        'testscore_4th_quintile': 25,
        'testscore_highest_quintile': 27,
        'fulltime': 20,
        'parttime': 7
      },
      {
        'name': 'Lord Fairfax Community College',
        'grad_rate_4yr': 27,
        'adj_4yr_grad_rate': 26,
        'white': 29,
        'black': 9,
        'hispanic': 21,
        'otherrace': 19,
        'male': 22,
        'female': 31,
        'nopell': 30,
        'pell': 21,
        'testscore_lowest_quintile': 7,
        'testscore_2nd_quintile': 19,
        'testscore_mid_quintile': 29,
        'testscore_4th_quintile': 28,
        'testscore_highest_quintile': 39,
        'fulltime': 35,
        'parttime': 12
      },
      {
        'name': 'Mountain Empire Community College',
        'grad_rate_4yr': 26,
        'adj_4yr_grad_rate': 23,
        'white': 27,
        'male': 26,
        'female': 26,
        'nopell': 37,
        'pell': 21,
        'testscore_lowest_quintile': 9,
        'testscore_2nd_quintile': 14,
        'testscore_mid_quintile': 23,
        'testscore_4th_quintile': 27,
        'testscore_highest_quintile': 42,
        'fulltime': 30,
        'parttime': 9
      },
      {
        'name': 'New River Community College',
        'grad_rate_4yr': 23,
        'adj_4yr_grad_rate': 22,
        'white': 24,
        'black': 11,
        'otherrace': 11,
        'male': 23,
        'female': 22,
        'nopell': 27,
        'pell': 18,
        'testscore_lowest_quintile': 9,
        'testscore_2nd_quintile': 20,
        'testscore_mid_quintile': 22,
        'testscore_4th_quintile': 29,
        'testscore_highest_quintile': 36,
        'fulltime': 25,
        'parttime': 14
      },
      {
        'name': 'Northern Virginia Community College',
        'grad_rate_4yr': 24,
        'adj_4yr_grad_rate': 24,
        'white': 24,
        'black': 16,
        'hispanic': 22,
        'asian': 36,
        'otherrace': 26,
        'male': 20,
        'female': 28,
        'nopell': 23,
        'pell': 28,
        'testscore_lowest_quintile': 14,
        'testscore_2nd_quintile': 21,
        'testscore_mid_quintile': 26,
        'testscore_4th_quintile': 29,
        'testscore_highest_quintile': 32,
        'fulltime': 30,
        'parttime': 12
      },
      {
        'name': 'Patrick Henry Community College',
        'grad_rate_4yr': 26,
        'adj_4yr_grad_rate': 26,
        'white': 32,
        'black': 14,
        'male': 26,
        'female': 27,
        'nopell': 31,
        'pell': 24,
        'testscore_lowest_quintile': 12,
        'testscore_2nd_quintile': 16,
        'testscore_mid_quintile': 29,
        'testscore_4th_quintile': 34,
        'testscore_highest_quintile': 41,
        'fulltime': 29,
        'parttime': 11
      },
      {
        'name': 'Paul D. Camp Community College',
        'grad_rate_4yr': 23,
        'adj_4yr_grad_rate': 26,
        'white': 35,
        'black': 8,
        'male': 27,
        'female': 20,
        'nopell': 30,
        'pell': 19,
        'testscore_lowest_quintile': 7,
        'testscore_2nd_quintile': 13,
        'testscore_mid_quintile': 29,
        'testscore_4th_quintile': 43,
        'testscore_highest_quintile': 41,
        'fulltime': 27,
        'parttime': 10
      },
      {
        'name': 'Piedmont Virginia Community College',
        'grad_rate_4yr': 18,
        'adj_4yr_grad_rate': 20,
        'white': 21,
        'black': 5,
        'hispanic': 17,
        'otherrace': 20,
        'male': 18,
        'female': 18,
        'nopell': 22,
        'pell': 13,
        'testscore_lowest_quintile': 4,
        'testscore_2nd_quintile': 10,
        'testscore_mid_quintile': 14,
        'testscore_4th_quintile': 21,
        'testscore_highest_quintile': 36,
        'fulltime': 27,
        'parttime': 8
      },
      {
        'name': 'Rappahannock Community College',
        'grad_rate_4yr': 24,
        'adj_4yr_grad_rate': 25,
        'white': 27,
        'black': 14,
        'hispanic': 28,
        'otherrace': 25,
        'male': 21,
        'female': 27,
        'nopell': 28,
        'pell': 20,
        'testscore_lowest_quintile': 9,
        'testscore_2nd_quintile': 15,
        'testscore_mid_quintile': 26,
        'testscore_4th_quintile': 27,
        'testscore_highest_quintile': 44,
        'fulltime': 30,
        'parttime': 9
      },
      {
        'name': 'Southside Virginia Community College',
        'grad_rate_4yr': 22,
        'adj_4yr_grad_rate': 25,
        'white': 26,
        'black': 19,
        'male': 22,
        'female': 23,
        'nopell': 31,
        'pell': 20,
        'testscore_lowest_quintile': 12,
        'testscore_2nd_quintile': 19,
        'testscore_mid_quintile': 25,
        'testscore_4th_quintile': 21,
        'testscore_highest_quintile': 41,
        'fulltime': 26,
        'parttime': 9
      },
      {
        'name': 'Southwest Virginia Community College',
        'grad_rate_4yr': 33,
        'adj_4yr_grad_rate': 28,
        'white': 34,
        'male': 29,
        'female': 37,
        'nopell': 39,
        'pell': 29,
        'testscore_lowest_quintile': 15,
        'testscore_2nd_quintile': 16,
        'testscore_mid_quintile': 33,
        'testscore_4th_quintile': 32,
        'testscore_highest_quintile': 46,
        'fulltime': 35,
        'parttime': 15
      },
      {
        'name': 'Thomas Nelson Community College',
        'grad_rate_4yr': 16,
        'adj_4yr_grad_rate': 18,
        'white': 22,
        'black': 5,
        'hispanic': 11,
        'asian': 29,
        'otherrace': 15,
        'male': 13,
        'female': 18,
        'nopell': 20,
        'pell': 9,
        'testscore_lowest_quintile': 5,
        'testscore_2nd_quintile': 11,
        'testscore_mid_quintile': 16,
        'testscore_4th_quintile': 22,
        'testscore_highest_quintile': 25,
        'fulltime': 20,
        'parttime': 7
      },
      {
        'name': 'Tidewater Community College',
        'grad_rate_4yr': 16,
        'adj_4yr_grad_rate': 18,
        'white': 22,
        'black': 8,
        'hispanic': 16,
        'asian': 25,
        'otherrace': 18,
        'male': 14,
        'female': 18,
        'nopell': 21,
        'pell': 11,
        'testscore_lowest_quintile': 6,
        'testscore_2nd_quintile': 11,
        'testscore_mid_quintile': 18,
        'testscore_4th_quintile': 21,
        'testscore_highest_quintile': 29,
        'fulltime': 20,
        'parttime': 7
      },
      {
        'name': 'Virginia Highlands Community College',
        'grad_rate_4yr': 26,
        'adj_4yr_grad_rate': 22,
        'white': 27,
        'male': 25,
        'female': 27,
        'nopell': 31,
        'pell': 21,
        'testscore_lowest_quintile': 8,
        'testscore_2nd_quintile': 18,
        'testscore_mid_quintile': 22,
        'testscore_4th_quintile': 26,
        'testscore_highest_quintile': 41,
        'fulltime': 28,
        'parttime': 5
      },
      {
        'name': 'Virginia Western Community College',
        'grad_rate_4yr': 24,
        'adj_4yr_grad_rate': 22,
        'white': 26,
        'black': 10,
        'hispanic': 26,
        'asian': 31,
        'otherrace': 19,
        'male': 22,
        'female': 26,
        'nopell': 27,
        'pell': 20,
        'testscore_lowest_quintile': 7,
        'testscore_2nd_quintile': 13,
        'testscore_mid_quintile': 21,
        'testscore_4th_quintile': 28,
        'testscore_highest_quintile': 38,
        'fulltime': 28,
        'parttime': 10
      },
      {
        'name': 'Wytheville Community College',
        'grad_rate_4yr': 29,
        'adj_4yr_grad_rate': 27,
        'white': 30,
        'black': 10,
        'male': 27,
        'female': 31,
        'nopell': 40,
        'pell': 23,
        'testscore_lowest_quintile': 15,
        'testscore_2nd_quintile': 24,
        'testscore_mid_quintile': 31,
        'testscore_4th_quintile': 36,
        'testscore_highest_quintile': 39,
        'fulltime': 31,
        'parttime': 17
      },
      {
        'name': 'State Average',
        'white': 25,
        'black': 11,
        'hispanic': 21,
        'asian': 33,
        'otherrace': 21,
        'male': 19,
        'female': 24,
        'nopell': 24,
        'pell': 19,
        'testscore_lowest_quintile': 10,
        'testscore_2nd_quintile': 16,
        'testscore_mid_quintile': 22,
        'testscore_4th_quintile': 26,
        'testscore_highest_quintile': 34,
        'fulltime': 26,
        'parttime': 10
      }
    ]
  }
}
/** END **/

export default data
