// Do not manually modify this file or else it will be overwritten by the
// convert-excel-to-json.js script
const data =
/** START **/
{
  '4yr': {
    '4yr': [
      {
        'name': 'Bluefield College',
        'grad_rate_4yr': 32,
        'adj_4yr_grad_rate': 43,
        'white': 38,
        'male': 20,
        'female': 43,
        'nopell': 35,
        'pell': 29,
        'sat_lowest_quintile': 29,
        'sat_2nd_quintile': 37,
        'gpa_lowest_quintile': 18
      },
      {
        'name': 'Bridgewater College',
        'grad_rate_4yr': 45,
        'adj_4yr_grad_rate': 47,
        'white': 49,
        'black': 21,
        'otherrace': 45,
        'male': 41,
        'female': 48,
        'nopell': 49,
        'pell': 35,
        'sat_lowest_quintile': 37,
        'sat_2nd_quintile': 41,
        'sat_mid_quintile': 57,
        'sat_4th_quintile': 56,
        'gpa_lowest_quintile': 16,
        'gpa_2nd_quintile': 33,
        'gpa_mid_quintile': 41,
        'gpa_4th_quintile': 70,
        'gpa_highest_quintile': 74
      },
      {
        'name': 'Christopher Newport University',
        'grad_rate_4yr': 55,
        'adj_4yr_grad_rate': 50,
        'white': 57,
        'black': 29,
        'otherrace': 48,
        'male': 48,
        'female': 62,
        'nopell': 57,
        'pell': 44,
        'sat_2nd_quintile': 33,
        'sat_mid_quintile': 52,
        'sat_4th_quintile': 59,
        'sat_highest_quintile': 61,
        'gpa_2nd_quintile': 41,
        'gpa_mid_quintile': 50,
        'gpa_4th_quintile': 63,
        'gpa_highest_quintile': 79
      },
      {
        'name': 'College of William and Mary',
        'grad_rate_4yr': 79,
        'adj_4yr_grad_rate': 61,
        'white': 81,
        'black': 71,
        'hispanic': 85,
        'asian': 66,
        'otherrace': 80,
        'male': 73,
        'female': 84,
        'nopell': 79,
        'pell': 75,
        'sat_2nd_quintile': 60,
        'sat_mid_quintile': 77,
        'sat_4th_quintile': 76,
        'sat_highest_quintile': 80,
        'gpa_mid_quintile': 65,
        'gpa_4th_quintile': 75,
        'gpa_highest_quintile': 83
      },
      {
        'name': 'Eastern Mennonite University',
        'grad_rate_4yr': 49,
        'adj_4yr_grad_rate': 48,
        'white': 55,
        'male': 45,
        'female': 52,
        'nopell': 56,
        'pell': 32,
        'sat_lowest_quintile': 27,
        'sat_2nd_quintile': 40,
        'sat_highest_quintile': 77,
        'gpa_2nd_quintile': 19,
        'gpa_mid_quintile': 47,
        'gpa_highest_quintile': 83
      },
      {
        'name': 'Emory and Henry College',
        'grad_rate_4yr': 38,
        'adj_4yr_grad_rate': 41,
        'white': 43,
        'male': 29,
        'female': 50,
        'nopell': 43,
        'pell': 31,
        'sat_lowest_quintile': 17,
        'sat_2nd_quintile': 48,
        'sat_mid_quintile': 43,
        'sat_4th_quintile': 51,
        'gpa_lowest_quintile': 8,
        'gpa_2nd_quintile': 30,
        'gpa_mid_quintile': 37,
        'gpa_4th_quintile': 47,
        'gpa_highest_quintile': 67
      },
      {
        'name': 'Ferrum College',
        'grad_rate_4yr': 18,
        'adj_4yr_grad_rate': 42,
        'white': 20,
        'black': 17,
        'male': 15,
        'female': 22,
        'nopell': 22,
        'pell': 15,
        'sat_lowest_quintile': 16,
        'sat_2nd_quintile': 21,
        'sat_mid_quintile': 21,
        'gpa_lowest_quintile': 13,
        'gpa_2nd_quintile': 13,
        'gpa_mid_quintile': 47
      },
      {
        'name': 'George Mason University',
        'grad_rate_4yr': 39,
        'adj_4yr_grad_rate': 37,
        'white': 41,
        'black': 35,
        'hispanic': 34,
        'asian': 34,
        'otherrace': 41,
        'male': 28,
        'female': 49,
        'nopell': 40,
        'pell': 35,
        'sat_lowest_quintile': 34,
        'sat_2nd_quintile': 40,
        'sat_mid_quintile': 38,
        'sat_4th_quintile': 40,
        'sat_highest_quintile': 38,
        'gpa_lowest_quintile': 8,
        'gpa_2nd_quintile': 27,
        'gpa_mid_quintile': 37,
        'gpa_4th_quintile': 49,
        'gpa_highest_quintile': 56
      },
      {
        'name': 'Hampden-Sydney College',
        'grad_rate_4yr': 54,
        'adj_4yr_grad_rate': 64,
        'white': 55,
        'male': 54,
        'nopell': 55,
        'pell': 49,
        'sat_lowest_quintile': 42,
        'sat_2nd_quintile': 51,
        'sat_mid_quintile': 59,
        'sat_4th_quintile': 49,
        'gpa_lowest_quintile': 40,
        'gpa_2nd_quintile': 49,
        'gpa_mid_quintile': 59
      },
      {
        'name': 'Hampton University',
        'grad_rate_4yr': 35,
        'adj_4yr_grad_rate': 47,
        'black': 35,
        'male': 26,
        'female': 40,
        'nopell': 38,
        'pell': 29,
        'sat_lowest_quintile': 29,
        'sat_2nd_quintile': 40,
        'sat_mid_quintile': 36,
        'sat_4th_quintile': 48,
        'gpa_lowest_quintile': 25,
        'gpa_2nd_quintile': 35,
        'gpa_mid_quintile': 34,
        'gpa_4th_quintile': 59,
        'gpa_highest_quintile': 71
      },
      {
        'name': 'Hollins University',
        'grad_rate_4yr': 53,
        'adj_4yr_grad_rate': 49,
        'white': 56,
        'female': 53,
        'nopell': 70,
        'pell': 33,
        'sat_lowest_quintile': 50,
        'sat_2nd_quintile': 40,
        'sat_highest_quintile': 74,
        'gpa_2nd_quintile': 51,
        'gpa_mid_quintile': 47
      },
      {
        'name': 'James Madison University',
        'grad_rate_4yr': 59,
        'adj_4yr_grad_rate': 50,
        'white': 61,
        'black': 35,
        'hispanic': 64,
        'asian': 56,
        'otherrace': 52,
        'male': 48,
        'female': 65,
        'nopell': 61,
        'pell': 46,
        'sat_lowest_quintile': 35,
        'sat_2nd_quintile': 58,
        'sat_mid_quintile': 59,
        'sat_4th_quintile': 61,
        'sat_highest_quintile': 62,
        'gpa_lowest_quintile': 23,
        'gpa_2nd_quintile': 36,
        'gpa_mid_quintile': 51,
        'gpa_4th_quintile': 61,
        'gpa_highest_quintile': 72
      },
      {
        'name': 'Jefferson College of Health Sciences',
        'grad_rate_4yr': 39,
        'adj_4yr_grad_rate': 44,
        'white': 41,
        'female': 36,
        'nopell': 49,
        'pell': 28,
        'sat_lowest_quintile': 19
      },
      {
        'name': 'Liberty University',
        'grad_rate_4yr': 25,
        'adj_4yr_grad_rate': 35,
        'white': 30,
        'black': 9,
        'hispanic': 23,
        'asian': 13,
        'otherrace': 21,
        'male': 20,
        'female': 29,
        'nopell': 28,
        'pell': 17,
        'sat_lowest_quintile': 15,
        'sat_2nd_quintile': 28,
        'sat_mid_quintile': 34,
        'sat_4th_quintile': 37,
        'sat_highest_quintile': 40,
        'gpa_lowest_quintile': 10,
        'gpa_2nd_quintile': 22,
        'gpa_mid_quintile': 27,
        'gpa_4th_quintile': 44,
        'gpa_highest_quintile': 56
      },
      {
        'name': 'Longwood University',
        'grad_rate_4yr': 43,
        'adj_4yr_grad_rate': 45,
        'white': 46,
        'black': 27,
        'hispanic': 31,
        'otherrace': 32,
        'male': 30,
        'female': 49,
        'nopell': 44,
        'pell': 39,
        'sat_lowest_quintile': 32,
        'sat_2nd_quintile': 45,
        'sat_mid_quintile': 44,
        'sat_4th_quintile': 45,
        'gpa_lowest_quintile': 24,
        'gpa_2nd_quintile': 31,
        'gpa_mid_quintile': 48,
        'gpa_4th_quintile': 63,
        'gpa_highest_quintile': 76
      },
      {
        'name': 'Lynchburg College',
        'grad_rate_4yr': 42,
        'adj_4yr_grad_rate': 50,
        'white': 43,
        'black': 38,
        'male': 30,
        'female': 51,
        'nopell': 44,
        'pell': 35,
        'sat_lowest_quintile': 33,
        'sat_2nd_quintile': 39,
        'sat_mid_quintile': 56,
        'sat_4th_quintile': 46,
        'gpa_lowest_quintile': 24,
        'gpa_2nd_quintile': 37,
        'gpa_mid_quintile': 50,
        'gpa_4th_quintile': 67,
        'gpa_highest_quintile': 77
      },
      {
        'name': 'Mary Baldwin College',
        'grad_rate_4yr': 32,
        'adj_4yr_grad_rate': 39,
        'white': 39,
        'black': 20,
        'female': 32,
        'nopell': 35,
        'pell': 29,
        'sat_lowest_quintile': 30,
        'sat_2nd_quintile': 26,
        'gpa_lowest_quintile': 26,
        'gpa_2nd_quintile': 26,
        'gpa_mid_quintile': 28
      },
      {
        'name': 'Marymount University',
        'grad_rate_4yr': 27,
        'adj_4yr_grad_rate': 38,
        'white': 31,
        'black': 21,
        'hispanic': 39,
        'asian': 28,
        'otherrace': 13,
        'male': 21,
        'female': 30,
        'nopell': 31,
        'pell': 19,
        'sat_lowest_quintile': 19,
        'sat_2nd_quintile': 27,
        'sat_mid_quintile': 39,
        'sat_4th_quintile': 46,
        'gpa_lowest_quintile': 15,
        'gpa_2nd_quintile': 25,
        'gpa_mid_quintile': 40,
        'gpa_4th_quintile': 47
      },
      {
        'name': 'Norfolk State University',
        'grad_rate_4yr': 10,
        'adj_4yr_grad_rate': 34,
        'black': 10,
        'otherrace': 4,
        'male': 6,
        'female': 13,
        'nopell': 13,
        'pell': 8,
        'sat_lowest_quintile': 8,
        'sat_2nd_quintile': 15,
        'sat_mid_quintile': 18,
        'gpa_lowest_quintile': 5,
        'gpa_2nd_quintile': 13,
        'gpa_mid_quintile': 23,
        'gpa_4th_quintile': 38
      },
      {
        'name': 'Old Dominion University',
        'grad_rate_4yr': 19,
        'adj_4yr_grad_rate': 25,
        'white': 21,
        'black': 16,
        'hispanic': 11,
        'asian': 20,
        'otherrace': 19,
        'male': 14,
        'female': 26,
        'nopell': 20,
        'pell': 17,
        'sat_lowest_quintile': 14,
        'sat_2nd_quintile': 17,
        'sat_mid_quintile': 21,
        'sat_4th_quintile': 22,
        'sat_highest_quintile': 34,
        'gpa_lowest_quintile': 9,
        'gpa_2nd_quintile': 14,
        'gpa_mid_quintile': 19,
        'gpa_4th_quintile': 34,
        'gpa_highest_quintile': 54
      },
      {
        'name': 'Radford University',
        'grad_rate_4yr': 36,
        'adj_4yr_grad_rate': 43,
        'white': 38,
        'black': 27,
        'hispanic': 26,
        'otherrace': 21,
        'male': 26,
        'female': 44,
        'nopell': 37,
        'pell': 33,
        'sat_lowest_quintile': 36,
        'sat_2nd_quintile': 32,
        'sat_mid_quintile': 39,
        'sat_4th_quintile': 41,
        'sat_highest_quintile': 41,
        'gpa_lowest_quintile': 23,
        'gpa_2nd_quintile': 33,
        'gpa_mid_quintile': 43,
        'gpa_4th_quintile': 44,
        'gpa_highest_quintile': 82
      },
      {
        'name': 'Randolph College',
        'grad_rate_4yr': 52,
        'adj_4yr_grad_rate': 57,
        'white': 55,
        'black': 49,
        'male': 45,
        'female': 60,
        'nopell': 54,
        'pell': 46,
        'sat_lowest_quintile': 46,
        'sat_2nd_quintile': 46,
        'sat_mid_quintile': 58,
        'sat_4th_quintile': 61,
        'gpa_lowest_quintile': 33,
        'gpa_2nd_quintile': 57,
        'gpa_mid_quintile': 56,
        'gpa_4th_quintile': 56,
        'gpa_highest_quintile': 70
      },
      {
        'name': 'Shenandoah University',
        'grad_rate_4yr': 35,
        'adj_4yr_grad_rate': 42,
        'white': 40,
        'black': 14,
        'otherrace': 29,
        'male': 23,
        'female': 46,
        'nopell': 38,
        'pell': 23,
        'sat_lowest_quintile': 23,
        'sat_2nd_quintile': 36,
        'sat_mid_quintile': 38,
        'sat_4th_quintile': 59,
        'gpa_lowest_quintile': 17,
        'gpa_2nd_quintile': 25,
        'gpa_mid_quintile': 49,
        'gpa_4th_quintile': 53,
        'gpa_highest_quintile': 67
      },
      {
        'name': 'Southern Virginia University',
        'grad_rate_4yr': 10,
        'adj_4yr_grad_rate': 20,
        'white': 9,
        'male': 4,
        'female': 16,
        'nopell': 11,
        'pell': 8,
        'gpa_lowest_quintile': 0
      },
      {
        'name': 'Sweet Briar College',
        'grad_rate_4yr': 52,
        'adj_4yr_grad_rate': 51,
        'white': 55,
        'female': 52,
        'nopell': 57,
        'pell': 39,
        'sat_lowest_quintile': 38,
        'gpa_lowest_quintile': 32,
        'gpa_2nd_quintile': 48,
        'gpa_mid_quintile': 49
      },
      {
        'name': 'University of Mary Washington',
        'grad_rate_4yr': 58,
        'adj_4yr_grad_rate': 53,
        'white': 59,
        'black': 58,
        'hispanic': 43,
        'asian': 54,
        'otherrace': 60,
        'male': 47,
        'female': 64,
        'nopell': 60,
        'pell': 48,
        'sat_lowest_quintile': 43,
        'sat_2nd_quintile': 58,
        'sat_mid_quintile': 55,
        'sat_4th_quintile': 62,
        'sat_highest_quintile': 60,
        'gpa_lowest_quintile': 35,
        'gpa_2nd_quintile': 46,
        'gpa_mid_quintile': 52,
        'gpa_4th_quintile': 70,
        'gpa_highest_quintile': 71
      },
      {
        'name': 'University of Richmond',
        'grad_rate_4yr': 80,
        'adj_4yr_grad_rate': 68,
        'white': 84,
        'black': 72,
        'asian': 75,
        'otherrace': 77,
        'male': 76,
        'female': 83,
        'nopell': 80,
        'pell': 82,
        'sat_mid_quintile': 77,
        'sat_4th_quintile': 78,
        'sat_highest_quintile': 85,
        'gpa_2nd_quintile': 63,
        'gpa_mid_quintile': 76,
        'gpa_4th_quintile': 82,
        'gpa_highest_quintile': 86
      },
      {
        'name': 'University of Virginia',
        'grad_rate_4yr': 87,
        'adj_4yr_grad_rate': 67,
        'white': 86,
        'black': 81,
        'hispanic': 89,
        'asian': 90,
        'otherrace': 87,
        'male': 88,
        'female': 86,
        'nopell': 87,
        'pell': 81,
        'sat_2nd_quintile': 78,
        'sat_mid_quintile': 79,
        'sat_4th_quintile': 82,
        'sat_highest_quintile': 90,
        'gpa_mid_quintile': 87,
        'gpa_4th_quintile': 82,
        'gpa_highest_quintile': 88
      },
      {
        'name': 'University of Virginia\'s College at Wise',
        'grad_rate_4yr': 18,
        'adj_4yr_grad_rate': 31,
        'white': 19,
        'black': 8,
        'male': 15,
        'female': 23,
        'nopell': 23,
        'pell': 14,
        'sat_lowest_quintile': 15,
        'sat_2nd_quintile': 23,
        'sat_mid_quintile': 15,
        'gpa_lowest_quintile': 7,
        'gpa_2nd_quintile': 17,
        'gpa_mid_quintile': 24,
        'gpa_4th_quintile': 34
      },
      {
        'name': 'Virginia Commonwealth University',
        'grad_rate_4yr': 31,
        'adj_4yr_grad_rate': 32,
        'white': 31,
        'black': 30,
        'hispanic': 31,
        'asian': 31,
        'otherrace': 30,
        'male': 26,
        'female': 34,
        'nopell': 32,
        'pell': 26,
        'sat_lowest_quintile': 25,
        'sat_2nd_quintile': 28,
        'sat_mid_quintile': 31,
        'sat_4th_quintile': 33,
        'sat_highest_quintile': 45,
        'gpa_lowest_quintile': 14,
        'gpa_2nd_quintile': 23,
        'gpa_mid_quintile': 30,
        'gpa_4th_quintile': 42,
        'gpa_highest_quintile': 54
      },
      {
        'name': 'Virginia Military Institute',
        'grad_rate_4yr': 60,
        'adj_4yr_grad_rate': 63,
        'white': 62,
        'male': 60,
        'female': 56,
        'nopell': 61,
        'pell': 50,
        'sat_2nd_quintile': 42,
        'sat_mid_quintile': 63,
        'sat_4th_quintile': 69,
        'sat_highest_quintile': 68,
        'gpa_lowest_quintile': 23,
        'gpa_2nd_quintile': 48,
        'gpa_mid_quintile': 71,
        'gpa_4th_quintile': 71,
        'gpa_highest_quintile': 82
      },
      {
        'name': 'Virginia State University',
        'grad_rate_4yr': 29,
        'adj_4yr_grad_rate': 50,
        'black': 30,
        'otherrace': 18,
        'male': 22,
        'female': 33,
        'nopell': 32,
        'pell': 27,
        'sat_lowest_quintile': 29,
        'sat_2nd_quintile': 25,
        'sat_mid_quintile': 39,
        'gpa_lowest_quintile': 21,
        'gpa_2nd_quintile': 39,
        'gpa_mid_quintile': 44,
        'gpa_4th_quintile': 45
      },
      {
        'name': 'Virginia Tech',
        'grad_rate_4yr': 61,
        'adj_4yr_grad_rate': 49,
        'white': 63,
        'black': 41,
        'hispanic': 55,
        'asian': 63,
        'otherrace': 50,
        'male': 51,
        'female': 72,
        'nopell': 62,
        'pell': 52,
        'sat_lowest_quintile': 45,
        'sat_2nd_quintile': 60,
        'sat_mid_quintile': 61,
        'sat_4th_quintile': 62,
        'sat_highest_quintile': 61,
        'gpa_2nd_quintile': 43,
        'gpa_mid_quintile': 50,
        'gpa_4th_quintile': 61,
        'gpa_highest_quintile': 65
      },
      {
        'name': 'Virginia Union University',
        'grad_rate_4yr': 15,
        'adj_4yr_grad_rate': 47,
        'black': 15,
        'male': 12,
        'female': 17,
        'nopell': 19,
        'pell': 12,
        'sat_lowest_quintile': 15,
        'gpa_lowest_quintile': 13,
        'gpa_2nd_quintile': 17
      },
      {
        'name': 'Virginia Wesleyan College',
        'grad_rate_4yr': 40,
        'adj_4yr_grad_rate': 52,
        'white': 45,
        'black': 31,
        'male': 32,
        'female': 46,
        'nopell': 46,
        'pell': 28,
        'sat_lowest_quintile': 35,
        'sat_2nd_quintile': 36,
        'sat_mid_quintile': 51,
        'gpa_lowest_quintile': 25,
        'gpa_2nd_quintile': 46,
        'gpa_4th_quintile': 53
      },
      {
        'name': 'Washington and Lee University',
        'grad_rate_4yr': 88,
        'adj_4yr_grad_rate': 71,
        'white': 87,
        'male': 90,
        'nopell': 88,
        'sat_highest_quintile': 87
      },
      {
        'name': 'State Average',
        'white': 50,
        'black': 28,
        'hispanic': 45,
        'asian': 50,
        'otherrace': 44,
        'male': 38,
        'female': 51,
        'nopell': 50,
        'pell': 31,
        'sat_lowest_quintile': 23,
        'sat_2nd_quintile': 36,
        'sat_mid_quintile': 46,
        'sat_4th_quintile': 54,
        'sat_highest_quintile': 69,
        'gpa_lowest_quintile': 16,
        'gpa_2nd_quintile': 29,
        'gpa_mid_quintile': 42,
        'gpa_4th_quintile': 59,
        'gpa_highest_quintile': 74
      }
    ],
    '6yr': [
      {
        'name': 'Bluefield College',
        'grad_rate_6yr': 41,
        'adj_6yr_grad_rate': 50,
        'white': 45,
        'male': 27,
        'female': 53,
        'nopell': 44,
        'pell': 37,
        'sat_lowest_quintile': 40,
        'sat_2nd_quintile': 40,
        'gpa_lowest_quintile': 29
      },
      {
        'name': 'Bridgewater College',
        'grad_rate_6yr': 53,
        'adj_6yr_grad_rate': 54,
        'white': 57,
        'black': 29,
        'otherrace': 50,
        'male': 54,
        'female': 52,
        'nopell': 57,
        'pell': 42,
        'sat_lowest_quintile': 48,
        'sat_2nd_quintile': 48,
        'sat_mid_quintile': 60,
        'sat_4th_quintile': 65,
        'gpa_lowest_quintile': 27,
        'gpa_2nd_quintile': 41,
        'gpa_mid_quintile': 52,
        'gpa_4th_quintile': 74,
        'gpa_highest_quintile': 76
      },
      {
        'name': 'Christopher Newport University',
        'grad_rate_6yr': 70,
        'adj_6yr_grad_rate': 66,
        'white': 71,
        'black': 54,
        'otherrace': 64,
        'male': 69,
        'female': 71,
        'nopell': 72,
        'pell': 60,
        'sat_2nd_quintile': 52,
        'sat_mid_quintile': 68,
        'sat_4th_quintile': 71,
        'sat_highest_quintile': 75,
        'gpa_2nd_quintile': 64,
        'gpa_mid_quintile': 65,
        'gpa_4th_quintile': 73,
        'gpa_highest_quintile': 86
      },
      {
        'name': 'College of William and Mary',
        'grad_rate_6yr': 89,
        'adj_6yr_grad_rate': 76,
        'white': 91,
        'black': 89,
        'hispanic': 95,
        'asian': 78,
        'otherrace': 91,
        'male': 87,
        'female': 92,
        'nopell': 90,
        'pell': 87,
        'sat_2nd_quintile': 77,
        'sat_mid_quintile': 91,
        'sat_4th_quintile': 91,
        'sat_highest_quintile': 89,
        'gpa_mid_quintile': 84,
        'gpa_4th_quintile': 89,
        'gpa_highest_quintile': 91
      },
      {
        'name': 'Eastern Mennonite University',
        'grad_rate_6yr': 60,
        'adj_6yr_grad_rate': 59,
        'white': 65,
        'male': 56,
        'female': 62,
        'nopell': 68,
        'pell': 40,
        'sat_lowest_quintile': 40,
        'sat_2nd_quintile': 60,
        'sat_highest_quintile': 81,
        'gpa_2nd_quintile': 41,
        'gpa_mid_quintile': 66,
        'gpa_highest_quintile': 88
      },
      {
        'name': 'Emory and Henry College',
        'grad_rate_6yr': 54,
        'adj_6yr_grad_rate': 56,
        'white': 57,
        'male': 44,
        'female': 67,
        'nopell': 57,
        'pell': 49,
        'sat_lowest_quintile': 44,
        'sat_2nd_quintile': 59,
        'sat_mid_quintile': 55,
        'sat_4th_quintile': 60,
        'gpa_lowest_quintile': 17,
        'gpa_2nd_quintile': 48,
        'gpa_mid_quintile': 51,
        'gpa_4th_quintile': 68,
        'gpa_highest_quintile': 81
      },
      {
        'name': 'Ferrum College',
        'grad_rate_6yr': 28,
        'adj_6yr_grad_rate': 48,
        'white': 30,
        'black': 26,
        'male': 24,
        'female': 33,
        'nopell': 32,
        'pell': 25,
        'sat_lowest_quintile': 26,
        'sat_2nd_quintile': 26,
        'sat_mid_quintile': 36,
        'gpa_lowest_quintile': 20,
        'gpa_2nd_quintile': 32,
        'gpa_mid_quintile': 58
      },
      {
        'name': 'George Mason University',
        'grad_rate_6yr': 69,
        'adj_6yr_grad_rate': 67,
        'white': 68,
        'black': 71,
        'hispanic': 68,
        'asian': 72,
        'otherrace': 66,
        'male': 61,
        'female': 76,
        'nopell': 69,
        'pell': 67,
        'sat_lowest_quintile': 68,
        'sat_2nd_quintile': 69,
        'sat_mid_quintile': 71,
        'sat_4th_quintile': 70,
        'sat_highest_quintile': 63,
        'gpa_lowest_quintile': 57,
        'gpa_2nd_quintile': 60,
        'gpa_mid_quintile': 68,
        'gpa_4th_quintile': 75,
        'gpa_highest_quintile': 80
      },
      {
        'name': 'Hampden-Sydney College',
        'grad_rate_6yr': 62,
        'adj_6yr_grad_rate': 69,
        'white': 63,
        'male': 62,
        'nopell': 63,
        'pell': 55,
        'sat_lowest_quintile': 48,
        'sat_2nd_quintile': 55,
        'sat_mid_quintile': 68,
        'sat_4th_quintile': 62,
        'gpa_lowest_quintile': 51,
        'gpa_2nd_quintile': 57,
        'gpa_mid_quintile': 66
      },
      {
        'name': 'Hampton University',
        'grad_rate_6yr': 48,
        'adj_6yr_grad_rate': 57,
        'black': 48,
        'male': 42,
        'female': 52,
        'nopell': 52,
        'pell': 41,
        'sat_lowest_quintile': 44,
        'sat_2nd_quintile': 53,
        'sat_mid_quintile': 48,
        'sat_4th_quintile': 54,
        'gpa_lowest_quintile': 40,
        'gpa_2nd_quintile': 51,
        'gpa_mid_quintile': 46,
        'gpa_4th_quintile': 64,
        'gpa_highest_quintile': 77
      },
      {
        'name': 'Hollins University',
        'grad_rate_6yr': 56,
        'adj_6yr_grad_rate': 54,
        'white': 58,
        'female': 56,
        'nopell': 72,
        'pell': 36,
        'sat_lowest_quintile': 53,
        'sat_2nd_quintile': 40,
        'sat_highest_quintile': 76,
        'gpa_2nd_quintile': 51,
        'gpa_mid_quintile': 47
      },
      {
        'name': 'James Madison University',
        'grad_rate_6yr': 83,
        'adj_6yr_grad_rate': 76,
        'white': 84,
        'black': 68,
        'hispanic': 87,
        'asian': 85,
        'otherrace': 79,
        'male': 79,
        'female': 86,
        'nopell': 84,
        'pell': 75,
        'sat_lowest_quintile': 64,
        'sat_2nd_quintile': 82,
        'sat_mid_quintile': 84,
        'sat_4th_quintile': 85,
        'sat_highest_quintile': 84,
        'gpa_lowest_quintile': 52,
        'gpa_2nd_quintile': 68,
        'gpa_mid_quintile': 81,
        'gpa_4th_quintile': 85,
        'gpa_highest_quintile': 89
      },
      {
        'name': 'Jefferson College of Health Sciences',
        'grad_rate_6yr': 49,
        'adj_6yr_grad_rate': 54,
        'white': 53,
        'female': 47,
        'nopell': 62,
        'pell': 34,
        'sat_lowest_quintile': 35
      },
      {
        'name': 'Liberty University',
        'grad_rate_6yr': 47,
        'adj_6yr_grad_rate': 56,
        'white': 53,
        'black': 28,
        'hispanic': 47,
        'asian': 39,
        'otherrace': 43,
        'male': 42,
        'female': 52,
        'nopell': 52,
        'pell': 37,
        'sat_lowest_quintile': 34,
        'sat_2nd_quintile': 53,
        'sat_mid_quintile': 61,
        'sat_4th_quintile': 62,
        'sat_highest_quintile': 64,
        'gpa_lowest_quintile': 27,
        'gpa_2nd_quintile': 46,
        'gpa_mid_quintile': 57,
        'gpa_4th_quintile': 69,
        'gpa_highest_quintile': 79
      },
      {
        'name': 'Longwood University',
        'grad_rate_6yr': 65,
        'adj_6yr_grad_rate': 67,
        'white': 66,
        'black': 58,
        'hispanic': 53,
        'otherrace': 61,
        'male': 59,
        'female': 68,
        'nopell': 67,
        'pell': 57,
        'sat_lowest_quintile': 54,
        'sat_2nd_quintile': 66,
        'sat_mid_quintile': 67,
        'sat_4th_quintile': 69,
        'gpa_lowest_quintile': 42,
        'gpa_2nd_quintile': 61,
        'gpa_mid_quintile': 69,
        'gpa_4th_quintile': 77,
        'gpa_highest_quintile': 84
      },
      {
        'name': 'Lynchburg College',
        'grad_rate_6yr': 57,
        'adj_6yr_grad_rate': 65,
        'white': 58,
        'black': 57,
        'male': 51,
        'female': 61,
        'nopell': 59,
        'pell': 52,
        'sat_lowest_quintile': 53,
        'sat_2nd_quintile': 55,
        'sat_mid_quintile': 67,
        'sat_4th_quintile': 56,
        'gpa_lowest_quintile': 43,
        'gpa_2nd_quintile': 53,
        'gpa_mid_quintile': 64,
        'gpa_4th_quintile': 78,
        'gpa_highest_quintile': 85
      },
      {
        'name': 'Mary Baldwin College',
        'grad_rate_6yr': 37,
        'adj_6yr_grad_rate': 44,
        'white': 46,
        'black': 24,
        'female': 37,
        'nopell': 41,
        'pell': 33,
        'sat_lowest_quintile': 36,
        'sat_2nd_quintile': 31,
        'gpa_lowest_quintile': 31,
        'gpa_2nd_quintile': 34,
        'gpa_mid_quintile': 31
      },
      {
        'name': 'Marymount University',
        'grad_rate_6yr': 49,
        'adj_6yr_grad_rate': 58,
        'white': 57,
        'black': 35,
        'hispanic': 53,
        'asian': 53,
        'otherrace': 42,
        'male': 44,
        'female': 52,
        'nopell': 54,
        'pell': 38,
        'sat_lowest_quintile': 43,
        'sat_2nd_quintile': 51,
        'sat_mid_quintile': 57,
        'sat_4th_quintile': 62,
        'gpa_lowest_quintile': 40,
        'gpa_2nd_quintile': 42,
        'gpa_mid_quintile': 67,
        'gpa_4th_quintile': 71
      },
      {
        'name': 'Norfolk State University',
        'grad_rate_6yr': 31,
        'adj_6yr_grad_rate': 50,
        'black': 32,
        'otherrace': 14,
        'male': 26,
        'female': 35,
        'nopell': 35,
        'pell': 28,
        'sat_lowest_quintile': 29,
        'sat_2nd_quintile': 38,
        'sat_mid_quintile': 33,
        'gpa_lowest_quintile': 24,
        'gpa_2nd_quintile': 35,
        'gpa_mid_quintile': 49,
        'gpa_4th_quintile': 68
      },
      {
        'name': 'Old Dominion University',
        'grad_rate_6yr': 50,
        'adj_6yr_grad_rate': 54,
        'white': 50,
        'black': 49,
        'hispanic': 55,
        'asian': 50,
        'otherrace': 55,
        'male': 45,
        'female': 57,
        'nopell': 50,
        'pell': 50,
        'sat_lowest_quintile': 48,
        'sat_2nd_quintile': 46,
        'sat_mid_quintile': 53,
        'sat_4th_quintile': 55,
        'sat_highest_quintile': 58,
        'gpa_lowest_quintile': 35,
        'gpa_2nd_quintile': 45,
        'gpa_mid_quintile': 54,
        'gpa_4th_quintile': 66,
        'gpa_highest_quintile': 77
      },
      {
        'name': 'Radford University',
        'grad_rate_6yr': 59,
        'adj_6yr_grad_rate': 65,
        'white': 60,
        'black': 58,
        'hispanic': 41,
        'otherrace': 47,
        'male': 50,
        'female': 65,
        'nopell': 60,
        'pell': 55,
        'sat_lowest_quintile': 57,
        'sat_2nd_quintile': 60,
        'sat_mid_quintile': 58,
        'sat_4th_quintile': 61,
        'sat_highest_quintile': 54,
        'gpa_lowest_quintile': 46,
        'gpa_2nd_quintile': 60,
        'gpa_mid_quintile': 61,
        'gpa_4th_quintile': 65,
        'gpa_highest_quintile': 94
      },
      {
        'name': 'Randolph College',
        'grad_rate_6yr': 58,
        'adj_6yr_grad_rate': 61,
        'white': 60,
        'black': 53,
        'male': 51,
        'female': 65,
        'nopell': 59,
        'pell': 52,
        'sat_lowest_quintile': 51,
        'sat_2nd_quintile': 50,
        'sat_mid_quintile': 64,
        'sat_4th_quintile': 70,
        'gpa_lowest_quintile': 40,
        'gpa_2nd_quintile': 63,
        'gpa_mid_quintile': 63,
        'gpa_4th_quintile': 60,
        'gpa_highest_quintile': 70
      },
      {
        'name': 'Shenandoah University',
        'grad_rate_6yr': 54,
        'adj_6yr_grad_rate': 60,
        'white': 60,
        'black': 30,
        'otherrace': 38,
        'male': 42,
        'female': 64,
        'nopell': 57,
        'pell': 42,
        'sat_lowest_quintile': 47,
        'sat_2nd_quintile': 50,
        'sat_mid_quintile': 56,
        'sat_4th_quintile': 74,
        'gpa_lowest_quintile': 34,
        'gpa_2nd_quintile': 48,
        'gpa_mid_quintile': 68,
        'gpa_4th_quintile': 65,
        'gpa_highest_quintile': 88
      },
      {
        'name': 'Southern Virginia University',
        'grad_rate_6yr': 18,
        'adj_6yr_grad_rate': 27,
        'white': 19,
        'male': 11,
        'female': 27,
        'nopell': 17,
        'pell': 19,
        'gpa_lowest_quintile': 3
      },
      {
        'name': 'Sweet Briar College',
        'grad_rate_6yr': 59,
        'adj_6yr_grad_rate': 60,
        'white': 62,
        'female': 59,
        'nopell': 63,
        'pell': 48,
        'sat_lowest_quintile': 45,
        'gpa_lowest_quintile': 42,
        'gpa_2nd_quintile': 58,
        'gpa_mid_quintile': 54
      },
      {
        'name': 'University of Mary Washington',
        'grad_rate_6yr': 71,
        'adj_6yr_grad_rate': 68,
        'white': 71,
        'black': 68,
        'hispanic': 71,
        'asian': 67,
        'otherrace': 73,
        'male': 63,
        'female': 76,
        'nopell': 72,
        'pell': 68,
        'sat_lowest_quintile': 50,
        'sat_2nd_quintile': 73,
        'sat_mid_quintile': 70,
        'sat_4th_quintile': 76,
        'sat_highest_quintile': 73,
        'gpa_lowest_quintile': 57,
        'gpa_2nd_quintile': 60,
        'gpa_mid_quintile': 71,
        'gpa_4th_quintile': 80,
        'gpa_highest_quintile': 78
      },
      {
        'name': 'University of Richmond',
        'grad_rate_6yr': 88,
        'adj_6yr_grad_rate': 79,
        'white': 89,
        'black': 89,
        'asian': 88,
        'otherrace': 86,
        'male': 87,
        'female': 89,
        'nopell': 87,
        'pell': 93,
        'sat_mid_quintile': 87,
        'sat_4th_quintile': 87,
        'sat_highest_quintile': 91,
        'gpa_2nd_quintile': 74,
        'gpa_mid_quintile': 88,
        'gpa_4th_quintile': 91,
        'gpa_highest_quintile': 90
      },
      {
        'name': 'University of Virginia',
        'grad_rate_6yr': 94,
        'adj_6yr_grad_rate': 78,
        'white': 95,
        'black': 90,
        'hispanic': 92,
        'asian': 96,
        'otherrace': 94,
        'male': 93,
        'female': 95,
        'nopell': 95,
        'pell': 90,
        'sat_2nd_quintile': 91,
        'sat_mid_quintile': 91,
        'sat_4th_quintile': 91,
        'sat_highest_quintile': 96,
        'gpa_mid_quintile': 93,
        'gpa_4th_quintile': 91,
        'gpa_highest_quintile': 95
      },
      {
        'name': 'University of Virginia\'s College at Wise',
        'grad_rate_6yr': 40,
        'adj_6yr_grad_rate': 50,
        'white': 40,
        'black': 33,
        'male': 31,
        'female': 53,
        'nopell': 41,
        'pell': 39,
        'sat_lowest_quintile': 35,
        'sat_2nd_quintile': 48,
        'sat_mid_quintile': 44,
        'gpa_lowest_quintile': 27,
        'gpa_2nd_quintile': 36,
        'gpa_mid_quintile': 47,
        'gpa_4th_quintile': 59
      },
      {
        'name': 'Virginia Commonwealth University',
        'grad_rate_6yr': 61,
        'adj_6yr_grad_rate': 62,
        'white': 59,
        'black': 63,
        'hispanic': 55,
        'asian': 65,
        'otherrace': 58,
        'male': 56,
        'female': 64,
        'nopell': 62,
        'pell': 58,
        'sat_lowest_quintile': 59,
        'sat_2nd_quintile': 60,
        'sat_mid_quintile': 62,
        'sat_4th_quintile': 58,
        'sat_highest_quintile': 65,
        'gpa_lowest_quintile': 44,
        'gpa_2nd_quintile': 56,
        'gpa_mid_quintile': 60,
        'gpa_4th_quintile': 71,
        'gpa_highest_quintile': 80
      },
      {
        'name': 'Virginia Military Institute',
        'grad_rate_6yr': 73,
        'adj_6yr_grad_rate': 76,
        'white': 74,
        'male': 74,
        'female': 67,
        'nopell': 76,
        'pell': 59,
        'sat_2nd_quintile': 70,
        'sat_mid_quintile': 73,
        'sat_4th_quintile': 78,
        'sat_highest_quintile': 77,
        'gpa_lowest_quintile': 52,
        'gpa_2nd_quintile': 64,
        'gpa_mid_quintile': 83,
        'gpa_4th_quintile': 81,
        'gpa_highest_quintile': 86
      },
      {
        'name': 'Virginia State University',
        'grad_rate_6yr': 47,
        'adj_6yr_grad_rate': 64,
        'black': 49,
        'otherrace': 35,
        'male': 44,
        'female': 49,
        'nopell': 51,
        'pell': 45,
        'sat_lowest_quintile': 48,
        'sat_2nd_quintile': 42,
        'sat_mid_quintile': 51,
        'gpa_lowest_quintile': 40,
        'gpa_2nd_quintile': 54,
        'gpa_mid_quintile': 60,
        'gpa_4th_quintile': 67
      },
      {
        'name': 'Virginia Tech',
        'grad_rate_6yr': 86,
        'adj_6yr_grad_rate': 76,
        'white': 87,
        'black': 73,
        'hispanic': 87,
        'asian': 85,
        'otherrace': 78,
        'male': 83,
        'female': 89,
        'nopell': 87,
        'pell': 77,
        'sat_lowest_quintile': 63,
        'sat_2nd_quintile': 86,
        'sat_mid_quintile': 84,
        'sat_4th_quintile': 87,
        'sat_highest_quintile': 86,
        'gpa_2nd_quintile': 71,
        'gpa_mid_quintile': 78,
        'gpa_4th_quintile': 87,
        'gpa_highest_quintile': 88
      },
      {
        'name': 'Virginia Union University',
        'grad_rate_6yr': 34,
        'adj_6yr_grad_rate': 60,
        'black': 35,
        'male': 34,
        'female': 35,
        'nopell': 37,
        'pell': 33,
        'sat_lowest_quintile': 35,
        'gpa_lowest_quintile': 32,
        'gpa_2nd_quintile': 49
      },
      {
        'name': 'Virginia Wesleyan College',
        'grad_rate_6yr': 45,
        'adj_6yr_grad_rate': 56,
        'white': 49,
        'black': 41,
        'male': 40,
        'female': 50,
        'nopell': 51,
        'pell': 33,
        'sat_lowest_quintile': 39,
        'sat_2nd_quintile': 42,
        'sat_mid_quintile': 59,
        'gpa_lowest_quintile': 32,
        'gpa_2nd_quintile': 53,
        'gpa_4th_quintile': 53
      },
      {
        'name': 'Washington and Lee University',
        'grad_rate_6yr': 88,
        'adj_6yr_grad_rate': 74,
        'white': 87,
        'male': 90,
        'nopell': 88,
        'sat_highest_quintile': 87
      },
      {
        'name': 'State Average',
        'white': 70,
        'black': 49,
        'hispanic': 66,
        'asian': 75,
        'otherrace': 63,
        'male': 61,
        'female': 69,
        'nopell': 70,
        'pell': 52,
        'sat_lowest_quintile': 43,
        'sat_2nd_quintile': 59,
        'sat_mid_quintile': 69,
        'sat_4th_quintile': 76,
        'sat_highest_quintile': 84,
        'gpa_lowest_quintile': 35,
        'gpa_2nd_quintile': 54,
        'gpa_mid_quintile': 66,
        'gpa_4th_quintile': 80,
        'gpa_highest_quintile': 88
      }
    ]
  },
  '2yr': {
    '6yr': [
      {
        'name': 'Blue Ridge Community College',
        'grad_rate_6yr': 23,
        'adj_6yr_grad_rate': 21,
        'white': 23,
        'male': 28,
        'female': 17,
        'nopell': 18,
        'pell': 32,
        'fulltime': 29
      },
      {
        'name': 'Central Virginia Community College',
        'grad_rate_6yr': 27,
        'adj_6yr_grad_rate': 26,
        'white': 30,
        'male': 27,
        'nopell': 32,
        'fulltime': 34
      },
      {
        'name': 'Dabney S. Lancaster Community College'
      },
      {
        'name': 'Danville Community College',
        'grad_rate_6yr': 26,
        'adj_6yr_grad_rate': 29,
        'pell': 19,
        'fulltime': 28
      },
      {
        'name': 'Eastern Shore Community College'
      },
      {
        'name': 'Germanna Community College',
        'grad_rate_6yr': 28,
        'adj_6yr_grad_rate': 29,
        'nopell': 32
      },
      {
        'name': 'J Sargeant Reynolds Community College',
        'grad_rate_6yr': 17,
        'adj_6yr_grad_rate': 20,
        'white': 18,
        'black': 16,
        'male': 17,
        'female': 18,
        'nopell': 18,
        'pell': 15,
        'testscore_lowest_quintile': 13,
        'testscore_2nd_quintile': 7,
        'testscore_mid_quintile': 27,
        'testscore_highest_quintile': 29,
        'fulltime': 21,
        'parttime': 13
      },
      {
        'name': 'John Tyler Community College',
        'grad_rate_6yr': 18,
        'adj_6yr_grad_rate': 21,
        'white': 28,
        'black': 5,
        'male': 22,
        'female': 14,
        'nopell': 20,
        'pell': 15,
        'fulltime': 26,
        'parttime': 3
      },
      {
        'name': 'Lord Fairfax Community College',
        'grad_rate_6yr': 22,
        'adj_6yr_grad_rate': 22,
        'white': 24,
        'male': 20,
        'nopell': 19,
        'fulltime': 30
      },
      {
        'name': 'Mountain Empire Community College',
        'grad_rate_6yr': 18,
        'adj_6yr_grad_rate': 16,
        'white': 19,
        'male': 19,
        'female': 17,
        'pell': 14,
        'fulltime': 21
      },
      {
        'name': 'New River Community College',
        'grad_rate_6yr': 30,
        'adj_6yr_grad_rate': 27,
        'white': 32,
        'male': 34,
        'female': 22,
        'nopell': 34,
        'pell': 24,
        'fulltime': 34
      },
      {
        'name': 'Northern Virginia Community College',
        'grad_rate_6yr': 23,
        'adj_6yr_grad_rate': 22,
        'white': 25,
        'black': 14,
        'hispanic': 20,
        'asian': 32,
        'otherrace': 17,
        'male': 20,
        'female': 27,
        'nopell': 22,
        'pell': 25,
        'testscore_lowest_quintile': 13,
        'testscore_2nd_quintile': 22,
        'testscore_mid_quintile': 22,
        'testscore_4th_quintile': 27,
        'testscore_highest_quintile': 28,
        'fulltime': 28,
        'parttime': 11
      },
      {
        'name': 'Patrick Henry Community College',
        'grad_rate_6yr': 33,
        'adj_6yr_grad_rate': 34,
        'male': 38,
        'fulltime': 39
      },
      {
        'name': 'Paul D Camp Community College'
      },
      {
        'name': 'Piedmont Virginia Community College'
      },
      {
        'name': 'Rappahannock Community College',
        'grad_rate_6yr': 14,
        'adj_6yr_grad_rate': 14,
        'white': 15,
        'female': 16,
        'pell': 14,
        'fulltime': 11
      },
      {
        'name': 'Southside Virginia Community College',
        'grad_rate_6yr': 17,
        'adj_6yr_grad_rate': 21,
        'white': 15,
        'black': 18,
        'male': 15,
        'female': 19,
        'pell': 18,
        'fulltime': 21
      },
      {
        'name': 'Southwest Virginia Community College',
        'grad_rate_6yr': 26,
        'adj_6yr_grad_rate': 22,
        'white': 26,
        'male': 18,
        'pell': 26,
        'fulltime': 27
      },
      {
        'name': 'Thomas Nelson Community College',
        'grad_rate_6yr': 17,
        'adj_6yr_grad_rate': 19,
        'white': 24,
        'black': 4,
        'male': 15,
        'female': 18,
        'nopell': 23,
        'pell': 8,
        'testscore_lowest_quintile': 6,
        'testscore_2nd_quintile': 10,
        'testscore_mid_quintile': 16,
        'testscore_4th_quintile': 35,
        'testscore_highest_quintile': 21,
        'fulltime': 24,
        'parttime': 3
      },
      {
        'name': 'Tidewater Community College',
        'grad_rate_6yr': 16,
        'adj_6yr_grad_rate': 17,
        'white': 21,
        'black': 12,
        'hispanic': 6,
        'asian': 22,
        'male': 16,
        'female': 17,
        'nopell': 19,
        'pell': 14,
        'testscore_lowest_quintile': 11,
        'testscore_2nd_quintile': 14,
        'testscore_mid_quintile': 12,
        'testscore_4th_quintile': 17,
        'testscore_highest_quintile': 29,
        'fulltime': 18,
        'parttime': 11
      },
      {
        'name': 'Virginia Highlands Community College',
        'grad_rate_6yr': 28,
        'adj_6yr_grad_rate': 25,
        'white': 29,
        'male': 26,
        'pell': 26,
        'fulltime': 32
      },
      {
        'name': 'Virginia Western Community College',
        'grad_rate_6yr': 21,
        'adj_6yr_grad_rate': 20,
        'white': 23,
        'black': 8,
        'male': 23,
        'female': 19,
        'nopell': 24,
        'pell': 19,
        'testscore_lowest_quintile': 7,
        'testscore_mid_quintile': 23,
        'testscore_4th_quintile': 31,
        'testscore_highest_quintile': 30,
        'fulltime': 27,
        'parttime': 5
      },
      {
        'name': 'Wytheville Community College',
        'grad_rate_6yr': 26,
        'adj_6yr_grad_rate': 23,
        'white': 27,
        'male': 26,
        'female': 27,
        'nopell': 40,
        'pell': 18,
        'testscore_2nd_quintile': 17,
        'fulltime': 28
      },
      {
        'name': 'State Average',
        'white': 24,
        'black': 13,
        'hispanic': 19,
        'asian': 29,
        'otherrace': 20,
        'male': 20,
        'female': 22,
        'nopell': 23,
        'pell': 18,
        'testscore_lowest_quintile': 11,
        'testscore_2nd_quintile': 17,
        'testscore_mid_quintile': 19,
        'testscore_4th_quintile': 26,
        'testscore_highest_quintile': 31,
        'fulltime': 25,
        'parttime': 10
      }
    ],
    '4yr': [
      {
        'name': 'Blue Ridge Community College',
        'grad_rate_4yr': 17,
        'adj_4yr_grad_rate': 16,
        'white': 18,
        'male': 18,
        'female': 17,
        'nopell': 15,
        'pell': 23,
        'fulltime': 23
      },
      {
        'name': 'Central Virginia Community College',
        'grad_rate_4yr': 16,
        'adj_4yr_grad_rate': 15,
        'white': 18,
        'male': 20,
        'nopell': 21,
        'fulltime': 22
      },
      {
        'name': 'Dabney S. Lancaster Community College'
      },
      {
        'name': 'Danville Community College',
        'grad_rate_4yr': 19,
        'adj_4yr_grad_rate': 20,
        'pell': 13,
        'fulltime': 22
      },
      {
        'name': 'Eastern Shore Community College'
      },
      {
        'name': 'Germanna Community College',
        'grad_rate_4yr': 13,
        'adj_4yr_grad_rate': 13,
        'nopell': 13
      },
      {
        'name': 'J Sargeant Reynolds Community College',
        'grad_rate_4yr': 10,
        'adj_4yr_grad_rate': 11,
        'white': 12,
        'black': 9,
        'male': 10,
        'female': 9,
        'nopell': 12,
        'pell': 7,
        'testscore_lowest_quintile': 5,
        'testscore_2nd_quintile': 4,
        'testscore_mid_quintile': 16,
        'testscore_highest_quintile': 19,
        'fulltime': 13,
        'parttime': 6
      },
      {
        'name': 'John Tyler Community College',
        'grad_rate_4yr': 11,
        'adj_4yr_grad_rate': 13,
        'white': 20,
        'black': 2,
        'male': 16,
        'female': 8,
        'nopell': 15,
        'pell': 7,
        'fulltime': 16,
        'parttime': 3
      },
      {
        'name': 'Lord Fairfax Community College',
        'grad_rate_4yr': 10,
        'adj_4yr_grad_rate': 10,
        'white': 12,
        'male': 9,
        'nopell': 9,
        'fulltime': 15
      },
      {
        'name': 'Mountain Empire Community College',
        'grad_rate_4yr': 15,
        'adj_4yr_grad_rate': 14,
        'white': 16,
        'male': 16,
        'female': 15,
        'pell': 13,
        'fulltime': 18
      },
      {
        'name': 'New River Community College',
        'grad_rate_4yr': 19,
        'adj_4yr_grad_rate': 18,
        'white': 21,
        'male': 23,
        'female': 13,
        'nopell': 23,
        'pell': 15,
        'fulltime': 21
      },
      {
        'name': 'Northern Virginia Community College',
        'grad_rate_4yr': 8,
        'adj_4yr_grad_rate': 9,
        'white': 11,
        'black': 6,
        'hispanic': 5,
        'asian': 9,
        'otherrace': 3,
        'male': 7,
        'female': 11,
        'nopell': 9,
        'pell': 7,
        'testscore_lowest_quintile': 2,
        'testscore_2nd_quintile': 7,
        'testscore_mid_quintile': 8,
        'testscore_4th_quintile': 11,
        'testscore_highest_quintile': 13,
        'fulltime': 11,
        'parttime': 4
      },
      {
        'name': 'Patrick Henry Community College',
        'grad_rate_4yr': 26,
        'adj_4yr_grad_rate': 25,
        'male': 31,
        'fulltime': 29
      },
      {
        'name': 'Paul D Camp Community College'
      },
      {
        'name': 'Piedmont Virginia Community College'
      },
      {
        'name': 'Rappahannock Community College',
        'grad_rate_4yr': 5,
        'adj_4yr_grad_rate': 5,
        'white': 4,
        'female': 5,
        'pell': 6,
        'fulltime': 5
      },
      {
        'name': 'Southside Virginia Community College',
        'grad_rate_4yr': 12,
        'adj_4yr_grad_rate': 14,
        'white': 12,
        'black': 12,
        'male': 9,
        'female': 16,
        'pell': 14,
        'fulltime': 16
      },
      {
        'name': 'Southwest Virginia Community College',
        'grad_rate_4yr': 25,
        'adj_4yr_grad_rate': 22,
        'white': 24,
        'male': 16,
        'pell': 26,
        'fulltime': 27
      },
      {
        'name': 'Thomas Nelson Community College',
        'grad_rate_4yr': 9,
        'adj_4yr_grad_rate': 9,
        'white': 17,
        'black': 0,
        'male': 8,
        'female': 10,
        'nopell': 11,
        'pell': 5,
        'testscore_lowest_quintile': 0,
        'testscore_2nd_quintile': 5,
        'testscore_mid_quintile': 13,
        'testscore_4th_quintile': 22,
        'testscore_highest_quintile': 8,
        'fulltime': 13,
        'parttime': 1
      },
      {
        'name': 'Tidewater Community College',
        'grad_rate_4yr': 7,
        'adj_4yr_grad_rate': 8,
        'white': 9,
        'black': 5,
        'hispanic': 6,
        'asian': 10,
        'male': 7,
        'female': 7,
        'nopell': 8,
        'pell': 6,
        'testscore_lowest_quintile': 4,
        'testscore_2nd_quintile': 6,
        'testscore_mid_quintile': 6,
        'testscore_4th_quintile': 6,
        'testscore_highest_quintile': 15,
        'fulltime': 9,
        'parttime': 4
      },
      {
        'name': 'Virginia Highlands Community College',
        'grad_rate_4yr': 21,
        'adj_4yr_grad_rate': 18,
        'white': 21,
        'male': 21,
        'pell': 23,
        'fulltime': 23
      },
      {
        'name': 'Virginia Western Community College',
        'grad_rate_4yr': 15,
        'adj_4yr_grad_rate': 14,
        'white': 16,
        'black': 8,
        'male': 16,
        'female': 13,
        'nopell': 14,
        'pell': 16,
        'testscore_lowest_quintile': 0,
        'testscore_mid_quintile': 10,
        'testscore_4th_quintile': 23,
        'testscore_highest_quintile': 28,
        'fulltime': 19,
        'parttime': 5
      },
      {
        'name': 'Wytheville Community College',
        'grad_rate_4yr': 18,
        'adj_4yr_grad_rate': 16,
        'white': 19,
        'male': 20,
        'female': 18,
        'nopell': 26,
        'pell': 14,
        'testscore_2nd_quintile': 10,
        'fulltime': 19
      },
      {
        'name': 'State Average',
        'white': 14,
        'black': 6,
        'hispanic': 7,
        'asian': 9,
        'otherrace': 8,
        'male': 11,
        'female': 11,
        'nopell': 11,
        'pell': 11,
        'testscore_lowest_quintile': 4,
        'testscore_2nd_quintile': 9,
        'testscore_mid_quintile': 10,
        'testscore_4th_quintile': 14,
        'testscore_highest_quintile': 18,
        'fulltime': 14,
        'parttime': 5
      }
    ]
  }
}
/** END **/

export default data
